### PR TITLE
Bump several package version numbers in preparation for 1.18

### PR DESCRIPTION
**Pull request by d-torrance**
I have participated in some nontrivial contributions to several packages which are probably worthy of version bumps before 1.18 is released (`gfanInterface`, `Posets`, `Graphs`, `Chordal`, and `Markov`).  Note that I'm not listed as an author on any of these packages.

### CODE REVIEW

**Comment by d-torrance** [comment]
The [autotools-ubuntu-20.04-default build](https://github.com/Macaulay2/M2/pull/2081/checks?check_run_id=2592868183) had another new instance of #1742 from the `MultiprojectiveVarieties` package:

```m2
 -- making example results for "MultirationalMap * MultirationalMap"        
 ulimit -c unlimited; ulimit -t 700; ulimit -m 850000; ulimit -s 8192; ulimit -n 512;  cd /tmp/M2-106635-0/38-rundir/; GC_MAXIMUM_HEAP_SIZE=400M "/home/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Linux-Ubuntu-20.04/bin/M2-binary" -q --int --no-randomize --no-readline --silent --stop --print-width 77 -e 'needsPackage("MultiprojectiveVarieties",Reload=>true,FileName=>"/home/runner/work/M2/M2/M2/Macaulay2/packages/MultiprojectiveVarieties.m2")' <"/tmp/M2-106635-0/0___Multirational__Map_sp_st_sp__Multirational__Map.m2" >>"/home/runner/work/M2/M2/M2/BUILD/build/usr-dist/common/share/doc/Macaulay2/MultiprojectiveVarieties/example-output/___Multirational__Map_sp_st_sp__Multirational__Map.errors" 2>&1
/home/runner/work/M2/M2/M2/BUILD/build/usr-dist/common/share/doc/Macaulay2/MultiprojectiveVarieties/example-output/___Multirational__Map_sp_st_sp__Multirational__Map.errors:0:1: (output file) error: Macaulay2 exited with status code 1
/tmp/M2-106635-0/0___Multirational__Map_sp_st_sp__Multirational__Map.m2:0:1: (input file)
M2: *** Error 1
 -- 1.44143 seconds elapsed
 -- storing example results in ../../../usr-dist/common/share/doc/Macaulay2/MultiprojectiveVarieties/example-output/___Multirational__Map_sp_st_sp__Multirational__Map.out
 -- warning: missing file /home/runner/work/M2/M2/M2/BUILD/build/usr-dist/common/share/doc/Macaulay2/MultiprojectiveVarieties/example-output/___Multirational__Map_sp_st_sp__Multirational__Map.out

...

../../../../../Macaulay2/m2/debugging.m2:20:6:(1):[9]: error: installPackage: 1 error(s) occurred running examples for package MultiprojectiveVarieties:

___Multirational__Map_sp_st_sp__Multirational__Map.errors
*********************************************************
-- -*- M2-comint -*- hash: -1302520141

i1 : ZZ/65521[x_0..x_4];

i2 : Psi = last graph rationalMap(projectiveVariety ideal(x_4,x_2^2-x_1*x_3,x_1*x_2-x_0*x_3,x_1^2-x_0*x_2),Dominant=>true);

o2 : MultirationalMap (dominant rational map from 4-dimensional subvariety of PP^4 x PP^7 to 4-dimensional subvariety of PP^7)

i3 : Phi = first graph Psi;
-- SIGSEGV
-* stack trace, pid: 107174
 0# stack_trace(std::ostream&, bool) at ../../../../Macaulay2/d/main.cpp:124
 1# segv_handler at ../../../../Macaulay2/d/main.cpp:241
 2# 0x00007FB86E5A2210 in /lib/x86_64-linux-gnu/libc.so.6
 3# MonomialIdeal::sat(MonomialIdeal const&) const at ../../../../Macaulay2/e/monideal.cpp:787
 4# rawSaturateMonomialIdeal2 at ../../../../Macaulay2/e/interface/monomial-ideal.cpp:189
 5# interface_rawSaturate at ../../../../Macaulay2/d/interface.dd:292
 6# evaluate_evalraw at ../../../../Macaulay2/d/evaluate.d:1297
```

**Comment by d-torrance** [comment]
Just pushed another commit adding some related information to `changes.m2`, in particular the changes from #1933.  I already mentioned they were coming in the [Google group](https://groups.google.com/g/macaulay2/c/bk762al8FpE/m/t9fvlo1nAwAJ), and the changes are big enough that they're probably worth mentioning.

**Comment by DanGrayson** [comment]
Thanks, Doug!

Authors, if there are any objections to these version numbers being bumped, let us know.  ( @dcookii @gwynwhieldon @abokeefe @jburkar1 @diegcif @luisgarciapuente @mikestillman )

**Comment by diegcif** [comment]
That's fine with me.

**Comment by gwynwhieldon** [comment]
Yeah works for me too.

**Comment by dcookii** [comment]
Fine with me.  Thanks.

**Comment by d-torrance** [comment]
There were some conflicts in `changes.m2` after 10c210d22f7a8a2a8e6c120654, so I rebased on top of `development` and force-pushed.

**Pull request merged**
