### PR TITLE
fix typos in the doc

### PR DESCRIPTION
**Pull request by fchapoton**
hopefully without parasite modified files

### CODE REVIEW

**Comment by DanGrayson** [comment]
I wonder why our builds keep getting cancelled.

**Comment by mahrud** [comment]
While you were waiting to merge #1809, another build using the old flint2 succeeded, which caused the github actions cache to be populated with the old flint, and discarding the cache isn't easy.

Wait for #1825 to finish building, then rerun the tests.

**Comment by DanGrayson** [comment]
> While you were waiting to merge #1809, another build using the old flint2 succeeded, which caused the github actions cache to be populated with the old flint, and discarding the cache isn't easy.
> 

How does an old flint in the cache result in a cancellation?

**Comment by DanGrayson** [comment]
> Wait for #1825 to finish building, then rerun the tests.

No luck: https://github.com/Macaulay2/M2/actions/runs/490457713

**Comment by DanGrayson** [comment]
> > Wait for #1825 to finish building, then rerun the tests.
> 
> No luck: https://github.com/Macaulay2/M2/actions/runs/490457713

Probably the cache created by #1825 is not accessible to builds on other branches.

**Comment by mahrud** [comment]
Nevermind then, this is a bug.

**Comment by DanGrayson** [comment]
@fchapoton -- I've merged the current development branch into your branch here, in an attempt to get the builds to work.

@mahrud -- why is it that corruption in the cache causes cancellation of the builds?

**Pull request merged**
