### PR TITLE
some improvements to toMap and added approximateInverseMap

### PR DESCRIPTION
**Pull request by giovannistagliano**

### CODE REVIEW

**Comment by DanGrayson** [comment]
Could you resolve the conflicts?

**Comment by giovannistagliano** [comment]
Sure.

**Comment by giovannistagliano** [comment]
Could you delete this pull request? I will open another one.

**Comment by DanGrayson** [comment]
You should see a button at the bottom called "Close and comment" that will allow you to do it yourself.  Do you not?

But why do that?  If you update your master branch on your fork, this pull request will be updated, too, automatically.

**Comment by giovannistagliano** [comment]
My master branch is updated, so it should be all right, isn't? However I was very undecided whether to update the package. There are no important changes.

**Comment by DanGrayson** [comment]
You can click on the first part of "Use the command line to resolve conflicts before continuing" to get some hints about how to do it.

Is your master branch up to date with our master branch or with your fork's master branch?

**Comment by giovannistagliano** [comment]
I'm unable to resolve the conflicts.. sorry

**Comment by DanGrayson** [comment]
Is it because the conflicts are complicated?  If so, one thing I like to do is to enable 3-way
diffs during conflict flagging.  That way one sees what the least common ancestor was, too.

**Comment by giovannistagliano** [comment]
Probably, It's because I don't understand anything! Now I deleted my fork of M2 and then made a new one.

**Comment by DanGrayson** [comment]
Prepare for future conflicts with http://psung.blogspot.com/2011/02/reducing-merge-headaches-git-meets.html

**Pull request closed without merging**
