### PR TITLE
Bugfixes and minor improvements in Polyhedra

### PR DESCRIPTION
**Pull request by lkastner**
This pull request contains the changes to Polyhedra.m2 from the Leipzig workshop. Thanks to @martapanizzut and @AndrewPStaal for code contributions and a lot of other work.

This pull request was a little delayed, since Polyhedra.m2 now needs Topcom.m2, but at the same time, Topcom.m2 started needing Polyhedra.m2. This has been resolved by calling `fourierMotzkin` in Topcom.m2 instead of using `convexHull` from Polyhedra.m2, since internally this is a call to `fourierMotzkin` anyway.

Furthermore, Polyhedra.m2 provides a method `regularSubdivision` now. Since NormalToricVarieties.m2 relies on Polyhedra.m2 and has  `regularSubdivision` as well, the declaration of `regularSubdivision` was moved to Polyhedra.m2. Is that ok, @ggsmith ?

Short list of changes:
- `cellDecompose` is now called `regularSubdivision`, since it computes the regular subdivision induced by a weight vector.
- `volume` now calls Topcom to compute a triangulation.
- Introduce `simplex` constructing the convex hull of the standard vectors and the origin, given the dimension.
- All deprecated methods are collected in a file. They give a warning indicating that they will be removed in version 1.11 of Polyhedra.m2.
- Deprecated methods are not used internally anymore.
- Fix some deprecated calls to Polyhedra.m2 in ToricVectorBundles.m2.
- Improve documentation.
- Introduce `regularTriangulation` giving a regular triangulation via Topcom.m2.
- Add StanleyReisner functionality.
- Bump version of Polyhedra.m2 to 1.10.

@mikestillman : We also added a method `topcomIsTriangulation` to Topcom.m2 that checks whether a subdivision of points is a triangulation using Topcom. You can remove it, if you do not like it.

### CODE REVIEW

**Comment by DanGrayson** [comment]
"regularSubdivision" is not exported by NormalToricVarieties, so moving the definition is not a good idea, as it entangles the two packages.  Why not just change
```
regularSubdivision = method(TypicalValue => NormalToricVariety)
```
to
```
regularSubdivision := method(TypicalValue => NormalToricVariety)
```

**Comment by ggsmith** [comment]
Dear Dan,

Since the “regularSubdivision” is not exported by NormalToricVarieties, I am happy to make it a local definition or simply rename it.  There is already a version in the Leipzig repository which does the latter.

I plan to submit a pull request for “NormalToricVarieties” in the relatively near future that will fix this minor issue and add some other useful functionality.

Cheers,
Greg.

**Comment by DanGrayson** [comment]
Renaming it would be good.

**Comment by DanGrayson** [comment]
@ggsmith --  make sure you work from the latest version of your packages on the master branch, to get the changes here.

**Pull request merged**
