### PR TITLE
Add package RunExternalM2

### PR DESCRIPTION
**Pull request by bapike**
Hi,
I've written a package that lets you run an M2 function in a child M2 process (either a fork or a new M2 process) and retrieve the result.  The goal was to allow the use of ulimits for calculations where failure is acceptable.  One benefit is a good method of benchmarking from within M2.

This has only been tested on Debian 7.8 with both M2 1.7, and the current git head.  Hopefully, portability issues are minor.  On other platforms, a few examples or tests may break because:
1) they assume a format for "ulimit"
2) they use KeepStatistics=>true, and then the default value of KeepStatisticsCommand assumes a fixed path (/usr/bin/time) to GNU Time or similar, and assumes a syntax for calling GNU Time.

I don't really see a way of fixing these issues, which should leave the package functional.

Thanks!

### CODE REVIEW

**Comment by DanGrayson** [comment]
I ran "check" and one of the tests failed:

```
-- -*- M2-comint -*- {* hash: 191131092 *}

i1 : --/Users/dan/src/M2/M2-Macaulay2/M2/Macaulay2/packages/RunExternalM2.m2:1211: location of test code
     
     fn=temporaryFileName()|".m2";

i2 : fn<<///
     spin = (x,t) -> (
       startTime:=cpuTime();
     	while(cpuTime()-startTime<t) do ();
     	return(x);
     );
     ///<<endl<<close;

i3 : 
     r=runExternalM2(fn,"spin",(5,4),PreRunScript=>"ulimit -t 2");
Running (ulimit -t 2 && (/Users/dan/src/M2/M2-Macaulay2/M2/BUILD/dan/builds.tmp/mac64-master.production/usr-dist/x86_64-Darwin-MacOS-10.10.3/bin/M2-binary  --stop --no-debug --silent  <"/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-31659-0/1.m2" >"/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-31659-0/1.out" 2>&1 ))
sh: line 1: 31662 Cputime limit exceeded: 24  ( /Users/dan/src/M2/M2-Macaulay2/M2/BUILD/dan/builds.tmp/mac64-master.production/usr-dist/x86_64-Darwin-MacOS-10.10.3/bin/M2-binary --stop --no-debug --silent < "/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-31659-0/1.m2" > "/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-31659-0/1.out" 2>&1 )
Finished running.
RunExternalM2: expected answer file does not exist

i4 : assert(not(r#"exit code"===0));

i5 : assert(r#value===null);

i6 : 
     r=runExternalM2(fn,"spin",(5,2),KeepStatistics=>true);
Running (echo -n && (/usr/bin/time --verbose -o "/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-31659-0/2.stat" /Users/dan/src/M2/M2-Macaulay2/M2/BUILD/dan/builds.tmp/mac64-master.production/usr-dist/x86_64-Darwin-MacOS-10.10.3/bin/M2-binary  --stop --no-debug --silent  <"/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-31659-0/2.m2" >"/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-31659-0/2.out" 2>&1 ))
-n
Finished running.
RunExternalM2: expected answer file does not exist
runExternalM2: error recovering statistics

i7 : assert(r#"exit code"===0);
stdio:17:1:(3): error: assertion failed
```

Also notice that the sh builtin "echo" will blithely echo "-n".

**Comment by bapike** [comment]
The options I'm using for /usr/bin/time are supported by GNU Time but not [the time utility in OS X](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/time.1.html#//apple_ref/doc/man/1/time).  I'll implement a POSIX fallback, but it would be nice to detect the OS X version of time so I can use the -l parameter.  I don't have access to an OS X system; is there an easy way to get a version string from /usr/bin/time?

**Comment by DanGrayson** [comment]
```
TIME(1)                   BSD General Commands Manual                  TIME(1)

NAME
     time -- time command execution

SYNOPSIS
     time [-lp] utility

DESCRIPTION
     The time utility executes and times utility.  After the utility finishes, time writes the total time elapsed, the time consumed by system overhead, and the
     time used to execute utility to the standard error stream.  Times are reported in seconds.

     Available options:

     -l      The contents of the rusage structure are printed.

     -p      The output is formatted as specified by IEEE Std 1003.2-1992 (``POSIX.2'').

     Some shells may provide a builtin time command which is similar or identical to this utility.  Consult the builtin(1) manual page.

DIAGNOSTICS
     The time utility shall exit with one of the following values:

     1-125   An error occurred in the time utility.

     126     The utility was found but could not be invoked.

     127     The utility could not be found.

     Otherwise, the exit status of time shall be that of utility.

SEE ALSO
     builtin(1), csh(1), getrusage(2)

FILES
     /usr/include/sys/resource.h

STANDARDS
     The time utility conforms to IEEE Std 1003.2-1992 (``POSIX.2'').

BUGS
     The granularity of seconds on microprocessors is crude and can result in times being reported for CPU usage which are too large by a second.

BSD                              June 6, 1993                              BSD

```

**Comment by DanGrayson** [comment]
You could detect Mac OS this way:

```
$ /usr/bin/sw_vers -productName
Mac OS X
```

**Comment by bapike** [comment]
I think it should work now on OS X.

If you wouldn't mind, please check that in the documentation node for "runExternalM2", in the example after "We can get quite a lot of detail...", that it is calling /usr/bin/time with a -l parameter.

**Comment by DanGrayson** [comment]
One of the examples fails:
```
-- -*- M2-comint -*- {* hash: 1790207602 *}

i1 : fn=temporaryFileName()|".m2"

o1 = /var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/0.m2

i2 : fn<</// square = (x) -> (stderr<<"Running"<<endl; sleep(1); x^2); ///<<endl;

i3 : fn<</// justexit = () -> ( exit(27); ); ///<<endl;

i4 : fn<</// spin = (x) -> (stderr<<"Spinning!!"<<endl; startTime:=cpuTime(); while(cpuTime()-startTime<x) do (); return(x);); ///<<endl;

i5 : fn<<flush;

i6 : h=runExternalM2(fn,"square",(4));
Running (true && (/Users/dan/src/M2/M2-Macaulay2/M2/BUILD/dan/builds.tmp/mac64-master.production/usr-dist/x86_64-Darwin-MacOS-10.10.3/bin/M2-binary  --stop --no-debug --silent  <"/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/1.m2" >"/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/1.out" 2>&1 ))
Finished running.

i7 : h

o7 = HashTable{answer file => null}
               exit code => 0
               output file => null
               return code => 0
               statistics => null
               time used => 1
               value => 16

o7 : HashTable

i8 : h#value===4^2

o8 = true

i9 : h#"exit code"===0

o9 = true

i10 : h=runExternalM2(fn,"justexit",());
Running (true && (/Users/dan/src/M2/M2-Macaulay2/M2/BUILD/dan/builds.tmp/mac64-master.production/usr-dist/x86_64-Darwin-MacOS-10.10.3/bin/M2-binary  --stop --no-debug --silent  <"/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/2.m2" >"/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/2.out" 2>&1 ))
Finished running.
RunExternalM2: expected answer file does not exist

i11 : h

o11 = HashTable{answer file => /var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/2.ans}
                exit code => 27
                output file => /var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/2.out
                return code => 6912
                statistics => null
                time used => 1
                value => null

o11 : HashTable

i12 : fileExists(h#"output file")

o12 = true

i13 : fileExists(h#"answer file")

o13 = false

i14 : h=runExternalM2(fn,"spin",3,PreRunScript=>"ulimit -t 2");
Running (ulimit -t 2 && (/Users/dan/src/M2/M2-Macaulay2/M2/BUILD/dan/builds.tmp/mac64-master.production/usr-dist/x86_64-Darwin-MacOS-10.10.3/bin/M2-binary  --stop --no-debug --silent  <"/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/3.m2" >"/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/3.out" 2>&1 ))
sh: line 1: 32480 Cputime limit exceeded: 24  ( /Users/dan/src/M2/M2-Macaulay2/M2/BUILD/dan/builds.tmp/mac64-master.production/usr-dist/x86_64-Darwin-MacOS-10.10.3/bin/M2-binary --stop --no-debug --silent < "/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/3.m2" > "/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/3.out" 2>&1 )
Finished running.
RunExternalM2: expected answer file does not exist

i15 : h

o15 = HashTable{answer file => /var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/3.ans}
                exit code => 152
                output file => /var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/3.out
                return code => 38912
                statistics => null
                time used => 5
                value => null

o15 : HashTable

i16 : fileExists(h#"output file")

o16 = true

i17 : if fileExists(h#"output file") then get(h#"output file")

o17 = 
      i1 : -- Script /var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/3.m2 automatically generated by RunExternalM2
           needsPackage("RunExternalM2",Configuration=>{"isChild"=>true});
      --loading configuration for package "RunExternalM2" from file /Users/dan/Library/Application Support/Macaulay2/init-RunExternalM2.m2

      i2 : load "/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/0.m2";

      i3 : runExternalM2ReturnAnswer("/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-32471-0/3.ans",spin (3));
      Spinning!!


i18 : fileExists(h#"answer file")

o18 = false

i19 : h=runExternalM2(fn,"spin",3,KeepStatistics=>true);
stdio:19:3:(3): error: close: process exited with code 1
```

The problem is this:
```
get("!/usr/bin/time --version 2>&1")
```

**Comment by bapike** [comment]
I hope this fixes it.

**Pull request merged**
