### PR TITLE
Replace array<T> with std::vector<T, gc_allocator<T> >

### PR DESCRIPTION
**Pull request by mahrud**
- [x] Remove array.hpp and replace `array<T>` with `std::vector<T, gc_allocator<T> >`

### CODE REVIEW

**Comment by mikestillman** [comment]
Hi Dan, actually, these code changes are all from me.  I can accept the request, once the tests pass, or if you want to look over my changes, please do so!

**Comment by mikestillman** [comment]
I just built this branch using cmake, macos, debug mode, and I am getting some things that appear to be actual bugs.  @DanGrayson before either you or I accept this pull request, I want to fix these or at least look into them.  These issues do not arise on the release build, but that is perhaps not surprising.

**Comment by mahrud** [comment]
Looks like two tests in EngineTests also failed: 81 and 83 (on debug build type, 66-68 also fail, but those are due to #1206). The two that failed in the builds above have the same resolution strategy and backtraces are identical:
```m2
83: i9 : 
83:        elapsedTime  res(ideal(I_*), Strategy=>0)
83: -- SIGSEGV
83: -* stack trace, pid: 105834
83:  0# basic_stacktrace at /home/mahrud/.linuxbrew/include/boost/stacktrace/stacktrace.hpp:126
83:  1# segv_handler at /home/mahrud/Projects/M2/engine/M2/BUILD/clang/../../Macaulay2/bin/main.cpp:240
83:  2# 0x00007F0D0875FA70 in /lib64/libc.so.6
83:  3# res2_comp::insert_pair(res2_pair*) at /home/mahrud/Projects/M2/engine/M2/BUILD/clang/../../Macaulay2/e/res-a0.cpp:670
83:  4# res2_comp::initialize(Matrix const*, int, bool, int, int) at /home/mahrud/Projects/M2/engine/M2/BUILD/clang/../../Macaulay2/e/res-a0.cpp:482
83:  5# res2_comp at /home/mahrud/Projects/M2/engine/M2/BUILD/clang/../../Macaulay2/e/res-a0.cpp:569
83:  6# ResolutionComputation::choose_res(Matrix const*, char, int, char, int, int, int) at /home/mahrud/Projects/M2/engine/M2/BUILD/clang/../../Macaulay2/e/comp-res.cpp:97
83:  7# IM2_res_make at /home/mahrud/Projects/M2/engine/M2/BUILD/clang/../../Macaulay2/e/x-gb.cpp:484
83:  8# interface_rawResolution at /home/mahrud/Projects/M2/engine/M2/Macaulay2/d/interface.dd:3506
83:  9# evaluate_evalraw at /home/mahrud/Projects/M2/engine/M2/Macaulay2/d/evaluate.d:1293
83: 10# evaluate_eval at /home/mahrud/Projects/M2/engine/M2/Macaulay2/d/evaluate.d:1253
```

```m2
85: i14 :   C2 = res(ideal gens gb I, Strategy=>0)
85: 
85:  -- removing res 0 at 0x7f15f16f1ca0
85: 
85:  -- removing polynomial ring 0 at 0x7f15f4a3f380
85: 
85:    -- registering gb 2 at 0x7f15f153d6e0
85: 
85:    -- [gb]{3}(3)mmm{4}(1)m{5}(2)mm{6}(5)oomoo{7}(3)ooo{9}(1)m{10}(2)oo{11}(1)m
85:    -- {12}(2)oonumber of (nonminimal) gb elements = 9
85:    -- number of monomials                = 18
85:    -- #reduction steps = 13
85:    -- #spairs done = 20
85:    -- ncalls = 11
85:    -- nloop = 24
85:    -- nsaved = 1
85:    -- 
85:    -- registering gb 3 at 0x7f15f48664a0
85: 
85:    -- [gb]{3}(3)mmm{4}(2)mo{5}(4)mmoo{6}(6)oomooo{7}(3)ooo{9}(2)mo{10}(2)oo{11}(2)mo
85:    -- {12}(2)oonumber of (nonminimal) gb elements = 9
85:    -- number of monomials                = 18
85:    -- #reduction steps = 19
85:    -- #spairs done = 26
85:    -- ncalls = 11
85:    -- nloop = 24
85:    -- nsaved = 1
85:    -- resolution Strategy=>0
85:    -- -- SIGSEGV
85: -* stack trace, pid: 106083
^[[A^[[B85:  0# basic_stacktrace at /home/mahrud/.linuxbrew/include/boost/stacktrace/stacktrace.hpp:126
85:  1# segv_handler at /home/mahrud/Projects/M2/engine/M2/BUILD/clang/../../Macaulay2/bin/main.cpp:240
85:  2# 0x00007F15F8B9DA70 in /lib64/libc.so.6
85:  3# res2_comp::insert_pair(res2_pair*) at /home/mahrud/Projects/M2/engine/M2/BUILD/clang/../../Macaulay2/e/res-a0.cpp:670
85:  4# res2_comp::initialize(Matrix const*, int, bool, int, int) at /home/mahrud/Projects/M2/engine/M2/BUILD/clang/../../Macaulay2/e/res-a0.cpp:482
85:  5# res2_comp at /home/mahrud/Projects/M2/engine/M2/BUILD/clang/../../Macaulay2/e/res-a0.cpp:569
85:  6# ResolutionComputation::choose_res(Matrix const*, char, int, char, int, int, int) at /home/mahrud/Projects/M2/engine/M2/BUILD/clang/../../Macaulay2/e/comp-res.cpp:97
85:  7# IM2_res_make at /home/mahrud/Projects/M2/engine/M2/BUILD/clang/../../Macaulay2/e/x-gb.cpp:484
85:  8# interface_rawResolution at /home/mahrud/Projects/M2/engine/M2/Macaulay2/d/interface.dd:3506
85:  9# evaluate_evalraw at /home/mahrud/Projects/M2/engine/M2/Macaulay2/d/evaluate.d:1293
85: 10# evaluate_eval at /home/mahrud/Projects/M2/engine/M2/Macaulay2/d/evaluate.d:1253
```

**Comment by DanGrayson** [comment]
> Hi Dan, actually, these code changes are all from me. I can accept the request, once the tests pass, or if you want to look over my changes, please do so!

I did look at the changes, and they seem okay.  So once all the tests pass, feel free to pull.

**Comment by mahrud** [comment]
The problem was that with unsigned iterators like `size_t`, the loop condition `i >= 0` in:
```cpp
for (auto i = base_components.size() - 1; i >= 0; i--) { ... }
```
is always true, so the iterator jumps to the maximum number. The easy fix would be using:
```cpp
for (auto i = base_components.size() - 1; i != -1; i--) { ... }
```
where `(size_t) -1` is converted to the maximum number and the condition actually works. The better fix though is to use vector iterators:
```cpp
for (auto p = base_components.rbegin(); p != base_components.rend(); ++p) { ... }
```
which also make the code ever so slightly cleaner.

**Comment by mahrud** [comment]
@DanGrayson shall I merge this?

**Pull request merged**
