### PR TITLE
Updated PushForward.m2 with Claudiu's changes.  Note that the order o…

### PR DESCRIPTION
**Pull request by kschwede**
pushFwd(module, f)  has been switched to  (f, module), to match the previous pushForward function.

Updated Pullback.m2 to work with the revised order.

Updated Schubert.m2 to work with the revised pushFwd.

### CODE REVIEW

**Comment by kschwede** [comment]
Dan, this has the changes we discussed.  I certainly don't mind if this pushFwd is changed to overwrite the old one.

**Comment by mikestillman** [comment]
I'm going to merge this, then test it after that.

**Comment by mikestillman** [comment]
Karl,

Does this pull request change the m2 pushFwd?  Or do we need to do that separately?

-- mike

**Comment by kschwede** [comment]
It does not change the m2 pushForward.  We need to do that separately.

**Pull request merged**
