### PR TITLE
Add capitals

### PR DESCRIPTION
**Pull request by fchapoton**
to some names of people inside packages/

### CODE REVIEW

**Comment by fchapoton** [comment]
why is there no codespell linter check ?

**Comment by DanGrayson** [comment]
> why is there no codespell linter check ?

That's strange, there should be.  I'll restart all the jobs.

**Comment by DanGrayson** [comment]
> > why is there no codespell linter check ?
> 
> That's strange, there should be. I'll restart all the jobs.

No, it only offers to rerun the jobs that were already run.

**Comment by DanGrayson** [comment]
> why is there no codespell linter check ?

Is your code based on an old branch, before that lint test was added?

**Comment by fchapoton** [comment]
no, my code is based on the most recent development branch

but I made a mistake and first asked for "master" as the target branch, before changing it ; maybe that's the reason

**Comment by DanGrayson** [comment]
> no, my code is based on the most recent development branch
> 
> but I made a mistake and first asked for "master" as the target branch, before changing it ; maybe that's the reason

That's probably not the reason -- a pull request could change the workflow, and that should be tested.

I've restarted all the jobs, anyway.  We'll see.

**Comment by d-torrance** [comment]
It only runs on pushes or pull requests to `development`, so I think that's indeed the reason:

https://github.com/Macaulay2/M2/blob/048c777dc703365e44c3865b2c1faed698b82b3a/.github/workflows/lint.yml#L2-L4

**Comment by DanGrayson** [comment]
Thanks again for all the work on improving such things!

**Pull request merged**
