### PR TITLE
added M2_setenv which starts a subshell with Macaulay2 environment

### PR DESCRIPTION
**Pull request by jakobkroeker**

### CODE REVIEW

**Comment by DanGrayson** [comment]
What's the purpose of this change?

**Comment by jakobkroeker** [comment]
this would also be a workaround for 
https://github.com/Macaulay2/M2/issues/234

**Comment by DanGrayson** [comment]
See my comment on a better way at #247

**Comment by DanGrayson** [comment]
In what sense is this a workaround for #234 ?

**Comment by DanGrayson** [comment]
Discussion seems to have died down.  Closing, but feel free to reopen to revive the discussion.

**Pull request closed without merging**
