### PR TITLE
New package BinomialEdgeIdeals

### PR DESCRIPTION
**Pull request by windisch**
Hi, this package provides methods for computations with (parity) binomial edge ideals and their permanental versions over arbitrary fields.

### CODE REVIEW

**Comment by DanGrayson** [comment]
I tried installing it with "installPackage", and the examples don't run, because Graphs isn't loaded.  That should be fixed, either by loading Graphs in the example code, or by moving Graphs to the PackageExports option.  Then I'll take another look.

**Comment by windisch** [comment]
Thanks. This should be fixed now.

**Comment by DanGrayson** [comment]
I just noticed that you export the variable "s".  That shouldn't be done, because the single letter variables belong to the user as variables for rings.

**Comment by windisch** [comment]
Thanks. This is fixed in #280.

**Pull request merged**
