### PR TITLE
initial commit for package SlackIdeals (A. Macchia and A. Wiebe)

### PR DESCRIPTION
**Pull request by antostain**

### CODE REVIEW

**Comment by DanGrayson** [comment]
Thanks.  I've also added it to the distribution list.

**Comment by DanGrayson** [comment]
I notice there are many possibly useful tests in the file, but they are after the "end" statement, so they aren't used.  If they work, how about activating them?

**Comment by antostain** [comment]
Dear Prof. Grayson,

thank you for your message. Yes, the tests should work, we probably forgot to activate them.

Do you want me to make the change and resubmit the package?

Best,

Antonio

 

 

Da: Daniel R. Grayson <notifications@github.com> 
Inviato: 26 March 2020 01:28
A: Macaulay2/M2 <M2@noreply.github.com>
Cc: antostain <macchia.antonello@outlook.com>; Author <author@noreply.github.com>
Oggetto: Re: [Macaulay2/M2] initial commit for package SlackIdeals (A. Macchia and A. Wiebe) (#1083)

 

I notice there are many possibly useful tests in the file, but they are after the "end" statement, so they aren't used. If they work, how about activating them?

**Comment by DanGrayson** [comment]
Resubmit, no: Your package is now on our master branch, so pull it to your copy of the repository, make the necessary changes, commit them, push them up to your clone on github, and submit a new pull request.

**Pull request merged**
