### PR TITLE
Refactoring Core with other small changes

### LINKED ISSUE #1472: trim the path
The directory `/Applications/Macaulay2-1.16/share/Macaulay2/Core/` should be removed from the path after loading all of the files in it.

```m2
Macaulay2, version 1.16
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems,
               LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra, TangentCone,
               Truncations

i1 : stack path

o1 = ./
     /Users/dan/Library/Application Support/Macaulay2/code/
     /Users/dan/Library/Application Support/Macaulay2/local/share/Macaulay2/
     /Applications/Macaulay2-1.16/share/Macaulay2/Core/
     /Applications/Macaulay2-1.16/share/Macaulay2/
```

### PR DESCRIPTION
**Pull request by mahrud**
- [x] renames `setup.m2 -> Core.m2`
  - [x] simplifies some aspects of `startup.m2` and `Core.m2`, hence fixes #1472
  - [x] cleans up `Core.m2`, move or simplify some routines
  - [x] fix running M2 with `--no-core` (used to be `--no-setup`)
  - [x] added dependencies between Core sources
- [x] adds `check(List, Package)`, `options(ZZ)`, `locate(List)` and `locate(ZZ)`, and `setRandomSeed(Sequence)`
 - [x] changed `new OptionTable from List` to just ignore null entries, so matches `HashTable`
- [x] adds internal function `getViewer` and improves `show` and `edit`
- [x] simplifies the dependency graph in Core by moving pieces of code

Each commit has an isolated purpose and leaves the repository in a stable state, so you can review this PR commit by commit.

### CODE REVIEW

**Comment by DanGrayson** [comment]
124 files changed, but "small changes" ???

**Comment by mikestillman** [comment]
@DanGrayson I have to look, but I think it is likely a set of simple changes, they just affect many files (by adding 'needs' in).  This is teased out of the previous pull request that got closed, I believe, without including the other changes to caching, etc.

**Comment by mahrud** [comment]
Of the 15 commits, 13 of them are small changes. One refractors Core.m2, and one adds "needs" lines to all core scripts.

**Review by mikestillman — APPROVED** [review]
@DanGrayson I think that this pull request is ready to merge.  I have gone through all the files.  Most are small changes, some reorganization of code, some renaming (e.g. setup.m2 to Core.m2), many 'needs' statements added in.

**Pull request merged**
