### PR TITLE
Build with gcc-6.1

### PR DESCRIPTION
**Pull request by doughdemon**

### CODE REVIEW

**Comment by DanGrayson** [comment]
Why?  We already get the warning message, and I've disabled it in commit 2fa55d212f36dc9b909b4dd67493b59d9cfd3472

**Comment by DanGrayson** [comment]
... and we already put `--Wall` on the command line.

**Comment by DanGrayson** [comment]
Thanks for the effort to improve our software, but this particular change isn't really a change, so I'm closing.  Feel free to suggest other changes as they occur to you, or to reopen this one if you have something further.

**Comment by doughdemon** [comment]
Sorry, I didn't see that it was already fixed. Thanks for pointing me the commit.

**Pull request closed without merging**
