### PR TITLE
Revert "fix error location in tail call" to fix the debugger

### PR DESCRIPTION
**Pull request by mahrud**
Reverts Macaulay2/M2#3144 in order to fix https://github.com/Macaulay2/M2/issues/3417 (debugger not finding the correct location of errors in Core).

### CODE REVIEW

**Comment by mahrud** [comment]
@pzinn I'll try to find an alternative fix for this issue before the next release, but I believe fixing the debugger is more important than the error location. If you can think of another fix let me know.

**Comment by d-torrance** [comment]
This is what I'm getting after building this branch:

```m2
i1 : debug Core; errorDepth = 1; blah 12
stdio:1:32:(3): error: debug me
```

I put `blah` on line 2 of "debugging.m2" just like the example in #3417.   It's not giving us the `olderror processArgs args` output any more, but is `stdio` the expected output?

**Comment by mahrud** [comment]
I noticed this too, but try turning `blah` into a method. It would be good to fix that as well.

**Comment by d-torrance** [comment]
Ah, ok!  As a method, this works great:

```m2
i4 : blah 12
/home/profzoom/src/macaulay2/M2/M2/Macaulay2/m2/debugging.m2:7:21:(1):[1]: error: debug me
/home/profzoom/src/macaulay2/M2/M2/Macaulay2/m2/debugging.m2:7:21:(1):[1]: --entering debugger (type help to see debugger commands)
/home/profzoom/src/macaulay2/M2/M2/Macaulay2/m2/debugging.m2:7:16-7:32: --source
code:
blah ZZ := x -> error "debug me"
```

**Review by d-torrance — APPROVED** [review]

**Comment by pzinn** [comment]
OK. I didn't have time to look into #3417 myself.

**Pull request merged**
