### PR TITLE
A major update to SpecialFanoFourfolds

### PR DESCRIPTION
**Pull request by giovannistagliano**

### CODE REVIEW

**Comment by giovannistagliano** [comment]
I should do some other minor updates. Is there still time for the version 1.18?

**Comment by DanGrayson** [comment]
> I should do some other minor updates. Is there still time for the version 1.18?

Yes, this will make it in.

**Comment by DanGrayson** [comment]
A test failed: https://github.com/Macaulay2/M2/pull/2092/checks?check_run_id=2651544292#step:13:2255

**Comment by DanGrayson** [comment]
Hmm, could you comment out this test, which consumes too much memory?

https://github.com/Macaulay2/M2/pull/2092/checks?check_run_id=2658077348#step:12:3508

**Comment by giovannistagliano** [comment]
> Hmm, could you comment out this test, which consumes too much memory?
> 
> https://github.com/Macaulay2/M2/pull/2092/checks?check_run_id=2658077348#step:12:3508

Which line can I comment on? Test 5 shouldn't be difficult. These are the times I get:

`i1 : loadPackage "SpecialFanoFourfolds"

o1 = SpecialFanoFourfolds

o1 : Package

i2 : check SpecialFanoFourfolds
 -- capturing check(0, "SpecialFanoFourfolds")                               -- 20.5087 seconds elapsed
 -- capturing check(1, "SpecialFanoFourfolds")                               -- 22.6896 seconds elapsed
 -- capturing check(2, "SpecialFanoFourfolds")                               -- 38.891 seconds elapsed
 -- capturing check(3, "SpecialFanoFourfolds")                               -- 28.8674 seconds elapsed
 -- capturing check(4, "SpecialFanoFourfolds")                               -- 13.4538 seconds elapsed
 -- capturing check(5, "SpecialFanoFourfolds")                               -- 16.5698 seconds elapsed
 -- capturing check(6, "SpecialFanoFourfolds")                               -- 20.9965 seconds elapsed
 -- capturing check(7, "SpecialFanoFourfolds")                               -- 1.69774 seconds elapsed

`

**Pull request merged**
