### PR TITLE
Add a test to make sure a faulty version of minimalBetti is not being used

### PR DESCRIPTION
**Pull request by mikestillman**

### CODE REVIEW

**Comment by mikestillman** [comment]
@DanGrayson, @mahrud I forgot to change the branch this should be merged into, grrr....  Sorry about that.

**Comment by mahrud** [comment]
You can always click to edit the title and change the target branch: image

**Comment by mikestillman** [comment]
I didn't edit the branch as I want to see the results of the tests, but maybe I should just change it.

**Comment by mikestillman** [comment]
I was going to make it for the release-1.22-branch branch too.

**Comment by mahrud** [comment]
The tests keep running regardless.

**Comment by mikestillman** [comment]
I'm not sure I understand what the error was, and if it is related to this?  (Or rather, it doesn't seem related!)

**Comment by mikestillman** [comment]
This is messed up.  I will add the test separately.  Closing for now...

**Pull request closed without merging**
