### PR TITLE
Test of merging ReesAlgebra with commit history

### PR DESCRIPTION
**Pull request by b-stone**
Here is a pull request that attempts to preserve commit history from a workshop repo. I believe this worked and was more work than it should be. 

**This request should not be accepted unless an author of `ReesAlgebra` checks it out. There were merge conflicts that I addressed in order to show the process.** 

Here is the process I used.

1. Clone the workshop repo.
2. remove `remote origin` so things don't go wrong.
3. Filter the branch, moving the contents of the subdirectory to the top level and deleting everything else; all the time preserving history.
4. Create a new repo, clone and move over to it. In the new repo create a `remote` that points to the local workshop filtered repo.
5. Fetch, merge, and push; fixing conflicts if necessary. 

I created the following repo following these steps:

https://github.com/b-stone/Sample-ReesAlgebra-M2

The actual commands I used are as follows:

```
git clone https://github.com/Macaulay2/Workshop-2017-Berkeley.git
cd Workshop-2017-Berkeley
git remote remove origin   # Just a precaution so you don't push changes
git filter-branch --subdirectory-filter ReesAlgebras -- --all  
cd ../Sample-ReesAlgebra-M2/
git remote add WorkShop ~/GitHub/M2-WorkShop-Tests/Workshop-2017-Berkeley
git fetch WorkShop
git merge WorkShop/master # Handle conflicts and commit.
git push origin master
```

Now at this point we have all the commit history as well as all the files in `ReesAlgebras`. In order to merge this into the `M2` repo we have more work. 

6. Create a branch that you will merge into the M2 repo.
7. On this branch, create the following directories, `M2/Macaulay2/packages/`.
8. Then move the files you want to merge into the `M2/Macaulay2/packages/`.
9. Delete all other top level files, including `README.md`
10. Fork the `M2` repo (or update your fork).
11. Merge locally, push to the fork, and submit a pull request.

Once again I did this for my repo:

https://github.com/b-stone/Sample-ReesAlgebra-M2

The actual commands I used are as follows:

```
git checkout -b Rees-M2-Merge
mkdir -p M2/Macaulay2/packages/
git rm -rf AssociatedGradedRingExample.m2 Associated\ Graded\ Ring\ Example LiskeStuff.m2 SegreEmbedding.m2 SpecialFiberRingExample.m2 Zhangchi/ ilir/ mahrud/ README.md 
git commit -am 'message'
git push --set-upstream origin Rees-M2-Merge
cd ../Forked-Repos/M2/ # Make sure you are updated and on the branch you want.
git remote add SampleReesAlg ~/GitHub/M2-WorkShop-Tests/Sample-ReesAlgebra-M2/
git fetch SampleReesAlg
git merge SampleReesAlg/Rees-M2-Merge
git commit -am 'message'
git push
```

At this point I created a pull request into the `M2` repo.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Please delete .DS_Store

**Comment by DanGrayson** [comment]
The history is not clean, since it involves many commits that have nothing to do with your file.  For example, the second one.

**Comment by b-stone** [comment]
So I removed the .DS_Store, but I am not sure how to filter out the noisy commits. The commits we are seeing here are all of the ones that effected the subdirectory `ReesAlgebras` in the Berkeley workshop. While I was able to filter all of the other workshop participants, Team ReesAlgebra is still there. 

At the moment I don not know how to fix this problem. Probably some sort of `cherry-pick` would do it, but I would need to read up on it.

**Comment by DanGrayson** [comment]
I looked into this once and decided there was no good way to do it, because the filtering command applies to directories.

In future, we should be careful to develop packages in a clone of the repository they come from, or in a branch of a repository that contains just that file.  One can envision the groups at a workshop all using different branches of the same repository.  We could even have one big repository for all the workshops, which would reduce the clutter as workshops proliferate.

**Comment by DanGrayson** [comment]
Why not just submit instead a 1-commit pull request based on the M2 repository and include a link to the other repository in the commit message?

**Comment by b-stone** [comment]
That is probably the most elegant solution. It probably be better if one of
the authors of the packages did it. I was just playing with the commit
history so you can close this request if you want.

—
Assistant Professor of Mathematics & Computer Science
Adelphi University
Garden City, NY 11530-0701

http://math.adelphi.edu/~bstone/
(785) 813-1206
—

On Mon, Jul 31, 2017 at 3:24 PM, Daniel R. Grayson <notifications@github.com

**Pull request closed without merging**
