### PR TITLE
partially fix debug build

### PR DESCRIPTION
**Pull request by bapike**
These changes allow a debug build to compile, and fix the 19 errors in Macaulay2Doc examples that were reported in #354.  It successfully runs all examples in packages before MinimalPrimes (it has an issue there).

One of the 19 errors was "sqrt 2p3000000", as mentioned in #35, although the originally reported bug still does not work.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Thanks, I'll test it!

**Comment by bapike** [comment]
For a debug build, `make` now works, and I'm testing `make check`.

There are two legitimate bugs here.  Commit 60210bc fixes a problem where, e.g., `concatenate(-2^20,2^20)` will try to overwrite a megabyte of memory with spaces.  Commit 052dda4 makes `substitute(1/101,ZZ/101)` give an error.  I've added tests for these.

The rest of the changes are pretty straightforward.  I got a little carried away and tried to fix a few undistributed packages.

**Comment by bapike** [comment]
`make check` now works in a debug build without optimization, though I had to allow more time for some tests.

**Comment by DanGrayson** [comment]
Thanks!

**Pull request merged**
