### PR TITLE
Feature: markdown(Hypertext)

### PR DESCRIPTION
**Pull request by mahrud**
This PR ensures the Core satisfies the following:
- [x] all types that inherit from `Hypertext` or `MarkUpType` are in `hypertext.m2` (previously `html0.m2`)
- [x] `net` and `info` methods for such objects are moved in `format.m2` (previously `hypertext.m2`)
- [x] `html` methods for such objects are moved in `html.m2` (previously `hypertext.m2`)
- [x] `tex` methods for such objects are moved in `latex.m2` (previously `hypertext.m2`)
- [x] a new `markdown` method for such objects is added in `markdown.m2`
- [x] the previous content of `html.m2` is temporarily in `installPackage.m2`

To try out the markdown generation, try something like this:
```
debug Core
markdown help sum
```

### CODE REVIEW

**Comment by mahrud** [comment]
@DanGrayson here is the broken down markdown PR. As you can see, quite a few other files are changed, but all of those are minor changes (e.g. removing `DIV1`, or other small things.) I made sure to do `git mv` commits so file logs are preserved.

@pzinn I know you've made some changes to the files moved by this PR. Hope it doesn't give you any conflicts.

**Comment by pzinn** [comment]
ha! I am preparing my PR as we speak. and yes, this will be a major headache for me...

**Comment by pzinn** [comment]
I think I'll proceed and submit my PR since I was just about finished. We can then discuss what to do.

**Comment by mahrud** [comment]
@pzinn what does your PR do? I'm happy to help with rebasing or merging the changes.

**Comment by mahrud** [comment]
6d847d6 is a cherry-pick from @pzinn's PR #1267 plus some work to fix the conflicts. This PR should have both changes now.

**Comment by mahrud** [comment]
@DanGrayson I presume the "waiting for update" tag was added because of the merge conflicts, so I rebased on top of development. There are more things to do, but since you wanted smaller pull requests, I think this PR is ready for review.

Changes to be made in a future PR:
- export and document `style` (@pzinn)
- export and document `markdown`
- break up `installPackage` into smaller functions (e.g. separate functions for info and html generation)
- add markdown as an option to `installPackage`
- add tests for all `net`, `info`, `tex`, `markdown`, `html`, etc.

**Comment by DanGrayson** [comment]
Will do, but slowly, as I have papers to referee and a conference this week to attend ...

**Pull request merged**
