### PR TITLE
Fix "Verbose" option to "check" after recent capture changes

### PR DESCRIPTION
**Pull request by d-torrance**
Previously, we computed the filename of the temporary file containing
the output of failing tests based on the number of the test itself in
relation to the total number of tests being run.  However, now that
"capture" is used for testing, this will no longer work, as temporary
files are not always created, and the temporary filename counter will
not be incremented in a predictable manner.

Instead, we store the location of the temporary file immediately after
the test is run.  In particular, the local variable "errorList" now
contains tuples of the form "(test number, temporary file number)".

### CODE REVIEW

**Comment by d-torrance** [comment]
I just noticed that this may have already been solved in #1716...

**Comment by d-torrance** [comment]
> I just noticed that this may have already been solved in #1716...

No, #1716 appears to be buggy.  After running `check` on the following package:

```m2
newPackage "Foo"

beginDocumentation()

TEST "assert(1 + 1 == 2)"
TEST "assert(2 + 2 == 5)"
TEST "assert(3 + 3 == 6)"
TEST "assert(4 + 4 == 9)"
```

I get the following:

```m2
i2 : check("Foo", Verbose => true)
 -- capturing check(0, "Foo")                                                -- 0.000513312 seconds elapsed
 -- capturing check(1, "Foo")                                               currentString:2:1:(3):[14]: error: assertion failed
 -- capture failed; retrying ...
 -- running check(1, "Foo")                                                 
 ulimit -c unlimited; ulimit -t 700; ulimit -m 850000; ulimit -s 8192; ulimit -n 512;  cd /tmp/M2-3389424-0/1-rundir/; GC_MAXIMUM_HEAP_SIZE=400M "/usr/bin/M2-binary" --int --no-randomize --no-readline --silent --stop --print-width 77 --srcdir "/home/profzoom/src/macaulay2/M2/M2/" -e 'needsPackage("Foo",Reload=>true,FileName=>"/home/profzoom/tmp/Foo.m2")' <"/tmp/M2-3389424-0/0.m2" >>"/tmp/M2-3389424-0/0.tmp" 2>&1
/tmp/M2-3389424-0/0.tmp:0:1: (output file) error: Macaulay2 exited with status code 1
/tmp/M2-3389424-0/0.m2:0:1: (input file)
M2: *** Error 1
 -- 0.535378 seconds elapsed
 -- capturing check(2, "Foo")                                                -- 0.000150841 seconds elapsed
 -- capturing check(3, "Foo")                                               currentString:2:1:(3):[14]: error: assertion failed
 -- capture failed; retrying ...
 -- running check(3, "Foo")                                                 
 ulimit -c unlimited; ulimit -t 700; ulimit -m 850000; ulimit -s 8192; ulimit -n 512;  cd /tmp/M2-3389424-0/3-rundir/; GC_MAXIMUM_HEAP_SIZE=400M "/usr/bin/M2-binary" --int --no-randomize --no-readline --silent --stop --print-width 77 --srcdir "/home/profzoom/src/macaulay2/M2/M2/" -e 'needsPackage("Foo",Reload=>true,FileName=>"/home/profzoom/tmp/Foo.m2")' <"/tmp/M2-3389424-0/2.m2" >>"/tmp/M2-3389424-0/2.tmp" 2>&1
/tmp/M2-3389424-0/2.tmp:0:1: (output file) error: Macaulay2 exited with status code 1
/tmp/M2-3389424-0/2.m2:0:1: (input file)
M2: *** Error 1
 -- 0.542386 seconds elapsed
tmp/Foo.m2:6:1: error:
tail: cannot open '/tmp/M2-3389424-0/-2.tmp' for reading: No such file or directory
stdio:2:1:(3): error: close: process exited with code 256
```

I'll fix up and rebase this PR on top of that one.

**Comment by mahrud** [comment]
Just tell me the patch and I'll apply it there, or you can push to that branch.

**Comment by d-torrance** [comment]
> Just tell me the patch and I'll apply it there, or you can push to that branch.

I'll just push to that branch -- that sounds easiest.

**Pull request closed without merging**
