### PR TITLE
Upgrade to FLINT 2.7.0 and Factory 4.2.0

### LINKED ISSUE #1808: Upgrade to FLINT 2.7.0
Currently Macaulay2 needs FLINT 2.6.x and won't run with FLINT 2.7.x and
Homebrew install instructions suggest `brew remove flint` as a first step.

Supporting FLINT 2.7.x would help compatibility with other math software.

Indeed, some users might have installed FLINT and other math software
depending on it such as Arb and GAP via brew, and have built SageMath
using those brew installed dependencies.

### PR DESCRIPTION
**Pull request by mahrud**
- [x] Fixes #1808 for CMake
- [x] update factory build for autotools.

@DanGrayson: this only updates the CMake build. The builds won't fail, because flint is installed from either brew or apt currently, but could you fix the autotools build and add a commit to this PR?

### CODE REVIEW

**Comment by DanGrayson** [comment]
> @DanGrayson: this only updates the CMake build. The builds won't fail, because flint is installed from either brew or apt currently, but could you fix the autotools build and add a commit to this PR?

Sure, I've converted it to a draft and assigned myself.

**Comment by DanGrayson** [comment]
Did you cancel the builds?

**Comment by mahrud** [comment]
No

**Comment by mikestillman** [comment]
@DanGrayson as you have been handling these, I'll let you push the button once you are ready.

**Comment by DanGrayson** [comment]
> Is there a reason why this isn't merged yet?

Yes, two reasons: commits keep getting added, and you haven't said to me that it's ready.

**Comment by mahrud** [comment]
> Yes, two reasons: commits keep getting added, and you haven't said to me that it's ready.

I add commits to my own branches whenever I see fit. You can merge them whenever the PR accomplishes the tasks listed in the first post and the tests pass. You can also wait indefinitely and never merge them. Up to you.

**Comment by DanGrayson** [comment]
No, I prefer to wait until things are static and I know, from the author, that the pull request is finally ready.

**Pull request merged**
