### PR TITLE
update M2-emacs submodule commit

### PR DESCRIPTION
**Pull request by mahrud**

### CODE REVIEW

**Comment by DanGrayson** [comment]
There's some conflict.

**Comment by mahrud** [comment]
I'll just close this. You can update the submodule hash directly.

**Comment by d-torrance** [comment]
It looks like M2-emacs already got updated to a relatively new commit  in #1758 (https://github.com/Macaulay2/M2/commit/5a1f8172b909406f696b34202e01c1faafd64d8b).  It could probably stand to get bumped up to https://github.com/Macaulay2/M2-emacs/commit/cddcd39f90dac8920ea8c6d95a9ddecb16d56464 for Mahrud's `README` changes, but I don't think it should go all the way up to the tip of the `master` branch since the `infoHelp` stuff is a new feature (and the corresponding Macaulay2 code is only in `development`).

**Comment by mahrud** [comment]
Who knows what's the point of master or development anymore. It should probably be changed to master.

**Comment by DanGrayson** [comment]
Still, the `infoHelp` feature is sort of cool, so if it works, why not include it?  The changes are simple enough.

**Comment by d-torrance** [comment]
> Still, the `infoHelp` feature is sort of cool, so if it works, why not include it? The changes are simple enough.

Ok, sounds good to me. :)

**Comment by DanGrayson** [comment]
> > Still, the `infoHelp` feature is sort of cool, so if it works, why not include it? The changes are simple enough.
> 
> Ok, sounds good to me. :)

Will you submit a pull request?

**Pull request closed without merging**
