### PR TITLE
Merged MultipolynomialResultants and ChowForms into Resultants

### PR DESCRIPTION
**Pull request by giovannistagliano**

### CODE REVIEW

**Comment by giovannistagliano** [comment]
Hi, I have a question: In the code (line 93), I assumed that if A = K[x_0,...,x_n]/I is a zero-dimensional algebra over a field K, then the command basis(A) always returns a monomial basis for the module A^1. Is this correct? Thanks.

**Comment by DanGrayson** [comment]
I assume so.  @mikestillman ?

**Comment by DanGrayson** [comment]
Hmm, are we still waiting for an answer here from @mikestillman ?

**Comment by giovannistagliano** [comment]
Hi, it was just to be 100% sure. I did several tests with the package and I would say it works well.

**Pull request merged**
