### PR TITLE
added OptionalComponentsPresent to PHCpack; fixed one example

### PR DESCRIPTION
**Pull request by antonleykin**
This resolves 
https://github.com/Macaulay2/M2/issues/1295
and fixes one bug in `cascade`.

@janverschelde may want to take a look at this.

### CODE REVIEW

**Comment by DanGrayson** [comment]
I just tested it and it works great.  There should probably be some tests involving running the program, though.

Also, as long as you're looking at this, could you add this option?:
```
  phc -0 : random numbers with fixed seed for repeatable runs    
```
That way, if we run the examples, the output files don't change and git doesn't notify us that something it knows about has changed.

**Comment by antonleykin** [comment]
Should we just make 
```
  Configuration => { 
    "path" => "",
    "PHCexe"=>"phc -0", 
    "keep files" => true
  },
```
so that `phc` is deterministic by default?

... or do you have some other solution in mind?

**Comment by DanGrayson** [comment]
That would work for us, I believe.

Why not delete the "keep files" option, since it's unused?

**Comment by antonleykin** [comment]
I've derandomized PHCpack (by default) and derandomized the use of Bertini in certain functions of NumericalAG.
@JoseMath, perhaps it is a good idea to make `RandomSeed=>0` default in `Bertini` package itself.

**Comment by DanGrayson** [comment]
> I've derandomized PHCpack (by default) and derandomized the use of Bertini in certain functions of NumericalAG.
> @JoseMath, perhaps it is a good idea to make `RandomSeed=>0` default in `Bertini` package itself.

That would be a good idea.  (When running tests and examples, M2 is careful to use `setRandomSeed 0`, but that wouldn't affect external programs such as `bertini`, which might have their own idea about randomization.)

**Pull request merged**
