### PR TITLE
Skip check(26, "MultiplierIdeals") -- uses too much memory

### PR DESCRIPTION
**Pull request by d-torrance**
Closes: #2923

### CODE REVIEW

**Comment by mahrud** [comment]
It seems to me like that issue indicates a regression that should be fixed, not just erased. Are we going backwards?

**Comment by d-torrance** [comment]
> It seems to me like that issue indicates a regression that should be fixed, not just erased. Are we going backwards?

Even before we were running out of memory in Debian's continuous integration tests, this test was arguably too slow for the test suite.  On my system right now:

```m2
1 : check(26, "MultiplierIdeals")
 -- capturing check(26, "MultiplierIdeals")                                  -- 18.2088 seconds elapsed
```

I think the underlying issue is likely something to do with factory, since the big thing that changed before the Debian tests started failing was an upload of the latest singular package.

**Comment by mahrud** [comment]
Consider this: without this test failing, would we have found out that the new factory version may cause a regression? Smaller tests wouldn't have failed, so I'd argue that 18 seconds isn't too much, but exactly the right size for a test because it's on the edge and can detect regressions.

**Comment by d-torrance** [comment]
Fair enough. I'll close this.

**Pull request closed without merging**
