### PR TITLE
TorAlgebra replaces CodepthThree

### PR DESCRIPTION
**Pull request by larswinther**
Deletes package CodepthThree, adds package TorAlgebra, updates =distributed-packages

### CODE REVIEW

**Comment by DanGrayson** [comment]
I moved your new file back into the packages directory where it belongs in commit 5175acfc8380e903d27d80e13fad457250035c96

**Comment by larswinther** [comment]
Thank you Dan.

Best,
Lars
---------------------------------------------------------------------
Lars Winther Christensen         E-mail:   lars.w.christensen@ttu.edu<mailto:lars.w.christensen@ttu.edu>
Department of Math. and Stat.    Phone:             (+1 806) 834 6323
Texas Tech University            Fax:               (+1 806) 742 1112
Lubbock, TX 79409-1042           Homepage: www.math.ttu.edu/~lchriste<http://www.math.ttu.edu/~lchriste>

**Comment by DanGrayson** [comment]
Oops, I just noticed that under the old name, CodepthThree, this package was certified as having been published in the journal, JSAG, and now that certification is gone.

There are two issues here:  How do we make it possible for readers of the journal to find the renamed package?  Shouldn't we put the certification back into the renamed package?

**Comment by larswinther** [comment]
Hi Dan,

The certification should definitely go back. We have just extended the algorithm to also cover rings of higher codepth, so the old name seemed silly. Is it possible to put a CodepthThree entry in the documentation with a message that the package has been superseded by TorAlgebra?

Best,
Oana and Lars
---------------------------------------------------------------------
Lars Winther Christensen         E-mail:   lars.w.christensen@ttu.edu<mailto:lars.w.christensen@ttu.edu>
Department of Math. and Stat.    Phone:             (+1 806) 834 6323
Texas Tech University            Fax:               (+1 806) 742 1112
Lubbock, TX 79409-1042           Homepage: www.math.ttu.edu/~lchriste<http://www.math.ttu.edu/~lchriste>

**Comment by DanGrayson** [comment]
It's hard to put a CodepthThree documentation entry in the right place in the documentation without actually having a package with that name, and we wouldn't want a fake package like that.  The "changes" documentation will mention it.

**Comment by larswinther** [comment]
Hi Dan,

I see the problem. Is there a way to have the same package have two names?

Anyway, if this is not a problem that has come up before and there is not good way to handle it, maybe we should just put the package on our homepages for now and then write a new article one day and do the official update.

Best,
Lars
---------------------------------------------------------------------
Lars Winther Christensen         E-mail:   lars.w.christensen@ttu.edu<mailto:lars.w.christensen@ttu.edu>
Department of Math. and Stat.    Phone:             (+1 806) 834 6323
Texas Tech University            Fax:               (+1 806) 742 1112
Lubbock, TX 79409-1042           Homepage: www.math.ttu.edu/~lchriste<http://www.math.ttu.edu/~lchriste>

**Comment by DanGrayson** [comment]
No, we'll keep it, thank you for the submission!  Meanwhile, I fixed the problem as commented on here: https://github.com/Macaulay2/M2/issues/734#issuecomment-366710709 .

The file CodepthThree.m2 now contains this:
```
-- The package CodepthThree has been renamed to TorAlgebra

error "The package CodepthThree has been renamed to TorAlgebra."
```

**Comment by larswinther** [comment]
Thank you Dan.

Best,
Lars
---------------------------------------------------------------------
Lars Winther Christensen         E-mail:   lars.w.christensen@ttu.edu<mailto:lars.w.christensen@ttu.edu>
Department of Math. and Stat.    Phone:             (+1 806) 834 6323
Texas Tech University            Fax:               (+1 806) 742 1112
Lubbock, TX 79409-1042           Homepage: www.math.ttu.edu/~lchriste<http://www.math.ttu.edu/~lchriste>

**Pull request merged**
