### PR TITLE
DiffAlg.m2

### PR DESCRIPTION
**Pull request by DiffAlg**
This is to submit the package DiffAlg to be included in the Macaulay2 website.

### CODE REVIEW

**Comment by DanGrayson** [comment]
We already have it included, as you can see by clicking on "Files changed".

By the way, who are you?  It would be good, when submitting future updates to the package, to use an account name that is close your name, and to include a picture in your profile so we can get to know you.

**Comment by DiffAlg** [comment]
Hi Dan,

ok, yes. Now I see that it is already included.

Sorry then.

I'm Ariel Molinuevo.

Ok. I'll change my account name.

Regards.

Ariel

**Comment by DanGrayson** [comment]
Thanks, and welcome!

**Comment by garyfurnish** [comment]
To whom it may concern,
Please take Gary Furnish off the mailing list for all participants as he
passed away from his Leukemia.

Thanks ,
Patti Furnish

**Comment by DanGrayson** [comment]
Dear Ms. Furnish,

We don't control the mailing list directory directly, but I have sent a message to the website managers at github.com, requesting them to arrange that his account be unsubscribed to updates from all repositories, including ours and any others he may have subscribed to.

Mike ( @mikestillman ) and I were greatly saddened by his death, for he made a valuable contribution to our project and was the best programmer we've ever managed to hire, always with a firm and clear idea of what had to be done to achieve the next goal.

**Comment by DanGrayson** [comment]
PS: If you wish to contact them yourself, the contact page is here: https://github.com/contact

**Pull request closed without merging**
