### PR TITLE
Fixing ring maps from WeylAlgebra to AssociativeAlgebra

### PR DESCRIPTION
**Pull request by mahrud**
@mikestillman this is the change suggested in https://github.com/Macaulay2/M2/issues/2907#issuecomment-1741490215 by @mdebellevue. Could you have a look at why it's not working?

I emailed you two weeks ago that we need to have #2907 fixed before the upcoming workshop. If that's not possible, we need to know so we can change plans.

### CODE REVIEW

**Comment by mikestillman** [comment]
@mahrud Sorry, I'm confused.  This example works on my machine (with your changes).  I thought you needed me to fix a bug?  If not, let's just accept this pull request (I guess we should make sure it passes all tests, they are running now).

**Comment by mikestillman** [comment]
Ah, I see, you were able to fix it after asking me about it.  That's good!

**Comment by mahrud** [comment]
This is failing a couple of assertions in AssociativeAlgebras. One of them is fixable (probably the test was wrong or ambiguous) but this one seems like a problem:
```m2
  needsPackage "AssociativeAlgebras"
  R = QQ<|b,c,d|>
  F2 = map(R,R,{c+b,c,d})
  F2(b*c) -- gives c*(b+c), should be (b+c)*c
  F2(c*b) -- gives (b+c)*c, should be c*(b+c)
```

**Comment by mdebellevue** [comment]
Sorry, this is probably just due to my inexperience with git and/or totally loosing the thread on what's going on with this issue, but just to check that I have the situation straight: the fix I originally wrote added an explicit check for WeylAlgebras to ringmap.cpp, and your fix instead adds an IsCommutative and IsQuotient to the free algebra class.  Looking at this with my eyes now, I'm not sure why either of these changes would have fixed the issue?  Unless I'm missing something. in the original ringmap.cpp is_commutative_ring() should be returning false for both WeylAlgebras and FreeAlgebra (or quotients theoreof), and the call to cast_to_SchurRing() shouldn't be affecting anything.  So in either of our fixes, the code used to evaluate a ring map is still the chunk from 171 of ringmap.cpp:
```
      for (index_varpower i = vp; i.valid(); ++i)
        {
          int v = first_var + i.var();
          int e = i.exponent();
          ring_elem g;
          if (e >= 0)
            g = _elem[v].bigelem;
          else
            g = R->invert(_elem[v].bigelem);
          for (int j = 0; j < e; j++)
            {
              assert(v < nvars);
              ring_elem tmp = R->mult(g, result);
              R->remove(result);
              result = tmp;
            }
        }

**Comment by moorewf** [comment]
I think I have fixed this in a new PR -- the idea for the fix was correct, but the is_commutative_ring() was placed in the wrong spot (it should be in M2FreeAlgebra and M2FreeAlgebraQuotient since those are the front-end interfaces to the FreeAlgebra and FreeAlgebraQuotient back-end classes).

**Comment by mahrud** [comment]
Closing this in favor of yours.

**Comment by mahrud** [comment]
> Unless I'm missing something. in the original ringmap.cpp is_commutative_ring() should be returning false for both WeylAlgebras and FreeAlgebra

You're right about everything except the last part: is_commutative_ring for FreeAlgebra was actually true! Now (either with this PR or with Frank's) it is false, so the same block handles it.

**Pull request closed without merging**
