### PR TITLE
Add texMath(ForeignObject)

### PR DESCRIPTION
**Pull request by d-torrance**
Improves display of foreign objects in web app:

image

### CODE REVIEW

**Comment by d-torrance** [comment]
> Wouldn't that give an error if I was using a ForeignObject that doesn't have an equivalent value in M2?

Sure, but that shouldn't happen.  `value` is installed for all of the various `ForeignObject` types.  This is also how `(net, ForeignObject)` is implemented.

**Comment by pzinn** [comment]
nice. I didn't realize ForeignFunctions worked on the cloud, thought there was some compilation problems.
Incidentally:
Screenshot from 2023-03-04 14-19-06

**Comment by d-torrance** [comment]
> nice. I didn't realize ForeignFunctions worked on the cloud, thought there was some compilation problems. 

Yup!  I think this was fixed in #2636.

> Incidentally:

Already taken care of in #2731.  :)  The new `AfterPrint` interface is so much nicer!

**Comment by d-torrance** [comment]
@pzinn - I just added a couple commits with the small `AfterPrint` changes you suggested.

**Pull request merged**
