### PR TITLE
Updated FrobeniusThresholds and TestIdeals packages.

### PR DESCRIPTION
**Pull request by kschwede**
This includes small updates to the TestIdeals package (including a renaming of the option IsLocal -> AtOrigin).  

This also includes large updates and improvements to the FrobeniusThresholds package, previously called the FThresholds package.

### CODE REVIEW

**Comment by eisenbud** [comment]
Dear Karl,

seeing this post reminds me to ask you: where is the "heights of minors" code that you mentioned to me? I'd like to try it out. I suppose one could use a similar strategy for things like colon ideals, too...

It was fun to see you at Notre Dame -- I hope the rest of the workshop went well!

Cordially,

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Comment by eisenbud** [comment]
Dear Karl,

seeing this post reminds me to ask you: where is the "heights of minors" code that you mentioned to me? I'd like to try it out. I suppose one could use a similar strategy for things like colon ideals, too...

It was fun to see you at Notre Dame -- I hope the rest of the workshop went well!

Cordially,

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de <http://www.msri.org/~de>

**Comment by DanGrayson** [comment]
Could you also change the name of the package in the file `=distributed-packages` ?

**Comment by kschwede** [comment]
Done.  Sorry about that.

**Comment by DanGrayson** [comment]
Thanks!

**Pull request merged**
