### PR TITLE
Updates to XOR

### PR DESCRIPTION
**Pull request by d-torrance**
While trying to convert Python binary operators into Macaulay2 binary operators and vice versa for #2130, I noticed that our XOR doesn't line up nicely with the others.

## Logical XOR

This addresses #1800.  In particular `xor` is now a keyword and `(symbol xor, Boolean, Boolean)` is a method:

```m2
i1 : 1 + 1 == 2 xor 2 + 2 == 4

o1 = false

i2 : 1 + 1 == 2 xor 2 + 2 == 5

o2 = true
```

## Bitwise XOR

The old `xor` method for bitwise XOR (which was only used twice) has been updated to use `^^` instead (since `^` is obviously taken!):

```m2
i3 : (1 + 2 + 8) ^^ (1 + 4 + 8)

o3 = 6
```
This is more consistent with the current use of  the keywords `&` and `|` for bitwise AND and OR, and it appears that this may have been considered at some point already considering `^^`'s precedence order, right where bitwise XOR would go:

https://github.com/Macaulay2/M2/blob/b5b9b18ccb0dbf4daeeefc69290f6f18331134ef/M2/Macaulay2/d/binding.d#L272-L277

### CODE REVIEW

**Comment by d-torrance** [comment]
I should probably add some tests... I'll do that later.

**Comment by d-torrance** [comment]
> I should probably add some tests... I'll do that later.

Done

**Comment by mahrud** [comment]
> > I should probably add some tests... I'll do that later.
> 
> Done

Might that be too many basic tests? Also see 
https://github.com/Macaulay2/M2/blob/b5b9b18ccb0dbf4daeeefc69290f6f18331134ef/M2/Macaulay2/m2/basictests/A01.m2#L67-L72
https://github.com/Macaulay2/M2/blob/b5b9b18ccb0dbf4daeeefc69290f6f18331134ef/M2/Macaulay2/m2/basictests/A01.m2#L143-L147

**Comment by d-torrance** [comment]
> Might that be too many basic tests?

I figured I might as well cover all the bases -- it doesn't take very long:

```m2
i14 : (tests "Core")#21

o14 = 
      usr-dist/common/share/doc/Macaulay2/Core/tests/boolean.m2:0:1-64:1:

o14 : TestInput

i15 : check_21 "Core"
 -- capturing check(21, "Core")                                              -- 0.050261 seconds elapsed
```

I did notice the existing tests, but I don't think the new XOR methods would be available yet when they're run, and I figured I might as well throw in AND and OR for good measure.

**Comment by mahrud** [comment]
I'm not concerned about the time. It's redundant in that if most of the things you test are broken, I highly doubt the computation will even reach that step. That's why `runBasicTests` is defined in the interpreter, not in top level.

**Comment by d-torrance** [comment]
> I'm not concerned about the time. It's redundant in that if most of the things you test are broken, I highly doubt the computation will even reach that step. That's why `runBasicTests` is defined in the interpreter, not in top level.

Fair enough -- I'll remove the AND/OR-only tests.

**Comment by d-torrance** [comment]
Oops:

```m2
 -- running   check(335, "Core")                                             -- 0.313255 seconds elapsed
/home/runner/work/M2/M2/M2/BUILD/build/usr-dist/common/share/doc/Macaulay2/Core/tests/names.m2:0:1-1119:1: error:
 -- i1105 : assert( (toString weightRange) === "weightRange" )
 -- 
 -- i1106 : assert( (toString width) === "width" )
 -- 
 -- i1107 : assert( (toString wrap) === "wrap" )
 -- 
 -- i1108 : assert( (toString x) === "x" )
 -- 
 -- i1109 : assert( (toString xor) === "xor" )
 -- stdio:1110:22:(3): error: syntax error at ')'
 -- /home/runner/work/M2/M2/M2/Macaulay2/m2/startup.m2.in:671:16:(0): --backtrace: parse error--
 -- 
stdio:1:1:(3): error: test(s) #184 of package Core failed.
```

I'll fix this shortly.

**Pull request merged**
