### PR TITLE
Fix git issues #1856, #638

### PR DESCRIPTION
**Pull request by mikestillman**
This is the first of several pull requests (I hope) for fixing bugs in the engine.  This one fixes the two bugs mentioned.  I might still need to add a test file for #638, but I have added one for #1856.

0^0 should consistently be 1.  0^n, for n>0 should consistently be 0 (this was a bug in some GF rings).

Elements in Weyl algebras were always coming out inhomogeneous.  Now, if the x and dx variables have degrees which are negative of each other, homogeneous elements should be recognized as such (fixed with @antonleykin )

### CODE REVIEW

**Comment by DanGrayson** [comment]
That's a thorough test file!

**Comment by mikestillman** [comment]
@DanGrayson Looks like I screwed something up (in ffpack exponentiation, in characteristic 2).  I'll fix it, add in the other test, and we can see how it goes.

**Comment by DanGrayson** [comment]
@mikestillman -- is there a reason for the test "ARingZZpFFPACK.arithmetic2" to have failed here?

**Comment by DanGrayson** [comment]
OOps, just saw your message above, so maybe you're on it already.

**Comment by mikestillman** [comment]
@DanGrayson You might want to look at this, but it is ready to be merged, once you agree.

**Pull request merged**
