### PR TITLE
Graphs 0.3.3, GraphicalModels 2.0, StatGraphs 0.1

### PR DESCRIPTION
**Pull request by olgakuznetsova**
….0 GraphicalModelsMLE version 0.3

### CODE REVIEW

**Comment by DanGrayson** [comment]
One problem with the test runs is that the name of the new package, `StatGraphs`, has not been added to the file `M2/Macaulay2/packages/=distributed-packages`.  The run fails when the html checker checks the documentation and finds broken links, due to the documentation for StatGraphs not being installed.

**Comment by olgakuznetsova** [comment]
Thank you!

**Comment by olgakuznetsova** [comment]
@DanGrayson, our package depends on another package (EigenSolver by Justin Chen, Anton Leykin and others), which has not been submitted yet but we have been in touch with the authors and they have committed to submit it with this release.
We have set that package as a default because NAG4M2 does not work in the majority of cases covered by our package. 

What is a good way for us to proceed?

**Comment by DanGrayson** [comment]
> @DanGrayson, our package depends on another package (EigenSolver by Justin Chen, Anton Leykin and others), which has not been submitted yet but we have been in touch with the authors and they have committed to submit it with this release.
> We have set that package as a default because NAG4M2 does not work in the majority of cases covered by our package.
> 
> What is a good way for us to proceed?

If you're package won't work without the other one, then we just have to wait for the other one to be submitted.

**Comment by olgakuznetsova** [comment]
I see, thank you!

Olga

**Comment by olgakuznetsova** [comment]
@DanGrayson, there seems to be a new type of package metadata, "Keywords". Is there a standard list of keywords that one should choose or can we choose our own? Can there be multiple keywords? What is the recommended syntaxes? 
Ours will most likely be "Algebraic Statistics". Is that ok?

**Comment by DanGrayson** [comment]
That sounds fine to me.  Here's what the other packages have currently:
```m2
AbstractToricVarieties.m2:16:	Keywords => {"Toric Geometry", "Intersection Theory"},
AdjointIdeal.m2:10:	Keywords => {"Commutative Algebra"},
AlgebraicSplines.m2:23:	Keywords => {"Applied Algebraic Geometry"},
AnalyzeSheafOnP1.m2:9:	     Keywords => {"Commutative Algebra"},
BGG.m2:14:	Keywords => {"Commutative Algebra"},
BIBasis.m2:16:    Keywords => {"Groebner Basis Algorithms"},
BeginningMacaulay2.m2:8:     Keywords => {"Miscellaneous"},
Benchmark.m2:9:     Keywords => {"Miscellaneous"},
Bertini.m2:22:  Keywords => {"Numerical Algebraic Geometry", "Interfaces"},
BinomialEdgeIdeals.m2:9:   Keywords => {"Edge Ideals"},
Binomials.m2:33:	Keywords => {"Commutative Algebra"},
BoijSoederberg.m2:14:	Keywords => {"Commutative Algebra"},
Book3264Examples.m2:14:     Keywords => {"Intersection Theory"},
BooleanGB.m2:10:    Keywords => {"Groebner Basis Algorithms"},
Browse.m2:10:     Keywords => {"Miscellaneous"},
Bruns.m2:22:     Keywords => {"Commutative Algebra"},
ChainComplexExtras.m2:13:     Keywords => {"Homological Algebra"},
ChainComplexOperations.m2:8:	       Keywords => {"Homological Algebra"},
CharacteristicClasses.m2:13:	Keywords => {"Intersection Theory"},
Chordal.m2:15:    Keywords => {"Commutative Algebra", "Graph Theory"},
Classic.m2:9:     Keywords => {"Miscellaneous"},
CohomCalg.m2:11:	Keywords => {"Toric Geometry", "Interfaces"},
CoincidentRootLoci.m2:11:	Keywords => {"Real Algebraic Geometry", "Interfaces"},
CompleteIntersectionResolutions.m2:9:	      Keywords => {"Commutative Algebra"},
Complexes.m2:10:        Keywords => {"Homological Algebra"},
ConformalBlocks.m2:10:    Keywords => {"Commutative Algebra"},
ConvexInterface.m2:10:        Keywords => {"Interfaces"},
ConwayPolynomials.m2:10:	Keywords => {"Group Theory"},
CorrespondenceScrolls.m2:25:	Keywords => {"Commutative Algebra"},
Cremona.m2:8:	Keywords => {"Commutative Algebra"},
Cyclotomic.m2:31:	Keywords => {"Algebraic Number Theory"},
DGAlgebras.m2:10:     Keywords => {"Commutative Algebra"},
DecomposableSparseSystems.m2:20:    Keywords => {"Numerical Algebraic Geometry"},
Depth.m2:28:     Keywords => {"Commutative Algebra"},
DeterminantalRepresentations.m2:12:	Keywords => {"Representation Theory", "Commutative Algebra"},
DiffAlg.m2:26:	Keywords => {"Commutative Algebra"},
Divisor.m2:10:     Keywords => {"Commutative Algebra"},
Dmodules.m2:12:     Keywords => {"D-modules"},
EagonResolution.m2:12:	Keywords => {"CommutativeAlgebra"},
EdgeIdeals.m2:48:	Keywords => {"Edge Ideals"},
Elimination.m2:6:     Keywords => {"Commutative Algebra"},
EliminationMatrices.m2:16:   Keywords => {"Commutative Algebra"},
EllipticCurves.m2:10:	Keywords => {"Algebraic Number Theory"},
EllipticIntegrals.m2:10:	Keywords => {"Algebraic Number Theory"},
EngineTests.m2:15:	Keywords => {"Miscellaneous"},
EnumerationCurves.m2:10:	Keywords => {"Commutative Algebra"},
EquivariantGB.m2:12:     Keywords => {"Groebner Basis Algorithms"},
ExampleSystems.m2:19:	Keywords => {"Examples and Random Objects"},
ExteriorIdeals.m2:9:	Keywords => {"Commutative Algebra"},
FGLM.m2:9:    Keywords => {"Groebner Basis Algorithms"},
FastLinAlg.m2:18:Keywords => {"Linear Algebra"},
FiniteFittingIdeals.m2:18:    Keywords => {"Commutative Algebra"},
FirstPackage.m2:9:    Keywords => {"Miscellaneous"},
FormalGroupLaws.m2:13:	Keywords => {"Group Theory"},
FourTiTwo.m2:27:	Keywords => {"Interfaces"},
FourierMotzkin.m2:26:	Keywords => {"Convex Geometry"},
FrobeniusThresholds.m2:31:Keywords => {"Commutative Algebra"},
GKMVarieties.m2:26:	--Keywords => {"Equivariant Cohomology", "Toric Geometry", "Flag Varieties", "Matroids"},
GenericInitialIdeal.m2:12:     Keywords => {"Commutative Algebra"},
GradedLieAlgebras.m2:16:	Keywords => {"Lie Groups and Lie Algebras"},
GraphicalModels.m2:25:     Keywords => {"Statistics", "Graph Theory"},
Graphics.m2:13:	Keywords => {"Miscellaneous"},
Graphs.m2:40:	Keywords => {"Graph Theory"},
GroebnerWalk.m2:8:	     Keywords => {"Groebner Basis Algorithms"},
HigherCIOperators.m2:9:	Keywords => {"Commutative Algebra"},
HighestWeights.m2:27:     Keywords => {"Lie Groups and Lie Algebras", "Homological Algebra"},
HodgeIntegrals.m2:25:   Keywords => {"Commutative Algebra"},
HyperplaneArrangements.m2:47:     Keywords => {"Commutative Algebra"},
IntegralClosure.m2:11:    Keywords => {"Commutative Algebra"},
InvariantRing.m2:32:	Keywords => {"Representation Theory", "Group Theory"},
InverseSystems.m2:12:	Keywords => {"Commutative Algebra"},
InvolutiveBases.m2:16:	Keywords => {"Groebner Basis Algorithms"},
K3Carpets.m2:21:	Keywords => {"Commutative Algebra"},
Kronecker.m2:8:     Keywords => {"Commutative Algebra"},
KustinMiller.m2:15:	Keywords => {"Commutative Algebra"},
LLLBases.m2:7:     Keywords => {"Algebraic Number Theory", "Linear Algebra"},
LatticePolytopes.m2:24:    Keywords => {"Convex Geometry"},
LexIdeals.m2:12:	Keywords => {"Commutative Algebra"},
Licenses.m2:7:     Keywords => {"Miscellaneous"},
LieTypes.m2:11:    Keywords => {"Lie Groups and Lie Algebras"},
LocalRings.m2:32:    Keywords => {"Commutative Algebra"},
M0nbar.m2:12:     Keywords => {"Commutative Algebra"},
MCMApproximations.m2:9:Keywords => {"Commutative Algebra"},
Macaulay2Doc.m2:14:     Keywords => {"Miscellaneous"},
MapleInterface.m2:10:	Keywords => {"Interfaces"},
Markov.m2:8:     Keywords => {"Statistics"},
Matroids.m2:10:	Keywords => {"Matroids"},
MinimalPrimes.m2:17:	Keywords => {"Commutative Algebra"},
Miura.m2:12:        Keywords => {"Commutative Algebra"},
MixedMultiplicity.m2:30:	Keywords => {"Commutative Algebra"},
ModuleDeformations.m2:13:     Keywords => {"Deformation Theory"},
MonodromySolver.m2:16:	Keywords => {"Numerical Algebraic Geometry"},
MonomialAlgebras.m2:11:	Keywords => {"Commutative Algebra"},
MultiGradedRationalMap.m2:7:    Keywords => {"Commutative Algebra"},
MultiplierIdeals.m2:44:  Keywords => {"D-modules"},
MultiplierIdealsDim2.m2:11:	Keywords => {"D-modules"},
NAGtypes.m2:13:     Keywords => {"Numerical Algebraic Geometry"},
NCAlgebra.m2:15:     Keywords => {"Noncommutative Algebra", "Interfaces"},
Nauty.m2:17:    Keywords => {"Graph Theory", "Interfaces"},
NautyGraphs.m2:23:    Keywords => {"Graph Theory", "Interfaces"},
NoetherNormalization.m2:15:     Keywords => {"Commutative Algebra"},
NonminimalComplexes.m2:20:	Keywords => {"Homological Algebra", "Commutative Algebra"},
NormalToricVarieties.m2:28:    Keywords => {"Toric Geometry"},
Normaliz.m2:21:           Keywords => {"Interfaces"},
NumericSolutions.m2:27: Keywords => {"Numerical Algebraic Geometry"},
NumericalAlgebraicGeometry.m2:15:     Keywords => {"Numerical Algebraic Geometry"},
NumericalCertification.m2:10:	Keywords => {"Numerical Algebraic Geometry"},
NumericalHilbert.m2:10:     Keywords => {"Numerical Algebraic Geometry"},
NumericalImplicitization.m2:13:    Keywords => {"Numerical Algebraic Geometry"},
NumericalSchubertCalculus.m2:20:    Keywords => {"Numerical Algebraic Geometry"},
OldPolyhedra.m2:28:    Keywords => {"Convex Geometry"},
OldToricVectorBundles.m2:21:    Keywords => {"Toric Geometry"},
OpenMath.m2:27:	Keywords => {"Miscellaneous"},
PHCpack.m2:36:  Keywords => {"Numerical Algebraic Geometry", "Interfaces"},
PackageCitations.m2:40:    Keywords => {"Miscellaneous"},
PackageTemplate.m2:11:	Keywords => {"Miscellaneous"},
Parametrization.m2:10:	Keywords => {"Commutative Algebra"},
Parsing.m2:9:     Keywords => {"Miscellaneous"},
PencilsOfQuadrics.m2:30:	     Keywords => {"Commutative Algebra"},
Permanents.m2:11:	Keywords => {"Commutative Algebra"},
PhylogeneticTrees.m2:18:     Keywords => {"Applied Algebraic Geometry"},
PieriMaps.m2:34:	  Keywords => {"Representation Theory"},
Points.m2:15:	Keywords => {"Examples and Random Objects"},
Polyhedra.m2:27:    Keywords => {"Convex Geometry"},
Polymake.m2:9:	Keywords => {"Interfaces"},
Posets.m2:22:	Keywords => {"Combinatorics"},
PositivityToricBundles.m2:15:           Keywords => {"Toric Geometry"},
PrimaryDecomposition.m2:8:     Keywords => {"Commutative Algebra"},
PruneComplex.m2:22:    Keywords => {"Commutative Algebra", "Homological Algebra"},
Pullback.m2:7:Keywords => {"Commutative Algebra"},
PushForward.m2:9:	Keywords => {"Commutative Algebra"},
QthPower.m2:10:    Keywords => {"Commutative Algebra"},
Quasidegrees.m2:9:	Keywords => {"Commutative Algebra"},
QuillenSuslin.m2:26:	Keywords => {"Commutative Algebra"},
RandomCanonicalCurves.m2:13:	Keywords => {"Examples and Random Objects"},
RandomComplexes.m2:23:	Keywords => {"Examples and Random Objects"},
RandomCurves.m2:20:	Keywords => {"Examples and Random Objects"},
RandomCurvesOverVerySmallFiniteFields.m2:12:	Keywords => {"Examples and Random Objects"},
RandomGenus14Curves.m2:13:	Keywords => {"Examples and Random Objects"},
RandomIdeals.m2:19:	Keywords => {"Examples and Random Objects"},
RandomMonomialIdeals.m2:51:	Keywords => {"Examples and Random Objects"},
RandomObjects.m2:21:	Keywords => {"Examples and Random Objects"},
RandomPlaneCurves.m2:19:	Keywords => {"Examples and Random Objects"},
RandomRationalPoints.m2:14:	Keywords => {"Examples and Random Objects"},
RandomSpaceCurves.m2:19:	Keywords => {"Examples and Random Objects"},
RationalMaps.m2:18:Keywords => {"Commutative Algebra"},
RationalPoints.m2:13:     Keywords => {"Commutative Algebra"},
ReactionNetworks.m2:17:	Keywords => {"Applied Algebraic Geometry"},
ReesAlgebra.m2:34:	Keywords => {"Commutative Algebra"},
ReflexivePolytopesDB.m2:18:	Keywords => {"Convex Geometry"},
Regularity.m2:10:   Keywords => {"Commutative Algebra"},
RelativeCanonicalResolution.m2:13:Keywords => {"Commutative Algebra"},
ResidualIntersections.m2:18:    Keywords => {"Commutative Algebra"},
Resultants.m2:8:	Keywords => {"Commutative Algebra"},
RunExternalM2.m2:18:		Keywords => {"Miscellaneous"},
SCSCP.m2:25:	Keywords => {"Miscellaneous"},
SLPexpressions.m2:32:     Keywords => {"Numerical Algebraic Geometry"},
SLnEquivariantMatrices.m2:20:	   Keywords => {"Representation Theory"},
SRdeformations.m2:11:	Keywords => {"Combinatorial Commutative Algebra"},
SVDComplexes.m2:24:	Keywords => {"Homological Algebra", "Commutative Algebra"},
Schubert2.m2:16:	Keywords => {"Intersection Theory"},
SchurComplexes.m2:29:	Keywords => {"Representation Theory", "Homological Algebra"},
SchurFunctors.m2:13:	  Keywords => {"Homological Algebra", "Representation Theory"},
SchurRings.m2:28:	Keywords => {"Representation Theory"},
SectionRing.m2:11:     Keywords => {"Commutative Algebra"},
SegreClasses.m2:13:    Keywords => {"Intersection Theory"},
SemidefiniteProgramming.m2:20:    Keywords => {"Real Algebraic Geometry", "Interfaces"},
Seminormalization.m2:14:	Keywords => {"Commutative Algebra"},
Serialization.m2:8:     Keywords => {"Miscellaneous"},
SimpleDoc.m2:13:    Keywords => {"Miscellaneous"},
SimplicialComplexes.m2:25:	Keywords => {"Combinatorial Commutative Algebra"},
SimplicialDecomposability.m2:17:   Keywords => {"Combinatorial Commutative Algebra"},
SimplicialPosets.m2:25:	Keywords => {"Combinatorial Commutative Algebra"},
SlackIdeals.m2:10:    Keywords => {"Commutative Algebra", "Matroids"},
SpaceCurves.m2:16:	Keywords => {"Examples and Random Objects"},
SparseResultants.m2:8:	Keywords => {"Commutative Algebra"},
SpechtModule.m2:9:	Keywords => {"Representation Theory"},
SpectralSequences.m2:49:  Keywords => {"Homological Algebra"},
StatePolytope.m2:10:	Keywords => {"Convex Geometry", "Interfaces"},
StronglyStableIdeals.m2:9:	   Keywords => {"Commutative Algebra"},
Style.m2:5:     Keywords => {"Miscellaneous"},
SumsOfSquares.m2:21:    Keywords => {"Real Algebraic Geometry"},
SwitchingFields.m2:11:	Keywords => {"Commutative Algebra"},
SymbolicPowers.m2:9:	Keywords => {"Commutative Algebra"},
SymmetricPolynomials.m2:7:     Keywords => {"Combinatorics", "Representation Theory"},
TangentCone.m2:10:	Keywords => {"Commutative Algebra"},
TateOnProducts.m2:23:    Keywords => {"Commutative Algebra"},
TensorComplexes.m2:54:  Keywords => {"Commutative Algebra"},
TestIdeals.m2:80:Keywords => {"Commutative Algebra"},
Text.m2:5:     Keywords => {"Miscellaneous"},
ThreadedGB.m2:21:    Keywords => {"Groebner Basis Algorithms"},
Topcom.m2:23:	Keywords => {"Interfaces"},
TorAlgebra.m2:13:    Keywords => {"Commutative Algebra"},
ToricInvariants.m2:9:	Keywords => {"Toric Geometry"},
ToricTopology.m2:30:        Keywords => {"Toric Geometry"},
ToricVectorBundles.m2:21:    Keywords => {"Toric Geometry"},
TriangularSets.m2:12:    Keywords => {"Commutative Algebra"},
Triplets.m2:11:	Keywords => {"Commutative Algebra"},
Tropical.m2:22:	Keywords => {"Tropical Geometry"},
Truncations.m2:16:	Keywords => {"Commutative Algebra"},
Units.m2:5:	Keywords => {"Miscellaneous"},
VectorFields.m2:19:		Keywords => {"Commutative Algebra"},
VectorGraphics.m2:10:	Keywords => {"Miscellaneous"},
VersalDeformations.m2:15:    Keywords => {"Deformation Theory"},
VirtualResolutions.m2:25:    Keywords => {"Commutative Algebra", "Homological Algebra"},
Visualize.m2:34:	Keywords => {"Miscellaneous"},
WeylGroups.m2:14:	Keywords => {"Lie Groups and Lie Algebras"},
XML.m2:8:	Keywords => {"Miscellaneous"},
gfanInterface.m2:15:	Keywords => {"Interfaces"},
```

**Comment by olgakuznetsova** [comment]
Great, thank you!

**Comment by mahrud** [comment]
Perhaps we should change the other "Statistics" keywords to "Algebraic Statistics" as well. That's probably more accurate.

**Comment by olgakuznetsova** [comment]
@mahrud agree. we'll change in GraphicalModels, so there will be only Markov left.

**Comment by olgakuznetsova** [comment]
@DanGrayson we've pushed the changes that do not require the additional package. Would it be possible to check these, so we could implement the necessary changes if any? Thank you!

**Comment by DanGrayson** [comment]
Sure, I'll take a look.

**Comment by olgakuznetsova** [comment]
Thank you!

**Comment by DanGrayson** [comment]
Looks good to me.  Authors (@mikestillman , @sonjapetrovic , @luisgarciapuente , @jburkar1 , @cook, @carolinejansen , @abokeefe ) -- are these changes to Graphs and GraphicalModels acceptable?

**Comment by luisgarciapuente** [comment]
Dear Dan, I was part of the team that is requesting these changes. I also had contacted most everyone in this list  to make them aware of the changes. I will let them respond here if they want but in my private conversations they had approved these changes.

Best,

Luis

**Comment by olgakuznetsova** [comment]
Dear @DanGrayson,

Apologies for disturbing again. I have made a minor update to the new package StatGraphs (really just deleting 2 lines and adding 1 line with a standard function from Graphs). The final installs on my machine but has now failed one of the 8 checks here. 

Could you help understand the error message? I am at loss at what to do.

Thank you in advance,
Olga

**Comment by DanGrayson** [comment]
The error message indicates that the package ThreadedGB failed, not yours, so don't worry about it.  I've been trying to debug that for the authors, with a little bit of success.

**Comment by olgakuznetsova** [comment]
Thank you!

**Comment by olgakuznetsova** [comment]
@DanGrayson our package (GraphicalModels MLE) depends on this pull request: https://github.com/Macaulay2/M2/pull/1615 (EigenSolver). Since the latter has not been merged into master yet, I expect our package to fail the checks. 

Would it be possible to trigger the checks again after the other pull request is resolved? Thank you!

**Comment by DanGrayson** [comment]
> @DanGrayson our package (GraphicalModels MLE) depends on this pull request: #1615 (EigenSolver). Since the latter has not been merged into master yet, I expect our package to fail the checks.
> 
> Would it be possible to trigger the checks again after the other pull request is resolved? Thank you!

Yes, indeed.

**Pull request merged**
