### PR TITLE
(revised) Miura: Divisor Class Group Arithmetic

### PR DESCRIPTION
**Pull request by prof-joe**
I have closed the pull request by mistake. I am very happy to suggest me what I should do next when you have time. Thank you.

### CODE REVIEW

**Comment by DanGrayson** [comment]
I tried installing and checking your package, but there are errors.  You can try this yourself with
```
  installPackage "Miura"
  check "Miura"
```

When it works, just commit and push the changes to your fork and I'll be notified.  The deadline is
April 15 for the next version.

**Comment by prof-joe** [comment]
Thank you for taking time for the package.
I will complete this as soon as possible.
Joe.
-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by prof-joe** [comment]
Hello Dan

I tried to install "Miura" from 
http://habanero.math.cornell.edu:3690/
by UpLoading the file Miura.m2.
Then, when I hit the command 
installPackage "Miura"
the following error message appears:

i1 : installPackage "Miura"
currentString:1:1:(2):[19]: error: no method found for applying complete to:
     argument   :  field (of class Symbol)

I found one error in the source and fixed it (as attached).

Is it possible to locate the problem and suggest me how?

Thank you very much.

Joe.

**Comment by DanGrayson** [comment]
I can't reproduce your error.  Here is what I get:
```
i1 : loadPackage "Miura"
Miura.m2:36:55:(2):[7]: error: syntax error at '%'
stdio:1:1:(3): --backtrace: parse error--
```

I'm not sure this small package has things other people can use.  Perhaps we should wait until it is more mature.  Later on I (and others) could give you specific advice.

**Comment by DanGrayson** [comment]
Closing, for now.  Please feel free to reopen when you feel the contribution is ready.

**Comment by prof-joe** [comment]
Dear Dan

I missed the message a couple days ago.
The error was solved easily, and I think I can give 
the final version in a day or two.

Is it possible to reopen the page for me?
http://habanero.math.cornell.edu:3690/

Currently, I cannot access the page although I could yesterday.
(I am using version 1.8.X but my windows version is much lower)

Thank you very much.

Joe.
-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by DanGrayson** [comment]
@mikestillman , is the try M2 server down?

**Comment by prof-joe** [comment]
I think so. Can you fix it for me ? Thank you very much.

Joe.
-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by DanGrayson** [comment]
@prof-joe, my question was addressed to Mike Stillman using the "@" notation of github.

**Comment by prof-joe** [comment]
Thank you. Joe.
-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by mikestillman** [comment]
Cornell had a full power outage today.  I might need to go in and physically restart the server.

**Comment by prof-joe** [comment]
Thank you very much. Joe.
-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>


> Cornell had a full power outage today.  I might need to go in and physically restart the server.
> 
> 
>

**Comment by DanGrayson** [comment]
Dear Joe,

The purpose of a Macaulay2 package is to propagate a substantial body of nontrivial code containing
algorithms that are likely to be useful to other mathematicians at a research level.  I think your package
has not reached that level, since it consists of just a handful of functions, each of which is
short.

I suggest you resubmit it when you have something fitting that description.  Take a look at the contents of the other packages to see what one normally finds in a package, especially those that have been published in the journal at http://j-sag.org/.

Probably you could find a more descriptive name than "Miura", which will not give users an idea of what the package is about.

Please also see whether the package "Divisor" overlaps with yours.

Dan

**Comment by prof-joe** [comment]
Dear Dan

Thank you for suggestion.

The package "Miura" deals with addition between two Jacobians
in any nonsingular curves as long as the definition equation
is expressed by a Miura standard form.

http://arxiv.org/pdf/1512.08040v1.pdf

I think this contains the EllipticCurves package in which 
1. an elliptic curve is expressed by its Weierstrass form; and 
2. given coordinates of P and Q, P+Q is computed.

On the other hand, in Miura 
1. an non-singular curve is expressed by its Miura form; and 
2. given divisor class groups (reduced ideals) [I] and [J], 
reduced ideal [I*J]  is computed. In this sense, EllipticCurves 
is a special case of Miura. 

The package Divisor does not consider to express the divisor classes
in terms of the defining equation.

I know that the code is very short, but that does not mean that the package is
poor. In fact, many authors tried to write huge programs [1][2] for implementing 
the algorithm. My discovery is that M2 implements the algorithm pretty smoothly.

Also, compared with the EllipticCurves and Divisor packages, Miura utilizes 
the M2 math background (communicative ring and Grobner basis). I believe that
this package will be liked by many mathematicians.

Of course, you have a right to reject any proposed package but I want you to
glance over the manuscript

http://arxiv.org/pdf/1512.08040v1.pdf

before your making a decision. I will complete to fix
bugs after the Cornel server resumes, in a day or two.

Thank you.

Joe.

-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by mikestillman** [comment]
web.macaulay2.com <http://web.macaulay2.com/> should be back on line now.  Sorry for the interruption.

— mike

**Comment by prof-joe** [comment]
Dear Mike. Thank you very much. Joe.
-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

> web.macaulay2.com <http://web.macaulay2.com/> should be back on line now.  Sorry for the interruption.
> 
> ? mike
>

**Comment by prof-joe** [comment]
installPackage "Miura" has passed. I do not know how to update the following. I'd be happy if you could proceed with this. Thank you very much. Joe.

-- -*- coding: utf-8 -*-
newPackage(
	"Miura", 
	Version => "1.0",
	Date => "25 December 2015",
	Authors => {
		{Name => "Joe Suzuki", 
		     Email => "suzuki@math.sci.osaka-u.ac.jp", 
		     HomePage => ""}
	},
	Headline => "Miura: Divisor Class Group Arithmetic",
	DebuggingMode => false
	)

export {"pR", "qR", "inv", "reduced", "add", "double", "multi"}

-- specify the underlying polynomial ring 
pR=method()
pR(Thing,List,List):=(kk,v,w)->kk[v,MonomialOrder=>{Weights => w, Weights=>toList(1 ..#w) }];

-- specify the quotient ring
qR=method()
qR(PolynomialRing,Thing):=(PR,p)->PR/ideal p

-- computing the reduced inverse ideal
inv=method()
inv(Ideal):=J-> quotient(ideal first first entries gens gb J, J)

-- computing the reduced ideal
reduced=method()
reduced(Ideal):=J->inv inv J

-- computing the reduced multiplied ideal
add=method()
add(Ideal,Ideal):=(J,K)-> reduced J*K

-- computing the reduced squared ideal 
double=method()
double(Ideal):=J->add(J,J)

-- computing the reduced ideal multiplied by integer 
multi=method()
multi(Ideal,ZZ):=(J,m)-> if m==0 then return ideal promote(1, ring J) else if m%2==0 then double multi(J,m//2) else add(double multi(J,(m-1)//2),J)

beginDocumentation()
-------------------------------------------------------
--DOCUMENTATION Miura
-------------------------------------------------------

document{
    Key => (pR, Thing, List, List),
	Inputs => {"kk"=>{"any field"},"v"=>{"a list of variables"},"w"=>{"a list of weights corresponding to", TT "v"} }, 
    Usage => "R=pR(kk,v,w)",
 	Outputs => {ofClass PolynomialRing},
    Headline => "A method for specifying the underlying polynomial ring",
    PARA {"The function pR generates the polynomial ring kk[v] with the monomial order w.r.t. weights w over the variables v. The elements in w should be positive and mutually prime. The number of elements in v and w coincide."},
	EXAMPLE {"R=pR(GF 13,{x,y},{2,3})"}
}

document{
    Key => (qR, PolynomialRing, Thing),
	Inputs => {"PR"=>{"the polynomial ring specified using", TT "pR"},"p"=>{"the ideal (generators) of the curve"}}, 
    Usage => "I=qR(R,p)",
 	Outputs => {ofClass Ideal},
    Headline => "A method for specifying the underlying quotient ring",
    PARA {"The function qR generates the quotient ring R over the ideal p. The variables and equations (the ideal generators) should be specified by pR and in the form of Miura, respectively."},
	EXAMPLE {"R=pR(GF 13,{x,y},{2,3})","I=qR(R,y^2-x^3-7*x)"}
}

document{
    Key => (inv, Ideal),
	Inputs => {"J" => {"an integral ideal"}},
    Usage => "K=inv(J)",
    Outputs => {ofClass Ideal},
    Headline => "A method for computing the reduced inverse ideal",
    PARA {"The function inv computes the inverse reduced ideal given an integral ideal"},    
	EXAMPLE {"R=pR(GF 13,{x,y},{2,3})", "I=qR(R,y^2-x^3-7*x)", "J=ideal(x,y);inv(J)"}
}
 
document{
    Key => (reduced, Ideal),
	Inputs => {"J" => {"an integral ideal"}},
    Usage => "K=reduced(J)",
    Outputs => {ofClass Ideal},
    Headline => "A method for computing the reduced ideal",
    PARA {"The function reduced computes the reduced ideal given an integral ideal"},   
	EXAMPLE {"R=pR(GF 13,{x,y},{2,3})","I=qR(R,y^2-x^3-7*x)","J=ideal(x,y);reduced(J)"}
}

document{
    Key => (add, Ideal, Ideal),
	Inputs => {"J" => {"an integral ideal"},"K" => {"an integral ideal"}},
    Usage => "L=add(J,K)",
    Outputs => {ofClass Ideal},
    Headline => "A method for computing the reduced ideal of J*K",
    PARA {"The function add computes the reduced ideal of multiplication of two integral ideals"},    
	EXAMPLE {"R=pR(GF 13,{x,y},{2,3})","I=qR(R,y^2-x^3-7*x)","J=ideal(x,y)",
			 "K=ideal(x-2,y-3)","add(J,K)","L=J*K","reduced(L)"}
}

document{
    Key => (double, Ideal),
	Inputs => {"J" => {"an integral ideal"}},
    Usage => "K=double(J)",
    Outputs => {ofClass Ideal},
    Headline => "A method for computing the squared ideal J*J",
    PARA {"The function double computes the reduced ideal of J*J given an integral ideal J"},    
	EXAMPLE {"R=pR(GF 13,{x,y},{2,3})","I=qR(R,y^2-x^3-7*x)","J=ideal(x,y)", "double J", "reduced(J*J)","add(J,J)"}
}

document{
    Key => (multi, Ideal, ZZ),
	Inputs => {"J" => {"an integral ideal"}, "m" => {"a positive integer"}},
    Usage => "K=multi(J,m)",
    Outputs => {ofClass Ideal},
    Headline => "A method for computing the reduced ideal of an integral ideal J multimplied by integer m",
    PARA {"	        The function multi computes the reduced ideal of an integral ideal multiplied by a nonnegative integer"},    
	EXAMPLE {"R=pR(GF 13,{x,y},{2,3})","I=qR(R,y^2-x^3-7*x)","J=ideal(x,y)","multi(J,5)"}
}

TEST ///
--Hyper Elliptic Curves
R=pR(GF 2^3,{x,y},{2,5});
I=qR(R,y^2-x^5-1);
J=ideal(x+1,y);
K=ideal(x,y-1);
L=ideal(x,y+1);
A=add(J,K)
multi(A,2)
multi(A,3)
multi(A,4)
A5=multi(A,5)
add(A5,A5)
///
TEST ///
--Cab Curves
R=pR(GF 5,{x,y},{3,4});
I=qR(R,y^3-x^4-1);
J=ideal(x-2,y-3);
K=ideal(x-4,y);
L=ideal(x,y-1);
A=add(J,add(K,L))
A2=multi(A,2)
A3=multi(A,3)
A4=multi(A,4)
A5=multi(A,5)
A6=multi(A,6)
///
TEST ///
--General Curves
R=pR(GF 5,{x,y,z},{4,6,5});
I=qR(R,{y^2-x^3-1,z^2-x*y-1});
J=ideal(x-2,y-2,z);
K=ideal(x-4,y,z-1);
L=ideal(x,y-1,z-4);
M=ideal(x,y-4,z-1);
A=J*K*L*M
inv(A)
multi(A,654)
multi(A,327)
multi(A,109)
///
end

**Comment by DanGrayson** [comment]
Re: "installPackage "Miura" has passed. I do not know how to update the following."

Dear Joe,

Please also try `check "Miura"`.  To update your pull request, run `git commit` on the file and then 
`git push`.

**Comment by DanGrayson** [comment]
Re: " deals with addition between two Jacobians in any nonsingular curves "

Perhaps you mean "sums of divisors on a nonsingular curve"?

**Comment by prof-joe** [comment]
Yes, divisor classes rather than divisors themselves.

For elliptic curves,
D1=(P1)-(O), D2=(P2)-(O) ==>  D1+D2 =(P1)+(P2)-2(O)
But, this package computes
[D1]=(P1)-(O), [D2]=(P2)-(O) ==>  [D1+D2] =(P1+P2)-(O)

Each divisor class is expressed by 
a (unique) reduced divisor E - g (O) 
with positive divisor E of degree g (genus)

Addition of divisor classes is the same as multiplying ideal classes.
The ideal classes are to be expressed by reduced ideals.

Joe.
-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by DanGrayson** [comment]
Your preprint on the idea behind it adds a lot of information, but your package's source code
fails to reveal its existence!

How about at least adding a documentation node for the package itself, under the key "Miura"?
On that node give a link to the arxiv preprint and explain the basic theory, including the part about
E - g(O).  Then a user could tell what the package is for.

What about renaming the package to something like "DivisorsOnCurves"?

What's the definition of the symbol L in the paper?

The word "arithmetic" for what's happening when you add divisor classes is not the
best, since it is usually used just when the things being added are numbers.  It 
would be better to refer to implementing the divisor class group algebraic operations,
or to speak of computations in divisor class groups.

It would be good if the preprint answered these questions:

Does it work for any non-Weierstrass point O?  If so, how is that related to the condition
that the valuations of the functions with poles at most at O form a monoid that can be generated
by mutually prime natural numbers?

Is there any way for the user to tell whether his equations satisfy the needed hypotheses?

Is there any way for the user to transform an arbitrary curve into one given by equations that
satisfy the needed hypotheses?

It would be nice if the preprint contained references to the papers and thesis of Miura.  I know
they are in Japanese.

**Comment by prof-joe** [comment]
Dear Dan,

Thank you for the useful comments.

1. I will add description of this package not just to
headline but also para so that many people can notice it.
For example, "the curve should be expressed in the Miura form,
an extention of the Weierstrass form for elliptic curves. Also,
the pole orders should be specified such as 2 and 3 for x and y, respectively,
of the elliptic curves." Explanation using E-g(O) would be useful.

2. $L$ is a typo. ${\cal}(\infty P_\infty)$ is correct.

3. The package will contain a variety of functions in the future such as
a. given a monoid generator $a_1,\cdots, a_t$, compute the genus,
b. given a monoid generator $a_1,\cdots, tell whether the curve is complete
intersection or not,
c. given a defining equation, tell whether it is in the form of Miura, etc.,
The common feature is that the curve is expressed by Miura. If you allow me,
I'd be glad to use the name "Miura".

4. The term "arithmetic" is from the book title J. Silverman: "The arithmetic
of elliptic curves". I understand that "arithmetic" can be used in many situations.
But, I will recheck the manuscript so that nothing misleading occurs around "arithmetic".

5. For the conditions in the manuscript, (1) is easy to check but (2) is difficult.
For (2), $\{F_M|M\in V\}$ should be a Grobner basis. On the other hand,
if the curve is complete intersection (2) automatically follows, which I proved 
ten years ago [7]. 

6. The last two questions are difficult to answer now.
Let me take time to add the answer to the paper before submitting it.

7. Miura's thesis is in [5]

I will submit the final to github in several hours.

Joe.
-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by DanGrayson** [comment]
When Joe Silverman refers to the arithmetic of elliptic curves, he's talking about what happens when they are defined over number fields.

**Comment by prof-joe** [comment]
I have just committed the latest version. Thank you.
I did not use the term "addition" to avoid misleading.
Thank you.
Joe.
-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by DanGrayson** [comment]
I hope, rather, it's the term "arithmetic" that you were careful about.

If you want me to be able to see the latest version of the package here, you should run `git push`.

**Comment by prof-joe** [comment]
I have just push the latest version. In case you miss it,  please let me know. Thank you very much. Joe.

**Comment by DanGrayson** [comment]
Your pull request has deleted three of our important files.  Could you fix that?

**Comment by prof-joe** [comment]
Hello

I am sorry but I might have done something wrong.

I just have reverted the four files including the three.

Is this OK for you? Thank you very much.

Joe.

-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by DanGrayson** [comment]
Okay, it looks better.  Is it ready for us to consider?

**Comment by prof-joe** [comment]
Yes, please. Thank you.

-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by DanGrayson** [comment]
You seem to have reverted too much, so now the new documentation node for the package itself is no longer there.

**Comment by prof-joe** [comment]
I have just committed the latest version. Is this enough for you? Thank you.

**Comment by DanGrayson** [comment]
No, nothing has changed in 11 hours.

**Comment by prof-joe** [comment]
Is it possible to set up the attached file for me?
Thank you very much.

Joe.
-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by DanGrayson** [comment]
Okay, email it to me at drg@uiuc.edu

**Comment by DanGrayson** [comment]
Package added in commit e01daa4c58a2c2f6b8e053993e9b448a2134ad72

**Pull request closed without merging**
