### PR TITLE
Adding ExteriorModules.m2

### PR DESCRIPTION
**Pull request by lucamata**
New [certified](https://msp.org/jsag/2021/11-1/p08.xhtml) package for manipulating special classes of monomial modules over an exterior algebra of a finite dimensional vector space over a field. This package extends the one on monomial ideals (```ExteriorIdeals```) and needs it to properly work. An updated version of such a package is available on the pull request [#2282](#2282) (minor changes to ExteriorIdeals).

### CODE REVIEW

**Comment by DanGrayson** [comment]
an error from your package:
```m2
../../../../../Macaulay2/packages/ExteriorModules.m2:461:28:(2):[59]: error: expected left hand parameter to be a function, type, or a hash table
```

**Comment by lucamata** [comment]
Sorry, I should have been more careful. I suppose the problem is the following:
I have implemented the method (minimalBettiNumbers,Ideal) in the [new](https://github.com/Macaulay2/M2/pull/2282) version of **ExteriorIdeals**. Moreover, I have overloaded the method in **ExteriorModules**: (minimalBettiNumbers,Module). Clearly the second package uses the declaration made in the first one. I have installed and checked ExteriorModules (error-free) using the new version of Exteriorideals.
Since ExteriorIdeals has now been merged, is it possible to check again ExteriorModules?
I apologize for the inconvenience.

**Comment by DanGrayson** [comment]
Maybe you should merge the development branch into your ExteriorModules branch -- then your branch would have the latest version of ExteriorIdeals and the tests would get run again.

**Comment by lucamata** [comment]
Just done, the tests started again. Thank you so much for your help.

**Pull request merged**
