### PR TITLE
CotangentSchubert update, VectorGraphics and LieTypes minor updates

### PR DESCRIPTION
**Pull request by pzinn**
the package `CotangentSchubert` was updated:
- various bug fixes
- improved implementation of separated/almost separated descent puzzles
- added visualization of double puzzles
- a minor update of `VectorGraphics` was incorporated since it was required by some of the changes above.
- minor update of `LieTypes`: improved weight parsing, doc fixes, no functionality changes

### CODE REVIEW

**Comment by pzinn** [comment]
I don't understand why two of the builds are failing. it seems to have nothing to do with my packages...

**Comment by d-torrance** [comment]
The `autotools-macos` build is failing due to #2857, and the `autotools-ubuntu` build is failing due to some bug I apparently introduced in #2850.

**Comment by mikestillman** [comment]
@pzinn Could you merge development into this PR?  It is failing on html validation, which I think @d-torrance fixed.  Perhaps also other of your pull requests fail on the same problem.

**Comment by d-torrance** [comment]
> trying but still failing!

My fault!  The "fix" wasn't a fix after all.  Once #2922 is merged, the tests should work again.

**Pull request merged**
