### PR TITLE
Triangulations

### PR DESCRIPTION
**Pull request by mikestillman**

### CODE REVIEW

**Comment by DanGrayson** [comment]
Lots of conflicts...

**Comment by mikestillman** [comment]
Yes, there should be only THREE changed files (maybe 4…)

Not sure what got screwed up...

**Comment by mikestillman** [comment]
@DanGrayson I tried merging development into this branch too, and got lots of changes.  Not sure how that happened... (probably I screwed up a previous use of ```git merge --rebase``` when placing this on top of development).  Any suggestions? What I might do is make another branch, add in these 3-4 files, then create a new pull request.  I will lose the history of these files, but that is probably not an issue...

**Comment by DanGrayson** [comment]
Maybe you were on a very old version of development.  If it really is just new files, start a new branch on top of the current development branch and add the files.

**Comment by mikestillman** [comment]
It wasn't that old...  But the files affected are: =distributed (1 package added), Polyhedra/core/polyhedron/methds.m2 (1 line changed), Topcom.m2 (many changes), and a new file: Triangulations.m2

**Comment by d-torrance** [comment]
@mikestillman - It looks like this version of the `Topcom` package is missing #2674, which had one additional fix for TOPCOM >= 1.0.0 support.

**Comment by mikestillman** [comment]
Unravelling this mess is going to take me a bit.  I don't think you would, but please don't accept this pull request yet.

**Comment by mikestillman** [comment]
@d-torrance Thanks, yes, I thought I had included that.  But apparently had not... It is hard (for me) to see what else might have changed from the release., but I will look over the diffs one by one...

**Comment by mahrud** [comment]
@mikestillman I think merging development into the branch (as opposed to rebasing on top of development) caused this problem. I attempted a fix in #2699 by first linearizing the part of git history involving Topcom, then applying your commits.

**Pull request closed without merging**
