### PR TITLE
Matroids v1.6.0

### PR DESCRIPTION
**Pull request by jchen419**
- Add methods: isNonCrossing, isPositivelyOriented, positiveOrientation, isPositivelyOrientable, kruskalSpanningForest, coordinatingPath, rescalingRepresentative, searchRepresentation, writeToString, saveMatroid, readFromFile
- Add documentation for (co)extensions from Matt Mastroeni

### CODE REVIEW

**Comment by jchen419** [comment]
So I think (one current) issue is that after #2625, `delete` no longer works on a `MutableList` (since these are `BasicList`s, but not `VisibleList`s). @d-torrance, @DanGrayson: any opinions on keeping `delete` functional on `MutableList`s?

**Comment by d-torrance** [comment]
> So I think (one current) issue is that after #2625, `delete` no longer works on a `MutableList` (since these are `BasicList`s, but not `VisibleList`s). @d-torrance, @DanGrayson: any opinions on keeping `delete` functional on `MutableList`s?

I think it totally makes sense for `delete` to work in this case.  I just didn't think about it for #2625.  The following should work:

```diff
--- a/M2/Macaulay2/m2/structure.m2
+++ b/M2/Macaulay2/m2/structure.m2
@@ -20,7 +20,8 @@ position(VisibleList,VisibleList,Function) := o -> (v,w,f) -> (
      )
 
 delete = method()
-delete(Thing, VisibleList) := (x,v) -> select(v, i -> i =!= x)
+delete(Thing, VisibleList)  :=
+delete(Think, MustableList) := (x,v) -> select(v, i -> i =!= x)
 
 -- Local Variables:
 -- compile-command: "make -C $M2BUILDDIR/Macaulay2/m2 "
```
This would create a brand-new `MutableList` object without the deleted element instead of modifying the original, which may or not be the desired behavior.

**Comment by jchen419** [comment]
@d-torrance: That's a good point - I guess `delete` has always returned a new copy, which makes sense for immutable objects. Should it be smarter for mutable objects? What does `remove` do for a `MutableHashTable`? (Btw: I was thinking if `delete` should just be defined on `BasicList`s.)

**Comment by d-torrance** [comment]
> @d-torrance: That's a good point - I guess `delete` has always returned a new copy, which makes sense for immutable objects. Should it be smarter for mutable objects? What does `remove` do for a `MutableHashTable`? (Btw: I was thinking if `delete` should just be defined on `BasicList`s, as anyways this is the level of generality that `select` is defined for.)

`remove` modifies the original:

```m2
i1 : x = new MutableHashTable from {1 => 2, 3 => 4}

o1 = MutableHashTable{...2...}

o1 : MutableHashTable

i2 : remove(x, 1)

i3 : peek x

o3 = MutableHashTable{3 => 4}
```
Maybe `delete` could keep its current behavior, but for `BasicList` objects, too, and `remove(MutableList, Thing)` could be added?

**Comment by jchen419** [comment]
> Maybe `delete` could keep its current behavior, but for `BasicList` objects, too, and `remove(MutableList, Thing)` could be added?

That sounds good to me - though I imagine the documentation should have a caveat, stating that `remove` is more sensible than `delete` for `MutableList`s.

**Pull request merged**
