### PR TITLE
New MultigradedBGG Package

### PR DESCRIPTION
**Pull request by sashahbc**
This package implements the multigraded BGG functors, including an implementation of differential modules, their minimal free resolutions, and a method for computing strongly linear strands of multigraded free resolutions.

### CODE REVIEW

**Comment by mahrud** [comment]
You should also add the package name to `M2/packages/=distributed-packages`.

**Comment by DanGrayson** [comment]
Can you add the name of your new package to the file `packages/=distributed-packages`?

**Comment by d-torrance** [comment]
I went ahead and took the liberty of adding the package to `=distributed-packages`.  (For some reason, pushing the commit closed the PR, but I re-opened it.  Strange!)

**Comment by d-torrance** [comment]
Here's the failing test:

```diff
testing: ComputationsBook::varieties
--- test.out.expected.trim	2024-05-09 20:48:06.412740405 +0000
+++ test.out.trim	2024-05-09 20:48:07.220745579 +0000
@@ -335,8 +335,8 @@
 
 i48 : set flatten entries gens M - set flatten entries C.dd_1
 
-            6 7   10 5   5 5 5   5 10
-o48 = set {x y , x  y , x y z , x y  }
+            5 10   5 5 5   10 5   6 7
+o48 = set {x y  , x y z , x  y , x y }
 
 o48 : Set
```
I can't imagine that this is related to this PR -- seems like maybe it could be a result of #3209?  But why did the tests pass for it and fail here?

**Comment by mahrud** [comment]
Ah, this is because the order of the keys in sets aren't fixed. Rather than sorting it everywhere we should change that test to sort them, I believe.

**Comment by sashahbc** [comment]
I appreciate the help--but I don't understand the html check either. What is the problem?

**Comment by d-torrance** [comment]
> I appreciate the help--but I don't understand the html check either. What is the problem?

Are you referring to the [failing check](https://github.com/Macaulay2/M2/actions/runs/9010471007/job/24756586079) from the first commit?

```
make -C Macaulay2/packages validate-html
make[1]: Entering directory '/home/runner/work/M2/M2/M2/BUILD/build/Macaulay2/packages'
validating MultigradedBGG documentation ...
ERROR:html5validator.cli:There are no files to check
invalid packages: MultigradedBGG
```

That was there because the package was missing from `=distributed-packages`.  It didn't know to build any documentation for the package, so there was no html documentation to validate.

**Pull request closed without merging**
