### PR TITLE
A few Python updates

### PR DESCRIPTION
**Pull request by d-torrance**
* Interpret lists (and other non-sequence visible lists) as arguments themselves and not as lists of arguments for `toFunction` (addressing part of [#2315 (comment)](https://github.com/Macaulay2/M2/issues/2315#issue-1057501584)).

### Before
```m2
i1 : loadPackage "Python"

o1 = Python

o1 : Package

i2 : (rs "len") {1, 2, 3}
TypeError: len() takes exactly one argument (3 given)
stdio:2:1:(3): error: python error
```

### After
```m2
i2 : (rs "len") {1, 2, 3}

o2 = 3

o2 : PythonObject of class int
```

* Convert all visible lists to Python lists with `toPython` unless another method function is installed (like `toPython(Sequence)`, which converts sequences to tuples).

```m2
i3 : toPython [1, 2, 3]

o3 = [1, 2, 3]

o3 : PythonObject of class list

i4 : toPython <|1, 2, 3|>

o4 = [1, 2, 3]

o4 : PythonObject of class list
```

* Add a couple more `value(PythonObject)` hooks for useful classes from the `collections` module.

```m2
i7 : c = import "collections"

o7 = <module 'collections' from '/usr/lib/python3.9/collections/__init__.py'>

o7 : PythonObject of class module

i8 : d = c@@defaultdict rs "int"

o8 = defaultdict(<class 'int'>, {})

o8 : PythonObject of class collections.defaultdict

i9 : d_"foo"

o9 = 0

o9 : PythonObject of class int

i10 : value d

o10 = HashTable{foo => 0}

o10 : HashTable

i11 : c@@Counter "foo"

o11 = Counter({'o': 2, 'f': 1})

o11 : PythonObject of class collections.Counter

i12 : value oo

o12 = Tally{f => 1}
            o => 2

o12 : Tally
```

### CODE REVIEW

**Comment by d-torrance** [comment]
Just added a few more commits adding unary operations:

```m2
i2 : x = rs "5"

o2 = 5

o2 : PythonObject of class int

i3 : -x

o3 = -5

o3 : PythonObject of class int

i4 : +x

o4 = 5

o4 : PythonObject of class int
```

**Comment by DanGrayson** [comment]
The function name "rs" is pretty cryptic.  Can you improve that (eventually)?

**Comment by d-torrance** [comment]
`rs` (which already existed in the package before my updates) is a wrapper around `runPythonString`. It concatenates the arguments and prints some debugging info if `debugLevel` is positive. Maybe we should make `runPythonString` do this instead and just make `rs` an alias?

**Comment by DanGrayson** [comment]
Maybe I'm responsible for creating "rs".  But still, it's too cryptic, even as a synonym, and will make code unreadable.  `runPythonString` sounds good.  Or `pythonValue`, which is like `value`.

**Pull request merged**
