### PR TITLE
refactoring numerical packages 

### PR DESCRIPTION
**Pull request by antonleykin**
Most changes concern redistributing code between various numerical packages and filling in missing documentation.

In particular,
- new package `NumericalLinearAlgebra` was created
- `NumericalHilbert` was removed (all functionality absorbed by `NoetherianOperators` and `NumericalLinearAlgebra`

### CODE REVIEW

**Comment by DanGrayson** [comment]
```
error: file not found on path: "NumericalHilbert.m2"
```

**Comment by antonleykin** [comment]
> ```
> error: file not found on path: "NumericalHilbert.m2"
> ```

@DanGrayson The file indeed is no more... but I'm not sure how you get this message.

**Comment by mahrud** [comment]
> @DanGrayson The file indeed is no more... but I'm not sure how you get this message.

It's from here:

https://github.com/antonleykin/M2/blob/50b4a9324ad4d823953f7c4a7ca1a197d2be988b/M2/Macaulay2/packages/Macaulay2Doc/changes.m2#L1086

Might be worth it to fix a few other mentions of it too:
```
Macaulay2/packages/NumericalAlgebraicGeometry/SYSTEMS/NumericalHilbert/whitney_umbrella.m2:loadPackage "NumericalHilbert"
Macaulay2/packages/NumericalAlgebraicGeometry/SYSTEMS/NumericalHilbert/NHexamples.m2:loadPackage "NumericalHilbert"
Macaulay2/packages/NumericalAlgebraicGeometry/SYSTEMS/NumericalHilbert/NHexamples.m2:loadPackage "NumericalHilbert"
Macaulay2/packages/NumericalAlgebraicGeometry/SYSTEMS/NumericalHilbert/NHexamples.m2:loadPackage "NumericalHilbert"
Macaulay2/packages/NumericalAlgebraicGeometry/SYSTEMS/NumericalHilbert/NHexamples.m2:debug NumericalHilbert
Macaulay2/packages/NumericalAlgebraicGeometry/SYSTEMS/NumericalHilbert/cyclic4.m2:loadPackage "NumericalHilbert"
Macaulay2/packages/NumericalAlgebraicGeometry/SYSTEMS/NumericalHilbert/cyclic4.m2:loadPackage "NumericalHilbert"
```

**Comment by antonleykin** [comment]
Thanks, @mahrud! What part of the build process checks for mentions of a package?

I've eliminated all references to `NumericalHilbert` except
```
   LI { "NumericalHilbert (absorbed by ", TO "NoetherianOperators::NoetherianOperators", "), a package by Robert Krone for numerically computing local dual spaces and Hilbert functions, has been added." },		 		    
```
in `changes.m2`. Now it builds with no errors for me.

@kroner, in https://github.com/Macaulay2/M2/pull/1651/commits/36aeaab7c66c88ca49a45a271f7531851b901c4c I have deleted `NumericalHilbert/*.m2`. This seems to be is a handful of examples --- check if anything useful was already salvaged in `NoetherianOperators`.

**Comment by mahrud** [comment]
> Thanks, @mahrud! What part of the build process checks for mentions of a package?

No part explicitly searches for mentions of a package (especially nonexistent ones), but `html TO "Pkg :: ABC"` will look for the physical file `Pkg.m2` in order to load it and see what is the correct link for the node `ABC`.

> @kroner, in [36aeaab](https://github.com/Macaulay2/M2/commit/36aeaab7c66c88ca49a45a271f7531851b901c4c) I have deleted `NumericalHilbert/*.m2`. This seems to be is a handful of examples --- check if anything useful was already salvaged in `NoetherianOperators`.

To be clear, you don't have to delete all mentions of it. I mentioned the examples in case you wanted to fix them so they would run.

**Comment by antonleykin** [comment]
Thanks to a failed run (1 out of 6 runs failed on a `check_3 "EigenSolver"`) more cleanup was done.

Why the run failed though is a mystery. If all tests are derandomized, then the only thing that could be different (from other runs) is how some routine in `lapack` behaves.

**Comment by DanGrayson** [comment]
Looks good.  Robert ( @kroner ) -- are these changes okay with you?  (Your package NumericalHilbert goes away,
and you become a co-author of a new package.

**Comment by kroner** [comment]
Yes, these changes are good with me!

**Pull request merged**
