### PR TITLE
CMake maintenance

### PR DESCRIPTION
**Pull request by mahrud**

### CODE REVIEW

**Comment by mahrud** [comment]
@DanGrayson, this hadn't passed checks yet! Why do you merge before the tests pass? Did you see  #1783?

**Comment by DanGrayson** [comment]
What I saw was that you cancelled the jobs.  Figuring you had a reason for that, I pulled.

**Comment by mahrud** [comment]
I cancelled because I wanted to add more commits.

**Comment by DanGrayson** [comment]
Okay, next time I'll realize that's a possibility.

**Pull request merged**
