### PR TITLE
fix of #321

### PR DESCRIPTION
**Pull request by pzinn**
Rings are flattened if necessary to compute gcd.
A test is added.
An error is produced is ring is a quotient ring since we can't guarantee it's a UFD.

### CODE REVIEW

**Comment by pzinn** [comment]
checks have failed. interesting. could it be  some packages rely on gcd working even with quotient rings?

**Comment by DanGrayson** [comment]
It looks like an example in the Graphs package uses "gcd" on a quotient ring, which is why at least one, and probably all, of the builds failed.

https://github.com/Macaulay2/M2/pull/2209/checks?check_run_id=3286586524#step:11:38934

**Comment by pzinn** [comment]
`noetherianOperators` of the package `NoetherianOperators` also uses `gcd` in quotient rings.
At this stage, several options:
- remove the test / error altogether
- replace it with a warning -- is there a standardized way of doing that?
- fix packages / examples...

**Comment by DanGrayson** [comment]
No, better to have an error than a warning.  Why not consult with the authors of the examples to see what they had in mind -- why they thought the quotient ring would support gcd?

Maybe look at the quotient rings to see whether it's obvious.

**Comment by pzinn** [comment]
> It looks like an example in the Graphs package uses "gcd" on a quotient ring, which is why at least one, and probably all, of the builds failed.
> 
> https://github.com/Macaulay2/M2/pull/2209/checks?check_run_id=3286586524#step:11:38934

that one is easy to fix. I'll check with the authors if they're OK with my fix.

**Comment by DanGrayson** [comment]
Rerunning all the jobs, so we can get at least one of them to go through all the tests.

**Comment by DanGrayson** [comment]
Thanks!

**Pull request merged**
