### PR TITLE
Including addition changes missed in original PR

### PR DESCRIPTION
**Pull request by aadams22**

### CODE REVIEW

**Comment by mahrud** [comment]
@DanGrayson did you mean to merge this directly to master when a test is failing?

**Comment by DanGrayson** [comment]
oops, no.  Thanks.

**Comment by DanGrayson** [comment]
But why did only one of the 6 builds fail?

**Comment by DanGrayson** [comment]
@aadams22 -- I've had to undo the inclusion of your changes, because test #2 of the package is failing.  If you'd like that to be in 1.17, could you fix it quite soon and submit another pull request?

**Comment by DanGrayson** [comment]
> But why did only one of the 6 builds fail?

@mahrud -- is this the only place in the work flow where we test the packages?:
```yaml
      - name: Run Tests using Autotools
        if: matrix.build-system == 'autotools' && matrix.os == 'ubuntu-latest' && matrix.compiler == 'default'
        run: |
          make check -o check-in-libraries
          make -C Macaulay2/html-check-links check
```

**Comment by mahrud** [comment]
Dan, you didn't need to do this! She submitted a PR that fixed it: https://github.com/Macaulay2/M2/pull/1782

**Comment by DanGrayson** [comment]
@aadams22 -- hopefully your file on the branch "release-1.17" is now as you wish it.  Let me know if that's not the case.

**Pull request merged**
