### PR TITLE
Updated package RationalPoints2

### PR DESCRIPTION
**Pull request by 8d1h**
Added new functionalities
- Automatically find the splitting field for 0-dimensional ideals;
- Enumeration over number fields of points with bounded height;
- Utility functions related to field extensions.

Currently there are two external dependencies
- Field extensions depend optionally on PARI/GP, which could yield much optimal results;
- Enumeration of points with bounded height over number fields other than `QQ` depends on Sage.

In fact, this package currently runs better than the naive algorithm in Sage, although I started implement it in Sage too, and with the same algorithm Sage seems to run faster.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Here's the error message:
```
../../../../../Macaulay2/m2/debugging.m2:20:6:(1):[14]: error: mutable unexported unset symbol(s) in package RationalPoints2: 'MinimalPrimes'
currentString:1:5-1:18: here is the first use of 'MinimalPrimes'
```

**Comment by 8d1h** [comment]
Thanks for the tip. I didn't pay attention to the error message at all..

**Comment by DanGrayson** [comment]
I should ask the author, Jieao Song, whether these changes are acceptable.  Or is that you?  (Your git id is inscrutable.)

**Comment by mahrud** [comment]
> I should ask the author, Jieao Song, whether these changes are acceptable. Or is that you? (Your git id is inscrutable.)

The package was added by @8d1h only two weeks ago in https://github.com/Macaulay2/M2/pull/1911.

**Comment by DanGrayson** [comment]
> > I should ask the author, Jieao Song, whether these changes are acceptable. Or is that you? (Your git id is inscrutable.)
> 
> The package was added by @8d1h only two weeks ago in #1911.

Thanks!

**Comment by 8d1h** [comment]
> I should ask the author, Jieao Song, whether these changes are acceptable. Or is that you? (Your git id is inscrutable.)

Yes, that's me... Sorry about the confusion.

**Pull request merged**
