### PR TITLE
adding adjunction process for surfaces

### PR DESCRIPTION
**Pull request by foschreyer**
The package AdjunctionForSurface implements the adjunction process of Sommese and Van de Den to compute minimal models of smooth projective surfaces in particular for rational surfaces.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Could you resolve the merge conflicts, please?

**Comment by mikestillman** [comment]
> Could you resolve the merge conflicts, please?

@DanGrayson I tried to fix this, but it says the branch cannot be rebased due to conflicts, and I'm also worried whether normal merge will work.  Can you take a look at this?

I think we need a better way to handle people getting conflicts due to =distributed-files.

**Comment by DanGrayson** [comment]
There are no more merge conflicts, so you were successful!

**Comment by DanGrayson** [comment]
I'll wait for the tests to run..

**Comment by mahrud** [comment]
@DanGrayson the tests were failing because of the spellchecker:
```m2
M2/Macaulay2/packages/AdjunctionForSurfaces.m2:114: defiend ==> defined
M2/Macaulay2/packages/AdjunctionForSurfaces.m2:374: presentaion ==> presentation
M2/Macaulay2/packages/AdjunctionForSurfaces.m2:646: suface ==> surface
M2/Macaulay2/packages/AdjunctionForSurfaces.m2:697: comming ==> coming
```

**Pull request merged**
