### PR TITLE
Delete mixed-cells

### PR DESCRIPTION
**Pull request by antonleykin**
This code (cooked up a long time ago with Anders Jensen) is not used (as far as I know).
It is superseded by the implementation in `gfanlib`.

### CODE REVIEW

**Comment by antonleykin** [comment]
By the way `Macaulay2/kernel/` now is empty --- perhaps we should delete it as well?

**Comment by DanGrayson** [comment]
This pull request is identical to #1651, closing.

**Comment by antonleykin** [comment]
Oops, I guess it was branched from NAG... and the relevant commit was not pushed.
Could you reopen this?
... or should I just bundle this with https://github.com/Macaulay2/M2/pull/1651 ?

**Comment by DanGrayson** [comment]
Let's let #1651 get pulled first, and then you can submit a new pull request.  That will be quickest.

**Comment by DanGrayson** [comment]
Or, if it's independent of #1651, you could branch from master, make the changes there, and submit a pull request now.

**Comment by antonleykin** [comment]
Let's wait --- it is independent, but the successful build was done on top of https://github.com/Macaulay2/M2/pull/1651

**Comment by antonleykin** [comment]
I see `Macaulay2/kernel/mixed-cells` again... 
Could you delete `kernel`?

**Comment by DanGrayson** [comment]
Sure, it seems to be unused ...

(I don't know what you mean by "again".)

**Comment by DanGrayson** [comment]
```sh
gallium$ git log -1 --stat
commit 80542afd250684068ddf775af8596a28d8a03401 (HEAD -> development, origin/development)
Author: Daniel R. Grayson <dan@math.uiuc.edu>
Date:   Mon Sep 20 14:13:02 2021 -0500

    delete M2/Macaulay2/kernel, which is unused
    
    see https://github.com/Macaulay2/M2/pull/1656#issuecomment-922936099

 M2/Macaulay2/kernel/Makefile.in                             |   13 -
 M2/Macaulay2/kernel/mixed-cells/Makefile.files              |    2 -
 M2/Macaulay2/kernel/mixed-cells/README.txt                  |   81 ------
 M2/Macaulay2/kernel/mixed-cells/demicsExamples/cyclic10.dat |  108 --------
 M2/Macaulay2/kernel/mixed-cells/demicsExamples/cyclic11.dat |  129 ---------
 M2/Macaulay2/kernel/mixed-cells/demicsExamples/cyclic4.dat  |   24 --
 M2/Macaulay2/kernel/mixed-cells/demicsExamples/cyclic5.dat  |   33 ---
 M2/Macaulay2/kernel/mixed-cells/demicsExamples/cyclic6.dat  |   44 ---
 M2/Macaulay2/kernel/mixed-cells/demicsExamples/cyclic7.dat  |   57 ----
 M2/Macaulay2/kernel/mixed-cells/demicsExamples/cyclic8.dat  |   72 -----
 M2/Macaulay2/kernel/mixed-cells/demicsExamples/cyclic9.dat  |   89 ------
 M2/Macaulay2/kernel/mixed-cells/src/Doxyfile                | 1254 -------------------------------------------------------------------------------------
 M2/Macaulay2/kernel/mixed-cells/src/allocator.h             |   72 -----
 M2/Macaulay2/kernel/mixed-cells/src/classes.h               | 1910 ---------------------------------------------------------------------------------------------------------------------------------
 M2/Macaulay2/kernel/mixed-cells/src/gmprationals.h          |  184 -------------
 M2/Macaulay2/kernel/mixed-cells/src/mixed-cells.cpp         |  125 ---------
 M2/Macaulay2/kernel/mixed-cells/src/mixed-cells.h           |  858 ----------------------------------------------------------
 M2/Macaulay2/kernel/mixed-cells/src/shortrationals.h        |  141 ----------
 M2/Macaulay2/kernel/mixed-cells/src/types.h                 |  574 ---------------------------------------
 M2/Macaulay2/kernel/mixed-cells/src/vektor.h                |  293 --------------------
 20 files changed, 6063 deletions(-)
```

**Pull request closed without merging**
