### PR TITLE
CMake maintenance

### PR DESCRIPTION
**Pull request by mahrud**

### CODE REVIEW

**Comment by mahrud** [comment]
@DanGrayson assuming tests here and in https://github.com/Macaulay2/homebrew-tap/pull/62 pass, here would be a good place to make a new tag, unless you're waiting for the ncEngine PR first.

**Comment by DanGrayson** [comment]
> @DanGrayson assuming tests here and in [Macaulay2/homebrew-tap#62](https://github.com/Macaulay2/homebrew-tap/pull/62) pass, here would be a good place to make a new tag, unless you're waiting for the ncEngine PR first.

Do you mean a tag for M2?  We haven't decided to bump the version number, so not sure where your suggestion comes from.

**Comment by mahrud** [comment]
> Do you mean a tag for M2? We haven't decided to bump the version number, so not sure where your suggestion comes from.

What do you mean you haven't decided? There have been 118 commits added to the main branch since the v1.17.1 tag, many of which are important bug fixes, such as those pointed out by Greg. As I [said here](https://github.com/Macaulay2/M2/issues/286#issuecomment-766942465), a tag is required to make the brew build reproducible, and there's no cost to making a tag with a minor or patch version bump to `1.17.2`, or `1.17.1.1`.

**Comment by DanGrayson** [comment]
> > Do you mean a tag for M2? We haven't decided to bump the version number, so not sure where your suggestion comes from.
> 
> What do you mean you haven't decided? 

I mean that there has been no decision to bump the version number.  We were considering briefly bumping it in connection with the forthcoming Ubuntu release, but then didn't.

> There have been 118 commits added to the main branch since the v1.17.1 tag, many of which are important bug fixes, such as those pointed out by Greg. As I [said here](https://github.com/Macaulay2/M2/issues/286#issuecomment-766942465), a tag is required to make the brew build reproducible, and there's no cost to making a tag with a minor or patch version bump to `1.17.2`, or `1.17.1.1`.

I'd be happy to bump the version number to 1.7.2 and to add a tag for it if you'd like to make a new brew release.  Is the current head of the master branch a good one to use?  Or should we let a few more fixes get tested and merged in?

**Comment by d-torrance** [comment]
For what it's worth, I'll likely stick with 1.17.1 in Debian/Ubuntu for now even if 1.17.2 is released soon, since we're so close to the freeze for Debian 11.

I can still release PPA packages, though.

**Comment by mahrud** [comment]
> I'd be happy to bump the version number to 1.7.2 and to add a tag for it if you'd like to make a new brew release. Is the current head of the master branch a good one to use? Or should we let a few more fixes get tested and merged in?

No, the main branch has repeatedly failed. After this PR would be best, since it aims to fix some of the issues in the main branch.

Also, just to be sure, you mean `1.17.2`, right? I thought it was a typo [here](https://github.com/Macaulay2/M2/issues/286#issuecomment-766953453), but since it's been three times I want to make sure.

**Comment by mahrud** [comment]
@DanGrayson there is only one test (`capturing check(2, "SpecialFanoFourfolds")`) running out of memory, so this can be merged from my perspective.

**Comment by DanGrayson** [comment]
> Also, just to be sure, you mean `1.17.2`, right?

oops, a typo

**Comment by DanGrayson** [comment]
This is the error:
```
-- capturing check(2, "SpecialFanoFourfolds")                              

 *** out of memory trying to allocate 262208 bytes, exiting ***

 cd /tmp/M2-152572-0/373-rundir/; GC_MAXIMUM_HEAP_SIZE=400M "/home/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Linux-Ubuntu-20.04/bin/M2-binary" -q --int --no-randomize --no-readline --silent --stop --print-width 77 <"/tmp/M2-152572-0/372.m2" >>"/tmp/M2-152572-0/372.tmp"
/tmp/M2-152572-0/372.tmp:0:1: (output file) error: Macaulay2 exited with status code 1
/tmp/M2-152572-0/372.m2:0:1: (input file)
```

Any advice?

**Pull request merged**
