### PR TITLE
Release 1.24.05

### PR DESCRIPTION
**Pull request by d-torrance**
Beginning work on the next release (1.24.05), due to go live on Wednesday, May 15.

TODO:

- [x] Merge in any additional PR's to the `development` branch that come in over the next few days.
- [x] Update prism/vim symbols (once all new packages have been merged in).
- [x] Update Emacs symbols in M2-emacs repository and update submodule commit.
- [x] Update changelog.
- [x] Keep eye on JSAG to see if any new articles are published and certify the corresponding packages.
- [x] Check `Keywords` and `DebuggingMode` for all packages (see https://github.com/Macaulay2/M2/wiki/Internals:-Release-Checklist)

### CODE REVIEW

**Comment by d-torrance** [comment]
I added a bunch of missing keywords to packages.  I did my best, but I wouldn't mind some additional sets of eyes to make sure that nothing was mis-categorized!

**Comment by DanGrayson** [comment]
If you want this to be considered for pulling, turn off the draft status.

**Comment by d-torrance** [comment]
> If you want this to be considered for pulling, turn off the draft status.

Not yet :) Still some work to due before the release.  It'll be ready Wednesday!

**Comment by d-torrance** [comment]
I think the release is ready.  Assuming all the tests pass, I'll add one more commit updating the version number in the changelog, tag it, and then merge this into development.

**Comment by DanGrayson** [comment]
Maybe turn off draft mode.

**Comment by d-torrance** [comment]
> Maybe turn off draft mode.

Not yet!  As I said above, I'll merge this once I add one last commit (with the `release-1.24.05` tag) updating the changelog after all the tests have passed.

**Comment by mikestillman** [comment]
Thanks!  I'm in France right now, have started building development (so not quite the release, but hopefully close enough), on apple M1 macos.  Will see how it goes.  I can also switch to this release branch, try it out.

**Comment by mikestillman** [comment]
In doing `ninja` in build directory (development, on Monterey MacOS, I know, this is old...), I get the following error (with testing set on):

```
[66/607] Linking CXX executable Macaulay2/e/mathicgb/mathicgb-unit-tests
FAILED: Macaulay2/e/mathicgb/mathicgb-unit-tests Macaulay2/e/mathicgb/mathicgb-unit-tests[1]_tests.cmake /Users/mike/src/M2-current-branches/M2-development/M2/BUILD/mike/builds.tmp/cmake-appleclang/Macaulay2/e/mathicgb/mathicgb-unit-tests[1]_tests.cmake 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O2 -g -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -g --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -L/Users/mike/src/M2-current-branches/M2-development/M2/BUILD/mike/builds.tmp/cmake-appleclang/usr-host/lib Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/F4MatrixBuilder.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/F4MatrixReducer.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/MathicIO.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/MonoMonoid.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/PrimeField.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/QuadMatrixBuilder.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/Range.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/Scanner.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/SparseMatrix.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/gb-test.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/ideals.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/mathicgb.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/poly-test.cpp.o Macaulay2/e/mathicgb/CMakeFiles/mathicgb-unit-tests.dir/test/testMain.cpp.o -o Macaulay2/e/mathicgb/mathicgb-unit-tests  -Wl,-rpath,/opt/homebrew/lib  Macaulay2/e/mathicgb/libmathicgb.a  Macaulay2/e/mathic/libmathic.a  Macaulay2/e/memtailor/libmemtailor.a  /opt/homebrew/lib/libtbb.12.11.dylib  usr-host/lib/libgtest_main.a  usr-host/lib/libgtest.a && cd /Users/mike/src/M2-current-branches/M2-development/M2/BUILD/mike/builds.tmp/cmake-appleclang/Macaulay2/e/mathicgb && /opt/homebrew/Cellar/cmake/3.29.0/bin/cmake -D TEST_TARGET=mathicgb-unit-tests -D TEST_EXECUTABLE=/Users/mike/src/M2-current-branches/M2-development/M2/BUILD/mike/builds.tmp/cmake-appleclang/Macaulay2/e/mathicgb/mathicgb-unit-tests -D TEST_EXECUTOR= -D TEST_WORKING_DIR=/Users/mike/src/M2-current-branches/M2-development/M2/BUILD/mike/builds.tmp/cmake-appleclang/Macaulay2/e/mathicgb -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX=unit-tests: -D TEST_SUFFIX= -D TEST_FILTER= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=mathicgb-unit-tests_TESTS -D CTEST_FILE=/Users/mike/src/M2-current-branches/M2-development/M2/BUILD/mike/builds.tmp/cmake-appleclang/Macaulay2/e/mathicgb/mathicgb-unit-tests[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=5 -D TEST_XML_OUTPUT_DIR= -P /opt/homebrew/Cellar/cmake/3.29.0/share/cmake/Modules/GoogleTestAddTests.cmake
CMake Error at /opt/homebrew/Cellar/cmake/3.29.0/share/cmake/Modules/GoogleTestAddTests.cmake:112 (message):
  Error running test executable.

    Path: '/Users/mike/src/M2-current-branches/M2-development/M2/BUILD/mike/builds.tmp/cmake-appleclang/Macaulay2/e/mathicgb/mathicgb-unit-tests'
    Working directory: '/Users/mike/src/M2-current-branches/M2-development/M2/BUILD/mike/builds.tmp/cmake-appleclang/Macaulay2/e/mathicgb'
    Result: Process terminated due to timeout
    Output:

Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.29.0/share/cmake/Modules/GoogleTestAddTests.cmake:226 (gtest_discover_tests_impl)
```

I have poor internet where I am currently, but I would have thought this part would not require web access.

**Comment by mahrud** [comment]
Mike, I don't know about Monterey, but brew built a bottle on an arm-based macOS 14 fine.

Doug, I like the idea of using a pull request to track what needs to be done before the release and also testing it at every stage rather than pushing to pre-master.

**Pull request merged**
