### PR TITLE
fixes #2323

### LINKED ISSUE #2323: ways to use gone from help
with the current development version, after installing Macaulay2Doc, I'm missing the "ways to use" in the help. here's an example:
```
i1 : help matrix

o1 = matrix -- make a matrix
     ***********************

     Synopsis
     ========

       * Optional inputs:
           * Degree => ..., default value null, create a matrix from a doubly-nested list of ring elements or matrices
     The simplest use of this function is to define a matrix by giving a doubly nested list of ring elements.  One may also
     explicitly provide the ring, or give a matrix as a doubly-nested list of matrices.
     +--------------------------------+
     |  i1 : matrix{{1,2,3},{4,5,6}}  |
     |                                |
     |  o1 = | 1 2 3 |                |
     |       | 4 5 6 |                |
     |                                |
     |                2        3      |
     |  o1 : Matrix ZZ  <--- ZZ       |
     +--------------------------------+
     |  i2 : R = QQ[x,y,z];           |
     +--------------------------------+
     |  i3 : matrix{{x,0,2},{1,2,y}}  |
     |                                |
     |  o3 = | x 0 2 |                |
     |       | 1 2 y |                |
     |                                |
     |               2       3        |
     |  o3 : Matrix R  <--- R         |
     +--------------------------------+
     The "map" function provides other methods to define a matrix.

o1 : DIV
```
whereas before I'd have
```
Ways to use matrix :
     ====================

       * "matrix(List)" -- create a matrix from a doubly-nested list of ring elements or matrices
       * "matrix(Matrix)" -- the matrix between generators
       * "matrix(MutableMatrix)" -- make a matrix from a mutable one
       * "matrix(Ring,List)" -- create a matrix from a doubly nested list of ring elements or matrices
       * "matrix(RingFamily,List)" -- see "matrix(Ring,List)" -- create a matrix from a doubly nested list of ring elements or matrices
       * "matrix(Number)" -- see "matrix(RingElement)" -- make a matrix from a ring element
       * "matrix(RingElement)" -- make a matrix from a ring element
       * "matrix(RingMap)" -- the matrix associated to a ring map
       * "matrix(String)" -- make a matrix using classic Macaulay syntax
       * "matrix(Vector)" -- make a matrix

     For the programmer
     ==================

     The object "matrix" is a method function with options.
```

### PR DESCRIPTION
**Pull request by mahrud**

### CODE REVIEW

**Comment by mahrud** [comment]
@DanGrayson I think we need to back-port this to release-1.19 and create a new tag, because unfortunately even some basic functionality isn't working correctly:
```m2
i7 : help needsPackage "Graphs"

o7 = Graphs
     ******

o7 : DIV
```

**Comment by DanGrayson** [comment]
Yes, that needs fixing.  We can up the version number 1.19.1.

**Comment by DanGrayson** [comment]
Take a look at https://github.com/Macaulay2/M2/tree/release-1.19-branch and see if it's okay.

**Comment by mahrud** [comment]
Hmm, I think one of my recent commits has resulted in a rather unfortunate slowdown of `help` for packages, and possibly also types. I'm looking into finding the exact commits to revert.

**Comment by DanGrayson** [comment]
Okay, we can wait ...

**Pull request merged**
