### PR TITLE
Some typos

### PR DESCRIPTION
**Pull request by fchapoton**
suggested by codespell

### CODE REVIEW

**Comment by DanGrayson** [comment]
Thanks!

But could you avoid updating the emacs submodule?

**Comment by fchapoton** [comment]
I am afraid I still do not master how to handle "submodules". Sorry..

**Comment by d-torrance** [comment]
One way to fix it:

```
git checkout origin/development -- M2/Macaulay2/editors/emacs/
```

**Comment by fchapoton** [comment]
hopefully better now. This  business of submodules is source of troubles..

**Comment by DanGrayson** [comment]
Thanks!

**Pull request merged**
