### PR TITLE
adding a prototype of lark file

### PR DESCRIPTION
**Pull request by fchapoton**
in relation with #2889 ; here as a pull request

works a little bit, but needs works by people used to the language

### CODE REVIEW

**Comment by fchapoton** [comment]
how to avoid triggering the Github CI at each push ?

**Comment by fchapoton** [comment]
thanks.
I feel that I am not familiar enough with the M2 script  language to push this tentative much further.

**Comment by mahrud** [comment]
If it's just a single file, not needed or used by anything, perhaps putting it on a wiki page would be more appropriate?

**Comment by fchapoton** [comment]
yes, indeed. is there a wiki for M2 somewhere ?

**Comment by d-torrance** [comment]
> yes, indeed. is there a wiki for M2 somewhere ?

Yes, look up at the top of this page for the "Wiki" tab.  :)  https://github.com/Macaulay2/M2/wiki

**Comment by fchapoton** [comment]
I was not able to upload the file on the wiki. I have just created

https://github.com/Macaulay2/M2/wiki/Lark-Grammar-for-M2-language

Should I copy paste the lark file in this page ?

**Comment by mahrud** [comment]
Since it's currently incomplete, pasting it in a code block on the wiki where others can add to it is one way to go.

However, can I ask what's the intended purpose of this file? If it can be eventually used as code validator or linter for instance, it would be good to include scripts and instructions for how to test it on a small example in a new subdirectory of the [editors](https://github.com/Macaulay2/M2/tree/master/M2/Macaulay2/editors) directory.

Is the goal that this file would be populated and maintained by hand (which would be a daunting task, or automatically by M2?

**Comment by fchapoton** [comment]
I have copy-pasted the macaulay2.lark file in the wiki.

The goal would be to use that in a colde validator, yes. I have added instructions on how to use the grammar to create a parser, see the wiki page.

If done coprrectly, and as long as the language itself does not change, there is not maintenance. But the language may be evolving ?

**Comment by DanGrayson** [comment]
There was a failing test run -- maybe you could fix it by merging your branch with the master branch.

**Comment by mahrud** [comment]
I think this should be closed, since it is now a wiki page: https://github.com/Macaulay2/M2/wiki/Lark-Grammar-for-M2-language

**Comment by fchapoton** [comment]
yes, you can close. Sorry for not being able to push this further.

**Pull request closed without merging**
