### PR TITLE
Update net/info HREF to match html HREF behavior

### PR DESCRIPTION
**Pull request by d-torrance**
Closes: #1777

### CODE REVIEW

**Comment by d-torrance** [comment]
Hrm, I probably shouldn't have overwritten the `mailto` stuff.  Let me add another commit...

**Comment by d-torrance** [comment]
Here is is in action:

```m2
i1 : beginDocumentation()

i2 : HREF{"http://foo.com", "look", SUP "at", SUB "this", "link!"}

         at
o2 = look      link! (see http://foo.com )
           this
```

And now `help` for gold star packages looks fine:

```m2
     Certification a gold star
     =========================

     Version 4.2.2 of this package was accepted for publication in volume 8
     (see https://msp.org/jsag/2018/8-1/ ) of The Journal of Software for
     Algebra and Geometry (see http://j-sag.org/ ) on 11 June 2018, in the
     article A Macaulay2 package for computations with rational maps (see
     https://msp.org/jsag/2018/8-1/p06.xhtml ). That version can be obtained
     from the journal (see https://msp.org/jsag/2018/8-1/jsag-v8-n1-x06-Cremona
     .zip ) or from the Macaulay2 source code repository (see
     http://github.com/Macaulay2/M2/blob/
     2e87a29e4b5b68af1bd8917a9c76d4008ff9fc5b/M2/Macaulay2/packages/Cremona.m2
     ).
```

**Comment by mahrud** [comment]
Whenever you push a commit, Github Actions starts a whole build, and since Github gives each repository a finite number of concurrent builds, it slows subsequent actions. But actions on superseded commits aren't automatically cancelled, which means someone has to manually cancel them. All this to say that it's better to push in groups rather than a commit at a time.

**Comment by d-torrance** [comment]
> Whenever you push a commit, Github Actions starts a whole build, and since Github gives each repository a finite number of concurrent builds, it slows subsequent actions. But actions on superseded commits aren't automatically cancelled, which means someone has to manually cancel them. All this to say that it's better to push in groups rather than a commit at a time.

Yeah, I totally understand, and generally try to do that and push all at once.  I just didn't notice these two things until after I'd pushed...

**Comment by d-torrance** [comment]
Perhaps [this](https://github.com/marketplace/actions/cancel-workflow-action) could be useful to prevent having to deal with that manually?

**Pull request merged**
