### PR TITLE
Restore missing diagrams from MonomialAlgebras package.

### PR DESCRIPTION
**Pull request by d-torrance**
The links have been broken since at least 2015.  Fortunately, copies from
2013 were still available on the Internet Archive Wayback Machine. We
now include them with the source.

This also has the advantage of fixing a privacy-breach-generic Lintian
warning in the Debian package:

> This package creates a potential privacy breach by fetching data from
> an external website at runtime. Please remove these scripts or
> external HTML resources.

> Please replace any scripts, images, or other remote resources with
> non-remote resources. It is preferable to replace them with text and
> links but local copies of the remote resources are also acceptable as
> long as they don't also make calls to remote services. Please ensure
> that the remote resources are suitable for Debian main before making
> local copies of them.

Closes: #402

### CODE REVIEW

**Comment by DanGrayson** [comment]
Thanks!

**Comment by DanGrayson** [comment]
Oops:
```
<p><img src="file:///Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-eigen/usr-dist/common/share/Macaulay2/MonomialAlgebras/projr_25.jpg" alt=""/></p>
<p><img src="file:///Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-eigen/usr-dist/common/share/Macaulay2/MonomialAlgebras/projc_25.jpg" alt=""/></p>
<p><img src="file:///Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-eigen/usr-dist/common/share/Macaulay2/MonomialAlgebras/projd_25.jpg" alt=""/></p>
<p><img src="file:///Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-eigen/usr-dist/common/share/Macaulay2/MonomialAlgebras/EGplane_25.jpg" alt=""/></p>
<p><img src="file:///Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-eigen/usr-dist/common/share/Macaulay2/MonomialAlgebras/EGbar_25.jpg" alt=""/></p>
```

We can't have such absolute paths in the generated documentation.  @d-torrance

**Comment by DanGrayson** [comment]
With `relativizeFilename` and `currentLayout` we should be able to fix that.  Would you like to try it, @d-torrance ?

**Comment by d-torrance** [comment]
Sure!

**Comment by d-torrance** [comment]
It turns out `relativeFilename` was unnecessary, as that already occurs when calling `IMG` in html.m2.  (I realized this when I started getting relative paths like `../../../../../../../../` lol)

**Pull request merged**
