### PR TITLE
Set warnings to be always printed

### PR DESCRIPTION
**Pull request by mahrud**
Before:
```m2
$ ninja install-Msolve
[1/1] Installing package Msolve
 -- making example results for "msolveEliminate"                             -- 1.79479 seconds elapsed
 -- making example results for "msolveSaturate"                              -- 1.6628 seconds elapsed
 -- making example results for "msolveRealSolutions"                         -- 2.01426 seconds elapsed
 -- making example results for "msolveLeadMonomials"                         -- 1.76609 seconds elapsed
 -- making example results for "msolveRUR"                                   -- 1.79487 seconds elapsed
 -- making example results for "msolveGB"                                    -- 1.7215 seconds elapsed
 -- warning: found 6 documentation node(s) not listed as a subnode
```
After:
```m2
$ ninja install-Msolve
[1/1] Installing package Msolve
 -- warning: document: documentation headlines must be less than 100 characters long:
 --   "Macaulay2 interface for msolve; computes real solutions, Groebner basis (in GRevLex), saturations, and elimination ideals."
 -- warning: document: documentation headlines must be less than 100 characters long:
 --   "Uses symbolic methods to compute a certified solution interval for each real solution to a zero dimensional polynomial system."
 -- warning: document: documentation headlines must be less than 100 characters long:
 --   "Uses symbolic methods to compute the rational univariate representation of a zero dimensional polynomial system."
 -- warning: document: documentation headlines must be less than 100 characters long:
 --   "Computes a Groebner basis for the saturation of an ideal by a single polynomial in GrevLex order; only works over a finite field."
 -- warning: found 6 documentation node(s) not listed as a subnode
 -- warning: ("MaybeQuotedTT{msolveEliminate(Ideal,List)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveEliminate(Ideal,List)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveEliminate(Ideal,RingElement)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveEliminate(Ideal,RingElement)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveEliminate(List,Ideal)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveEliminate(List,Ideal)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveEliminate(RingElement,Ideal)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveEliminate(RingElement,Ideal)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveGB(Ideal)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveGB(Ideal)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveLeadMonomials(Ideal)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveLeadMonomials(Ideal)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveRealSolutions(Ideal)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveRealSolutions(Ideal)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveRUR(Ideal)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveRUR(Ideal)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveSaturate(Ideal,RingElement)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
 -- warning: ("MaybeQuotedTT{msolveSaturate(Ideal,RingElement)}", is an instance of an intermediate markup type ,"MaybeQuotedTT", with no qname, appearing in hypertext during validation)
```
My intention is to force users to cut short their documentation headlines, but I'm not sure what those markup type warnings are all about ...

### CODE REVIEW

**Comment by d-torrance** [comment]
I think the `MaybeQuotedTT` warnings are my fault from #3070.  I'll see if I can figure out what's going on.

**Comment by mahrud** [comment]
There are 53630 MaybeQuotedTT warnings and 5652 others XD

Fun fact: out of 6683 examples in M2, the average takes about 2.8s, standard variation is ~5.3, and the top 10 take 15 minutes! I'm thinking of adding a warning for examples taking more than 30s, which is only about 28 examples taking 28 minutes.

Similarly, out of 4008 tests, average is 0.85s, std.var is ~2.8, but only 7 or so take more than 30s. Maybe a warning there isn't a terrible idea.

**Comment by mahrud** [comment]
The example for lowerBound in SumsOfSquares takes more than 4 minutes!

**Comment by mahrud** [comment]
Rebased this on top of the qname changes. Hopefully there should be very few warnings now.

**Review by d-torrance — APPROVED** [review]

**Comment by mahrud** [comment]
Is this good to merge?

**Comment by d-torrance** [comment]
I think so.  I'll go ahead and merge #3376 first since this is on top of that.

**Pull request merged**
