### PR TITLE
delete E1208 lines (ref google groups post)

### PR DESCRIPTION
**Pull request by mkummini**

### CODE REVIEW

**Comment by mkummini** [comment]
delete the phrase "-complete=shellcmd" in the definitions of M2Start, etc where -nargs=0. vim 9 gives an error for these lines.

**Comment by mikestillman** [comment]
@DanGrayson Could you look at this PR?

**Comment by DanGrayson** [comment]
Will do.

**Comment by DanGrayson** [comment]
Mike, there was a failing test, but I don't see the button for rerunning it.

**Comment by mikestillman** [comment]
@DanGrayson Hmm, I don't see how to get them to rerun either...

**Comment by d-torrance** [comment]
Is there a "Re-run all jobs" button for either of you in the upper right-hand corner of https://github.com/Macaulay2/M2/actions/runs/6174378134?  I can't see one, but I do have a button like that on other GitHub repositories where I have higher permissions.

However, I don't think it's necessary to re-run the checks for this PR, since it just touches the vi files.  See https://groups.google.com/g/macaulay2/c/I8FLlHJhp8Y/m/f2Xt9dAhAgAJ for more explanation about the proposed changes.

**Comment by DanGrayson** [comment]
> However, I don't think it's necessary to re-run the checks for this PR, since it just touches the vi files. See https://groups.google.com/g/macaulay2/c/I8FLlHJhp8Y/m/f2Xt9dAhAgAJ for more explanation about the proposed changes.

Then what test failed?

**Pull request merged**
