### PR TITLE
Two packages 

### PR DESCRIPTION
**Pull request by giovannistagliano**

### CODE REVIEW

**Comment by DanGrayson** [comment]
The examples in the package MultipolynomialResultants fail, because pushFwd is undefined.  After fixing it, just commit and push the changes to your branch.

**Comment by giovannistagliano** [comment]
I do not understand, I don't get any error or warning (on M2 1.8.2).
pushFwd is defined in the package "PushForward".

**Comment by DanGrayson** [comment]
Sorry, it's missing a method definition:
```
stdio:2:6:(3): error: no method found for applying pushFwd to:
     argument 1 :  | (-a_1^2+4a_0a_2)/2a_0 | (of class Matrix)
     argument 2 :      frac ZZ[a , a , a ][x ]             . (of class RingMap)
                                0   1   2   0              .
                   map(-----------------------,frac ZZ[a , .
                              2a x  + a                 0  .
                                0 0    1                   .
```
Here are the methods provided by PushForward:
```
i5 : methods pushFwd

o5 = {(pushFwd, RingMap)           }
     {(pushFwd, RingMap, Module)   }
     {(pushFwd, RingMap, ModuleMap)}

o5 : VerticalList
```

**Comment by DanGrayson** [comment]
I looked into it more deeply:  It turns out that the package PushForward has changed since 1.8.2:
```
Macaulay2, version 1.8.2
with packages: ConwayPolynomials, Elimination, IntegralClosure, LLLBases,
               PrimaryDecomposition, ReesAlgebra, TangentCone

i1 : loadPackage "PushForward"

o1 = PushForward

o1 : Package

i2 : methods pushFwd

o2 = {(pushFwd, Module, RingMap)   }
     {(pushFwd, ModuleMap, RingMap)}
     {(pushFwd, RingMap)           }

o2 : VerticalList

i3 : 

Process M2 finished

+ /Users/dan/src/M2/M2-Macaulay2/M2/BUILD/dan/builds.tmp/mac64-master-production/M2 --no-readline -q --print-width 192
Macaulay2, version 1.8.2.1
with packages: ConwayPolynomials, Elimination, IntegralClosure, LLLBases, PrimaryDecomposition, ReesAlgebra, TangentCone

i1 : loadPackage "PushForward"

o1 = PushForward

o1 : Package

i2 : methods pushFwd

o2 = {(pushFwd, RingMap)           }
     {(pushFwd, RingMap, Module)   }
     {(pushFwd, RingMap, ModuleMap)}
```

Could you test your package with the latest version?  It seems to be a simple matter of
changing the order of arguments to pushFwd.

**Comment by giovannistagliano** [comment]
I do not know how to install a newer version of M2... But probably you are right, It should be enough to change the order of arguments. I am using (pushFwd, ModuleMap, RingMap)
Thank you for your time!

**Comment by DanGrayson** [comment]
You don't have to install a newer version of M2, you just have to use the
latest version of the
package PushForward.  It's already on your disk drive, in your clone of the
Macaulay2 repository,
on the master branch.

**Comment by giovannistagliano** [comment]
Just now I tested my package with the new version of PushForward. It does not work in any way!! I hope to resolve in time.

**Comment by DanGrayson** [comment]
Perhaps @kschwede can give advice, if you need it, since he submitted the changes to PushForward:

```
commit bd1b4b2ffd54e669931ae91f3132cef9e9ffe860
Author: Karl Schwede <kschwede@gmail.com>
Date:   Tue Nov 3 15:04:38 2015 -0700

    Updated PushForward.m2 with Claudiu's changes.  Note that the order of (f, module) has been switched to match the previous pushForward function.
    
    Updated Pullback.m2 to work with the revised order.
    
    Updated Schubert.m2 to work with the revised pushFwd.

```

**Comment by giovannistagliano** [comment]
Actually it was a simple matter of interchange the arguments, and of correcting a test comparing strings instead of polynomials. I hope it works well with you.

**Comment by DanGrayson** [comment]
All is well, thanks!

**Pull request merged**
