### PR TITLE
Codespell linter

### PR DESCRIPTION
**Pull request by fchapoton**
let's try and see if this is doable

### CODE REVIEW

**Comment by fchapoton** [comment]
the linter was not triggered, no idea what to do for that

**Comment by d-torrance** [comment]
I think it's because it hasn't been merged into the `development` branch yet.  If that happens, then future pull requests should trigger it.

**Comment by fchapoton** [comment]
but it's not ready to go... even by restricting to packages, many more words should be excluded

**Comment by mahrud** [comment]
You should test this on a personal fork first, where you can control more about the workflow.

**Comment by fchapoton** [comment]
Oh, nice, the linter is now running here. Hopefully, it should be green

**Comment by fchapoton** [comment]
now the linter is green, but for some reason the other (long) checks were cancelled

**Comment by mahrud** [comment]
Suppose there are typo's in a pull request, what does this spellcheck workflow do? Does it fail on the first typo, or list them all? Does it easily point out where it is so the PR author can fix it?

**Comment by fchapoton** [comment]
Here is a sample of what the linter says:

```
../../M2/M2/Macaulay2/m2/typicalvalues.m2:89: openIn ==> opening
../../M2/M2/Macaulay2/m2/typicalvalues.m2:89: openIn ==> opening
../../M2/M2/Macaulay2/m2/startup.m2.in:180: Hart ==> Heart, Harm
../../M2/M2/Macaulay2/m2/book.m2:91: crossReference ==> cross-reference
../../M2/M2/Macaulay2/m2/book.m2:106: crossreferences ==> cross-references
../../M2/M2/Macaulay2/m2/book.m2:111: crossReference ==> cross-reference
../../M2/M2/Macaulay2/m2/methods.m2:88: overriden ==> overridden
../../M2/M2/Macaulay2/m2/methods.m2:120: overriden ==> overridden
../../M2/M2/Macaulay2/m2/basictests/D01.m2:4: nam ==> name
../../M2/M2/Macaulay2/m2/basictests/D01.m2:4: nam ==> name
../../M2/M2/Macaulay2/m2/basictests/D01.m2:6: nam ==> name
../../M2/M2/Macaulay2/m2/basictests/D01.m2:6: nam ==> name

```

**Comment by mahrud** [comment]
> The linter (takes around one minute) will list all failures, and for each one will explain in which file and at which line it happens. It also suggests the possible fixes. In case of disagreement of the author with the linter, there remains the possibility to add an excluded word in `.codespell_ignore`

Could you document this somewhere in the wiki for future contributors?

**Comment by fchapoton** [comment]
where is the wiki ? is this http://wiki.macaulay2.com/Macaulay2/ ? should I request an account there ?

**Comment by mahrud** [comment]
Somewhere here: https://github.com/Macaulay2/M2/wiki
Or @DanGrayson might have a better idea.

**Comment by fchapoton** [comment]
I have added something in https://github.com/Macaulay2/M2/wiki/Git-for-Macaulay2-Contributors

**Pull request merged**
