### PR TITLE
StatePolytope updates

### PR DESCRIPTION
**Pull request by d-torrance**
This is a short followup to #1368, specifically dealing with the `StatePolytope` package.

It calls gfan for the the `initialIdeals` method, which is used by its other methods (which call polymake).  We update it to use the `gfanInterface` package, and therefore, indirectly, the new `loadProgram` and `runProgram` methods so it can use any gfan, either installed by Macaulay2 or already present on the system.

We also:
* Rename `statePolytope` to `polymakeStatePolytope` to avoid an error (see also #507).
* Fix the failing test from #1173.
* Update the cached examples.

### CODE REVIEW

**Comment by DanGrayson** [comment]
@d-torrance -- how could changing the name of a function prevent an error?

**Comment by mahrud** [comment]
Perhaps in light of #507, this package should be removed from distributed packages?

**Comment by mahrud** [comment]
Also, are we not concerned about involving package authors in changes to their packages anymore?

**Comment by DanGrayson** [comment]
> Also, are we not concerned about involving package authors in changes to their packages anymore?

We are.  That's why I've (already) asked the author to review this.

**Comment by DanGrayson** [comment]
> Perhaps in light of #507, this package should be removed from distributed packages?

That would premature, since the question in #507 has not been answered.

**Comment by dswinarski** [comment]
Thanks everyone for your comments on this--I'll review it this week.  I
predict that it may indeed be time to remove this package from the
distributed packages, but I would like to test a few examples using the
Polyhedra package first to see if there is any major difference in
performance anymore.  Many years ago, there would have been, but I suspect
that gap may have closed with recent work on Polyhedra.

Best,

Dave
*_______________________________________*

*David Swinarski, Ph.D.*
Associate Dean, Faculty of Arts and Sciences
Fordham University
718.817.3034

dswinarski@fordham.edu

(he/him/his)
*_______________________________________*

**Comment by d-torrance** [comment]
> @d-torrance -- how could changing the name of a function prevent an error?

`Polyhedra` also has a `statePolytope` method, and it's exported by `gfanInterface`.  So if we try to define a new `statePolytope` method, we get an error:

    error: assignment to protected built-in global variable 'statePolytope'

**Comment by DanGrayson** [comment]
> > @d-torrance -- how could changing the name of a function prevent an error?
> 
> `Polyhedra` also has a `statePolytope` method, and it's exported by `gfanInterface`. So if we try to define a new `statePolytope` method, we get an error:
> 
> ```
> error: assignment to protected built-in global variable 'statePolytope'
> ```

Why not just not try to define a new `statePolytope` function?  (That's the error here.)

**Comment by d-torrance** [comment]
> Why not just not try to define a new `statePolytope` function? (That's the error here.)

That was my goal.  By renaming `statePolytope` to something else, then we wouldn't be trying to define it a second time.

**Comment by DanGrayson** [comment]
I don't get any errors when I build Macaulay2, so we aren't trying to define it a second time.

**Comment by d-torrance** [comment]
> I don't get any errors when I build Macaulay2, so we aren't trying to define it a second time.

Not currently, no.  But this PR adds the following line:
https://github.com/Macaulay2/M2/blob/7785cd656d011450a49f8df49e14c42792de9cbe/M2/Macaulay2/packages/StatePolytope.m2#L16

If I try to load the package with that line added, I get:
```m2
i1 : loadPackage("StatePolytope",
         FileName => "~/src/macaulay2/M2/M2/Macaulay2/packages/StatePolytope.m2")
../../StatePolytope.m2:126:15:(2):[7]: error: assignment to protected built-in global variable 'statePolytope'
```

**Comment by DanGrayson** [comment]
Ah, finally I catch on, thanks!  If Dave likes the name the way it is, then inside the package you could refer to the shadowed symbol by its synonym, `StatePolytope$statePolytope`.

**Comment by d-torrance** [comment]
I just noticed a further complication.  This package requires polymake < 4.0, as the command line interface changed with the version bump:
https://polymake.org/doku.php/user_guide/tutorials/legacy#command_line

I tested this pull request initially in Ubuntu 18.04, which has polymake 3.2, and everything worked fine.  But in Debian unstable, which has polymake 4.0, it fails:

```m2
i8 : R=QQ[a..d];

i9 : I=ideal(a*c-b^2,a*d-b*c,b*d-c^2);

o9 : Ideal of R

i10 : L = {{9, 6, 6, 9}, {9, 3, 12, 6}, {7, 5, 14, 4}, {5, 8, 14, 3}, {3, 12, 12,3}, {6, 12, 3, 9}, {4, 14, 5, 7}, {3, 14, 8, 5}};

i11 : statePolytope(3, I)
----------------------------------------------------------------------------
This is the Gfan program for computing Groebner fans and tropical varieties.
     Webpage: http://home.math.au.dk/jensen/software/gfan/gfan.html
----------------------------------------------------------------------------

To run a Gfan subcommand do for example:
	gfan _groebnerfan
in your shell and type in your input, for example:
	Q[x,y]{x^2-y-1,y^2-xy-2/3}

Options for controlling the main program:
 _list             List all subcommands.
 _version          Display version of gfan and compiled libraries.
 _test             Run selftest. Use --suite to specify test suite.
                   Creates/overwrites files in current folder.
 _documentation    Generate .tex file for manual.

General useful options for subcommands:
 --help            Print the help text associated to the subcommand.
 --log1            Set the log level for comments written to stderr while computing (--log2,--log3).
 --stdin FILENAME  Use the specified file as input for the program rather than reading from stdin.
 --stdout FILENAME Use the specified file as output for the program rather than writing to stdout.

The command "gfan" is deprecate for computing all Groebner bases of an ideal.
Please use subcommand "gfan _bases" instead.
To keep compatibility with older versions, gfan _bases is awaiting input.
<Ctrl>-D to end.
usage: polymake [-dv] [-A|-a <application>]
                [--reconfigure] [--config-path PATH ... | --no-config | --ignore-config]
                [ --script | --iscript <script_file> arg ... ] | script_file | 'one-liner' |
                - | [ --connect SOCKETFILE | HOST:PORT ] |
                --touch <file> ... | --help | --version
stdio:11:1:(3): error: close: process exited with code 256
```

**Comment by DanGrayson** [comment]
The interaction you posted seems to be with gfan, not polymake.

If we want to distribute M2 on both systems (once Debian unstable is incorporated into a release), we might have to arrange for some packages to run polymake both ways.  That'll be a pain.

How many packages are running polymake themselves?

**Comment by d-torrance** [comment]
> The interaction you posted seems to be with gfan, not polymake.

It interacts with both.  First it calls gfan to get the initial ideals, and then it calls polymake to find the vertices of a polytope.   gfan was just a lot more verbose in the example above.  But polymake is there -- check out the last few lines.

> If we want to distribute M2 on both systems (once Debian unstable is incorporated into a release), we might have to arrange for some packages to run polymake both ways. That'll be a pain.

Fortunately, the new command-line interface was introduced in 3.x (or maybe even earlier?).  They carried compatibility with both for a while and dropped the old one in 4.0.

I've added a new commit porting `StatePolytope` to the new interface. It also uses `loadProgram` and `runProgram` now, too.

> How many packages are running polymake themselves?

Certainly `Polymake`, but glancing at it, it also appears to use the old interface.  I imagine a better solution in the future would be to port it to the new interface and have `StatePolytope` import it instead of calling polymake directly.

**Comment by d-torrance** [comment]
I also wrote a patch for the Debian package that updates `StatePolytope` to use modern gfan and polymake in a more minimal way, i.e., no importing `gfanInterface` or calling `loadProgram`/`runProgram`:
https://salsa.debian.org/science-team/macaulay2/-/blob/master/debian/patches/fix-state-polytope.patch

**Comment by d-torrance** [comment]
Rebased this on top of `development` since it's affected by the `loadProgram` → `findProgram` change from #1389.

**Comment by d-torrance** [comment]
Just added a new commit adding the `--no-config` argument to polymake.  Without it, polymake tries to create `~/.polymake`, which we may not have permission to do.

**Comment by DanGrayson** [comment]
@dswinarski -- did this fall off your radar?

**Comment by DanGrayson** [comment]
@dswinarski -- did this fall off your radar?

**Comment by d-torrance** [comment]
I've rebased this branch on top of `development` and added a new commit adding support for the `OptionalComponentsPresent` option.

**Comment by DanGrayson** [comment]
@dswinarski -- did this fall off your radar?

**Comment by dswinarski** [comment]
Yes, sorry. I'll invest some time in it this weekend.

Best,

Dave
*_______________________________________*

*David Swinarski, Ph.D.*
Associate Dean, Faculty of Arts and Sciences
Fordham University
718.817.3034

dswinarski@fordham.edu

(he/him/his)
*_______________________________________*

**Comment by DanGrayson** [comment]
@dswinarski  --  why don't I go ahead and pull this so it gets into 1.17?  You can always look at it later.

Or take a look during the next week or so.

**Pull request merged**
