### PR TITLE
Add new package

### PR DESCRIPTION
**Pull request by eisenbud**
Finished for now editing CompleteIntersectionResolutions. If Mike puts in my code for creating elements of Hom from homomorphisms, then that should be subtracted.

### CODE REVIEW

**Comment by DanGrayson** [comment]
David, could you give me a sentence or two for the "changes, 1.8"
documentation node, if the
changes are substantial enough to advertise?

**Comment by DanGrayson** [comment]
I had to disable one of your tests, because it didn't work.  (I also had to fix 4 others so they would work.)  Take a look at the one I disabled and see how it can be made to work.

**Comment by eisenbud** [comment]
Humph!  — your program! They *all* worked on my machine when I sent it off!

Anyway, thanks for fixing those, I’ll take a look at the last.

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics, University of California, Berkeley
www.msri.org/~de

**Comment by DanGrayson** [comment]
It's impossible that they worked on your machine.  I bet you ran them  manually, line by line, rather than running them with ```  check "CompleteIntersectionResolutions" ```

**Comment by DanGrayson** [comment]
... and the only reason they worked is because of your init file, which probably defines ```kk```

**Comment by eisenbud** [comment]
I ran them with “check” — and it took me quite a few fixes. But you’re right about “kk”.

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics, University of California, Berkeley
www.msri.org/~de

**Comment by DanGrayson** [comment]
Strange - if you run with "check", then the test M2 session would not load your init file, since it's run with the "-q" option, unless you specify ```UserMode=>true```.

**Comment by eisenbud** [comment]
Dear Dan,

That is odd. The other test that failed was also because of a special definition of Matrix^Array in my init file — so somehow that “check" mechanism doesn’t seem to be working.

Anyhow, I fixed it, ran “check”, all seems to work fine.

I **think** I successfully made a “pull” request. 

I must say I find the git lingo, such as “checkout” for changing from one branch to another, unintuitive, though I think I’m beginning to use it more correctly.

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics, University of California, Berkeley
www.msri.org/~de

**Comment by eisenbud** [comment]
Possible text for the “Changes” file:

The package “CompleteIntersectionResolutions” implements a number of old and new ideas about minimal resolutions over a complete intersection developed by Eisenbud-Peeva, Avramov-Jorgensen, Eisenbud-Peeva-Schreyer, and Burke-Eisenbud-Schreyer. Let S = k[x_1..x_n] be a polynomial ring, ff a codimension c regular sequence of homogeneous forms of the same degree, and R = S/(ff). It contains:

1) routines to compute the structure of “higher matrix factorization” on a “high” R-syzygy M — one for which the modules Ext_R^even(M,k) and Ext_R^odd(M,k) have negative regularity over the ring of CI operators. There are also routines to extract various information from the higher matrix factorization.

2) routines that implement the reconstruction algorithm of Avramov and Jorgensen that constructs modules M having (certain kinds of) specified Ext-modules.

3) routines to test of a conjecture of Eisenbud about the vanishing of certain local cohomology of Ext-modules, implementing the map from a module to its saturation.

4) routines to compute the higher homotopies for ff on an S-free resolution of an S-module M annihilated by ff, and understanding the structure of module over an exterior algebra, determined by the ff-homotopies on a resolution of M, on Tor^S(M,N) and Ext_S(M,N), when M and N are S-modules annihilated by ff. These routines led to conjectures that were later proven, and will appear in a work-in-progress of Eisenbud, Peeva and Schreyer.

5) routines to compute Hom in the stable category of Cohen-Macaulay R-modules, and test for stable triviality. This is used in understanding possible obstructions to commutativity of CI-operators. 


David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics, University of California, Berkeley
www.msri.org/~de

**Comment by DanGrayson** [comment]
Thanks, I've used it.

**Comment by DanGrayson** [comment]
I take it back : the ```-q``` option is used during ```check``` only if it was used on the command line that you used to start M2.  Hmm....

**Pull request merged**
