### PR TITLE
package PhylogeneticTrees.m2

### PR DESCRIPTION
**Pull request by kroner**
Beginning at the MRC on algebraic statistics this past summer in Snowbird, our team wrote a package to compute the invariants of phylogenetic tree models with several different algorithms.  We're planning to submit the package to JSAG shortly.

The team consists of Hector Banos, Nathaniel Bushek, Ruth Davidson, Elizabeth Gross, Pamela Harris, Robert Krone, Colby Long, AJ Stewart, Robert Walker.

### CODE REVIEW

**Comment by DanGrayson** [comment]
This package doesn't load:
```
Macaulay2, version 1.9.2
with packages: ConwayPolynomials, Elimination, IntegralClosure, LLLBases,
               PrimaryDecomposition, ReesAlgebra, TangentCone

i1 : installPackage "PhylogeneticTrees"
--loading configuration for package "Graphs" from file /Users/dan/Library/Application Support/Macaulay2/init-Graphs.m2
--loading configuration for package "FourTiTwo" from file /Users/dan/Library/Application Support/Macaulay2/init-FourTiTwo.m2
--loading configuration for package "Posets" from file /Users/dan/Library/Application Support/Macaulay2/init-Posets.m2
Macaulay2/packages/PhylogeneticTrees.m2:2251:6:(0):[10]: error: EOF in string /// ... /// beginning here
stdio:1:1:(3): --backtrace: parse error--
```

**Comment by kroner** [comment]
Sorry, somehow an extra "/" got added to a "///" that broke things.  It should load now.

**Comment by DanGrayson** [comment]
I get two errors when installing the package.  One of them is this one:
```
-- -*- M2-comint -*- {* hash: 1324183505 *}

i1 : T = leafTree(4,{{0,1}})

o1 = {{0, 1, 2, 3}, {set {0, 1}, set {0}, set {1}, set {2}, set {3}}}

o1 : LeafTree

i2 : P = edgeCut(T, set {0,1});
stdio:2:5:(3): error: no method found for applying edgeCut to:
     argument 1 :  {{0, 1, 2, 3}, {set {0, 1}, set {0}, se. (of class LeafTree)
     argument 2 :  set {0, 1} (of class Set)
```

The package name should be added to the list in `=distributed-packages`.

One of the tests files with this output:
```
-- -*- M2-comint -*- {* hash: 434041771 *}

i1 : --/home2/dan/src/M2/M2/Macaulay2/packages/PhylogeneticTrees.m2:1803: location of test code
     
     assert( (2+2) === 5 )
stdio:3:1:(3): error: assertion failed
```
How could it ever work?

**Comment by DanGrayson** [comment]
@kroner or @antonleykin ?

**Comment by DanGrayson** [comment]
PS: What about also adding the name of this package to the list of packages?  (... in addition to making it work.)

**Comment by antonleykin** [comment]
I was not a part of this one...

**Comment by DanGrayson** [comment]
@kroner Any comments on repairing this pull request?

**Comment by kroner** [comment]
@DanGrayson Sorry it took me some time to address this.  Those bugs should be fixed and the examples and tests run now for me. I also added it to =distributed-packages.

I was neglecting to uninstallPackage before installing or run the check function, but now hopefully I'm actually testing everything.

**Comment by DanGrayson** [comment]
Thanks!

**Pull request merged**
