### PR TITLE
fix bug in Triangulations, caused by version change of Topcom. 

### PR DESCRIPTION
**Pull request by mikestillman**
Tests added to check this (`flips`).  Also added my most recent BUILD Makefile

### CODE REVIEW

**Comment by mikestillman** [comment]
I have started fixing documentation and tests for the pacage `Triangulations`.  But I don't have that quite ready yet.

**Comment by d-torrance** [comment]
@mikestillman - is this ready to merge, or are the Triangulations updates you mentioned planned for this PR, too?

Also, have you seen #3529? Is that ok to merge?

**Comment by mikestillman** [comment]
I don't think I can have the Triangulations changes ready for this release, sadly.

**Comment by d-torrance** [comment]
Ok, I'll go ahead and merge this.

**Pull request merged**
