### PR TITLE
Address git issue #2108

### LINKED ISSUE #2108: minimalBetti crash
This crash is occurring on the github workflow that builds brew bottles and is blocking it. The crash itself is in the minimalBetti example but I could also reproduce it myself on Linux:
```m2
[mahrud@noether build]$ ./M2
Macaulay2, version 1.17.2.1
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems,
               LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra,
               Saturation, TangentCone

i1 : R = ZZ/3[x]; minimalBetti ideal x
-- SIGSEGV
-* stack trace, pid: 1917263
 0# stack_trace(std::ostream&, bool) at ../../Macaulay2/bin/main.cpp:124
 1# segv_handler at ../../Macaulay2/bin/main.cpp:240
 2# 0x00007F1FB4BA5860 in /lib64/libc.so.6
 3# free in /lib64/libc.so.6
 4# __gnu_cxx::new_allocator<int>::deallocate(int*, unsigned long) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/ext/new_allocator.h:138
 5# std::allocator_traits<std::allocator<int> >::deallocate(std::allocator<int>&, int*, unsigned long) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/alloc_traits.h:492
 6# std::_Vector_base<int, std::allocator<int> >::_M_deallocate(int*, unsigned long) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_vector.h:355
 7# std::_Vector_base<int, std::allocator<int> >::~_Vector_base() at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_vector.h:335
 8# std::vector<int, std::allocator<int> >::~vector() at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_vector.h:683
 9# ResF4toM2Interface::from_M2_vec(ResPolyRing const&, FreeModule const*, vecterm*, poly&) at ../../Macaulay2/e/schreyer-resolution/res-f4-m2-interface.cpp:250
10# createF4Res(Matrix const*, int, int) at ../../Macaulay2/e/schreyer-resolution/res-f4-computation.cpp:143
11# ResolutionComputation::choose_res(Matrix const*, char, int, char, int, int, int) at ../../Macaulay2/e/comp-res.cpp:136
12# IM2_res_make at ../../Macaulay2/e/interface/groebner.cpp:122
13# interface_rawResolution at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/interface.dd:3604
14# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1297
15# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
16# evaluate_applyFCE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:742
17# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:895
18# method1 at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors5.d:668
19# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:891
20# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:897
21# method1234 at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors5.d:734
22# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1306
23# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
24# evaluate_storeInHashTable at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:61
25# assignelemfun at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:133
26# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1373
27# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
28# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1411
29# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
30# evaluate_storeInHashTable at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:61
31# assignelemfun at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:133
32# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1373
33# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
34# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1358
35# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
36# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1329
37# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
38# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1411
39# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
40# evaluate_applyFCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:522
41# evaluate_applyFCC at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:572
42# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1293
43# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
44# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1357
45# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
46# evaluate_applyFCCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:823
47# evaluate_applyFCC at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:562
48# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1293
49# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
50# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1401
51# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
52# evaluate_applyFCCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:832
53# evaluate_applyFCC at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:562
54# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1293
55# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
56# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1329
57# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
58# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1396
59# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
60# scan_1 at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors3.d:1918
61# scan_4 at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors3.d:2218
62# scan_5 at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors3.d:2228
63# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1297
64# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
65# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1357
66# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
67# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1404
68# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
69# evaluate_applyFCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:522
70# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:894
71# iteratedApply at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors3.d:2285
72# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1297
73# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
74# evaluate_applyFCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:465
75# evaluate_applyES at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:882
76# method1234p at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors5.d:784
77# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1301
78# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
79# evaluate_applyFCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:465
80# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:894
81# iteratedApply at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors3.d:2285
82# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1297
83# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
84# evaluate_applyFCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:465
85# evaluate_applyFCCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:779
86# evaluate_applyFCC at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:562
87# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1304
88# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
89# evaluate_applyFCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:522
90# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:894
91# iteratedApply at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors3.d:2285
92# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1297
93# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
94# evaluate_applyFCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:465
95# evaluate_applyES at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:882
96# method1234p at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors5.d:781
97# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1301
98# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
99# evaluate_applyFCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:465
100# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:894
101# iteratedApply at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors3.d:2285
102# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1297
103# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
104# evaluate_applyFCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:465
105# evaluate_applyFCCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:779
106# evaluate_applyFCC at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:562
107# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1304
108# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
109# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1398
110# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
111# evaluate_applyFCCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:832
112# evaluate_applyFCC at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:562
113# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1293
114# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
115# evaluate_evalSequence at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:420
116# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1417
117# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
118# evaluate_applyFCC at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:678
119# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1304
120# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
121# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1329
122# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
123# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1411
124# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
125# evaluate_applyFCE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:742
126# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:895
127# applyEOE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors5.d:704
128# method1234o at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors5.d:768
129# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1301
130# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
131# evaluate_applyFCE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:742
132# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:895
133# iteratedApply at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors3.d:2285
134# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1297
135# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
136# evaluate_applyFCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:465
137# evaluate_applyFCCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:779
138# evaluate_applyFCC at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:562
139# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1304
140# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
141# evaluate_applyFCE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:742
142# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:895
143# applyEOE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors5.d:704
144# method1234o at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors5.d:768
145# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1301
146# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
147# evaluate_applyFCE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:742
148# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:895
149# iteratedApply at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors3.d:2285
150# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1297
151# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
152# evaluate_applyFCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:465
153# evaluate_applyFCCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:779
154# evaluate_applyFCC at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:562
155# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1304
156# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
157# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1357
158# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
159# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1329
160# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
161# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1396
162# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
163# evaluate_applyFCE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:742
164# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:895
165# iteratedApply at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors3.d:2285
166# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1297
167# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
168# evaluate_applyFCS at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:465
169# evaluate_applyES at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:882
170# method1234p at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors5.d:797
171# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1301
172# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
173# evaluate_applyFCE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:742
174# evaluate_applyEE at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:895
175# iteratedApply at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/actors3.d:2285
176# evaluate_applyFCC at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:662
177# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1304
178# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
179# evaluate_evalexcept at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1437
180# readeval4(parse_TokenFile_struct*, char, parse_Dictionary_struct*, char, char, char) at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/interp.dd:178
181# readeval3(parse_TokenFile_struct*, char, parse_DictionaryClosure_struct*, char, char, char) at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/interp.dd:270
182# loadprint(M2_string_struct*, parse_DictionaryClosure_struct*, char) at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/interp.dd:343
183# commandInterpreter_2(tagged_union*) at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/interp.dd:458
184# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1297
185# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
186# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1329
187# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
188# evaluate_evalraw at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1407
189# evaluate_eval at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1257
190# evaluate_evalexcept at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/evaluate.d:1437
191# readeval4(parse_TokenFile_struct*, char, parse_Dictionary_struct*, char, char, char) at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/interp.dd:178
192# readeval3(parse_TokenFile_struct*, char, parse_DictionaryClosure_struct*, char, char, char) at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/interp.dd:270
193# readeval(parse_TokenFile_struct*, char, char) at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/interp.dd:282
194# interp_process at /home/mahrud/Projects/M2/M2/M2/Macaulay2/d/interp.dd:606
195# interpFunc(ArgCell*) at ../../Macaulay2/bin/main.cpp:193
196# ThreadTask::run(SupervisorThread*) at ../../Macaulay2/system/supervisor.cpp:377
197# SupervisorThread::threadEntryPoint() at ../../Macaulay2/system/supervisor.cpp:426
198# SupervisorThread::threadEntryPoint(void*) at ../../Macaulay2/system/supervisor.hpp:100
199# GC_inner_start_routine in /home/linuxbrew/.linuxbrew/opt/bdw-gc/lib/libgc.so.1
200# GC_call_with_stack_base in /home/linuxbrew/.linuxbrew/opt/bdw-gc/lib/libgc.so.1
201# start_thread in /lib64/libpthread.so.0
202# __clone in /lib64/libc.so.6
-- end stack trace *-
```

cc: @mikestillman seems to be related to the changes in `e/schreyer-resolution`.

### PR DESCRIPTION
**Pull request by mikestillman**
This pull request renames some classes to address (and hopefully solve) git issue #2108.  It also places a couple of types into anonymous namespaces.

### CODE REVIEW

**Comment by mahrud** [comment]
@DanGrayson could you merge this directly into release-1.18-branch, so that a future release-1.18 tag will only have one commit more than the other releases?

**Comment by DanGrayson** [comment]
> @DanGrayson could you merge this directly into release-1.18-branch, so that a future release-1.18 tag will only have one commit more than the other releases?

Sure thing, done.

**Comment by mahrud** [comment]
Ah, that did not have the desired effect ... all the python changes ended up in that branch! I thought this PR was based on release-1.18-branch, not development

**Comment by mahrud** [comment]
For future reference, I think it's easier to merge in development, then backport (via git cherry-pick) to the release branch.

**Comment by DanGrayson** [comment]
> Ah, that did not have the desired effect ... all the python changes ended up in that branch! I thought this PR was based on release-1.18-branch, not development

Okay, I've forcefully pushed the former head to `release-1.18`.

**Comment by DanGrayson** [comment]
I could now cherry pick commit 0e9358a ...

**Comment by mahrud** [comment]
Thanks

**Comment by DanGrayson** [comment]
Done.

**Pull request merged**
