### PR TITLE
Minor update to MultiprojectiveVarieties

### PR DESCRIPTION
**Pull request by giovannistagliano**

### CODE REVIEW

**Comment by giovannistagliano** [comment]
I'm done with the updates. I hope they can be included with the 1.17.

**Comment by DanGrayson** [comment]
> I'm done with the updates. I hope they can be included with the 1.17.

okay

**Comment by DanGrayson** [comment]
We're getting a crash unrelated to the current pull request:
```make
make[4]: Entering directory '/home/runner/work/M2/M2/M2/BUILD/build/Macaulay2/tests/ComputationsBook/monomialIdeals'
<../../../../../../Macaulay2/tests/ComputationsBook/monomialIdeals/test.out.expected sed -f ../../../../../../Macaulay2/tests/ComputationsBook/monomialIdeals/../patterns -f ../../../../../../Macaulay2/tests/ComputationsBook/monomialIdeals/patterns >test.out.expected.trim
ulimit -t 1200 ; ulimit -v 1600000 ; ulimit -m 800000 ; ulimit -s 8192 ; time nice -18 /home/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Linux-Ubuntu-18.04/bin/M2 --stop -q -e 'path = join({"./","../../../../../../Macaulay2/tests/ComputationsBook/monomialIdeals/"},path)' --print-width 0 -e 'input "../../../../../../Macaulay2/tests/ComputationsBook/monomialIdeals/test.m2"' -e "exit 0" >test.out.tmp
Macaulay2, version 1.17
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra, Saturation, TangentCone
-- SIGSEGV
-* stack trace, pid: 27008
 0# stack_trace(std::ostream&, bool) at ../../../../Macaulay2/d/main.cpp:124
 1# segv_handler at ../../../../Macaulay2/d/main.cpp:241
 2# 0x00007FD38E662040 in /lib/x86_64-linux-gnu/libc.so.6
 3# MonomialIdeal::sat(MonomialIdeal const&) const at ../../../../Macaulay2/e/monideal.cpp:787
 4# rawSaturateMonomialIdeal2 at ../../../../Macaulay2/e/interface/monomial-ideal.cpp:189
 5# interface_rawSaturate at ../../../../Macaulay2/d/interface.dd:303
 6# evaluate_evalraw at ../../../../Macaulay2/d/evaluate.d:1293
 7# evaluate_applyFCCS at ../../../../Macaulay2/d/evaluate.d:820
 8# evaluate_evalraw at ../../../../Macaulay2/d/evaluate.d:1289
...
126# 0x00007FD38FAE7C42 in /usr/lib/x86_64-linux-gnu/libgc.so.1
127# 0x00007FD38F6A76DB in /lib/x86_64-linux-gnu/libpthread.so.0
128# 0x00007FD38E74471F in /lib/x86_64-linux-gnu/libc.so.6
-- end stack trace *-
Command exited with non-zero status 1
../Makefile.chapter:46: recipe for target 'test.out' failed
6.77user 0.08system 0:06.39elapsed 107%CPU (0avgtext+0avgdata 135048maxresident)k
make[4]: Leaving directory '/home/runner/work/M2/M2/M2/BUILD/build/Macaulay2/tests/ComputationsBook/monomialIdeals'
```

@d-torrance -- is this the same sort of crash you've been getting?

**Comment by d-torrance** [comment]
> @d-torrance -- is this the same sort of crash you've been getting?

Yup -- same line number in `monideal.cpp` as https://github.com/Macaulay2/M2/issues/1742#issuecomment-751502158 and https://github.com/Macaulay2/M2/issues/1742#issuecomment-753687336.

**Comment by DanGrayson** [comment]
@mikestillman  --  what could explain such a crash?

Maybe I'll build 1.17 first on a vm with 18.04 here at home, and if I'm lucky, I'll run into the same crash.

**Comment by mahrud** [comment]
#1742 is the issue for this. It'll be difficult to find the discussion here.

**Comment by mikestillman** [comment]
I've just been looking at the code.  It seems like it should be fine.  It does use raw pointers though, so I'm going to audit the code a bit closer.  Since I don't have a crash to look at, it might be a bit difficult...  But we'll see....   I'll post this in #1742 as well.

@DanGrayson , @d-torrance What kind of systems has this been failing on?  Is there a specific test file I could try?

**Pull request merged**
