### PR TITLE
Add CoincidentRootLoci package

### PR DESCRIPTION
**Pull request by giovannistagliano**
Hi All!

This adds a new package named CoincidentRootLoci which accompanies 
a joint preprint with M. C. Brambilla (it will be available on arXiv soon).
The package provides tools for working with symmetric tensors of dimension 2, i.e. binary forms.

It is required Qepcad B as an optional component.

### CODE REVIEW

**Comment by DanGrayson** [comment]
I got this error
```
i2 : check "CoincidentRootLoci"
--running test 0 of package CoincidentRootLoci on line 30 in file M2/Macaulay2/packages/./CoincidentRootLoci/tests.m2
--    rerun with: check_0 "CoincidentRootLoci"
--making test results in file /var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-77292-0/1.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; ulimit -n 512; cd /var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-77292-0/2-rundir/; /Users/dan/src/M2/M2-Macaulay2/M2/BUILD/dan/builds.tmp/einsteinium-release-1.11.1/usr-dist/x86_64-Darwin-MacOS-10.13.4/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("CoincidentRootLoci", FileName => "/Users/dan/src/M2/M2-Macaulay2/M2/Macaulay2/packages/CoincidentRootLoci.m2")' <"/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-77292-0/1.m2" >>"/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-77292-0/1.tmp" 2>&1
/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-77292-0/1.tmp:0:1: (output file) error: Macaulay2 exited with status code 1
stdio:5:8:(3):[1]: error: error occured while executing QEPCAD. Please make sure that it is installed and configured correctly.
/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-77292-0/1.m2:0:1: (input file)
M2: *** Error 1
```
and in the error file is this:
```
i3 : assert isSomeLinearCombinationRealRooted(F,Verbose=>true);
/bin/sh: /bin/qepcad: No such file or directory
--running $qe/bin/qepcad +N20000000 +L10000 < '/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-77306-0/0-input'
stdio:5:8:(3):[1]: error: error occured while executing QEPCAD. Please make sure that it is installed and configured correctly.
```

The tests should run even if the program is not present.

**Comment by DanGrayson** [comment]
Here's a worrisome message from the garbage collector:
```
-- -*- M2-comint -*- hash: 988703134
/bin/sh: /bin/qepcad: No such file or directory
--loading configuration for package "Cremona" from file /Users/dan/Library/Application Support/Macaulay2/init-Cremona.m2
--warning: Qepcad required but not present

i1 : --/Users/dan/src/M2/M2-Macaulay2/M2/Macaulay2/packages/CoincidentRootLoci/tests.m2:73: location of test code
      -- realrank: Comon Ottaviani method for quintics
     t = gens Grass(0,1);

i2 : F = {52521875*t_0^5+90037500*t_0^4*t_1+61740000*t_0^3*t_1^2+21168000*t_0^2*t_1^3+3628800*t_0*t_1^4+248832*t_1^5,
          33571239*t_0^5+36736175*t_0^4*t_1+16087190*t_0^3*t_1^2+3525550*t_0^2*t_1^3+386995*t_0*t_1^4+17050*t_1^5,
          24*t_0^5+12*t_0^4*t_1+120*t_0^3*t_1^2+36*t_0^2*t_1^3+20*t_0*t_1^4+27*t_1^5,
          t_0^5+3*t_0^4*t_1+3*t_0^3*t_1^2+3*t_0^2*t_1^3+2*t_0*t_1^4,
          8400*t_0^5+129620*t_0^4*t_1+173908*t_0^3*t_1^2+79803*t_0^2*t_1^3+14210*t_0*t_1^4+784*t_1^5};

i3 : F' = flatten entries sub(matrix{F},QQ[][gens ring matrix {F}])

               5            4              3 2            2 3             4  
o3 = {52521875p  + 90037500p p  + 61740000p p  + 21168000p p  + 3628800p p  +
               0            0 1            0 1            0 1           0 1  
     ------------------------------------------------------------------------
            5           5            4              3 2           2 3  
     248832p , 33571239p  + 36736175p p  + 16087190p p  + 3525550p p  +
            1           0            0 1            0 1           0 1  
     ------------------------------------------------------------------------
              4         5     5      4         3 2      2 3        4      5 
     386995p p  + 17050p , 24p  + 12p p  + 120p p  + 36p p  + 20p p  + 27p ,
            0 1         1     0      0 1       0 1      0 1      0 1      1 
     ------------------------------------------------------------------------
      5     4       3 2     2 3       4       5          4            3 2  
     p  + 3p p  + 3p p  + 3p p  + 2p p , 8400p  + 129620p p  + 173908p p  +
      0     0 1     0 1     0 1     0 1       0          0 1          0 1  
     ------------------------------------------------------------------------
           2 3           4       5
     79803p p  + 14210p p  + 784p }
           0 1         0 1       1

o3 : List

i4 : for i from 1 to 4 list assert(realrank(F'_(i-1)) == i)
Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS
```

**Comment by DanGrayson** [comment]
Similarly here:
```
-- -*- M2-comint -*- hash: 1829773829
/bin/sh: /bin/qepcad: No such file or directory
--loading configuration for package "Cremona" from file /Users/dan/Library/Application Support/Macaulay2/init-Cremona.m2
--warning: Qepcad required but not present

i1 : --/Users/dan/src/M2/M2-Macaulay2/M2/Macaulay2/packages/CoincidentRootLoci/tests.m2:117: location of test code
      -- real rank boundary (odd)
     k = 3

o1 = 3

i2 : n = 2*k-1

o2 = 5

i3 : lambda = {3}|toList((k-2):2)

o3 = {3, 2}

o3 : List

i4 : describe coincidentRootLocus lambda

o4 = Coincident root locus associated with the partition {3, 2} defined over QQ
     ambient: P^5 = Proj(QQ[t_0, t_1, t_2, t_3, t_4, t_5])
     dim    = 2
     codim  = 3
     degree = 12
     The singular locus coincides with the coincident root locus associated with the partition {5}

i5 : time D = ideal dual(coincidentRootLocus lambda);  
Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS
```

**Comment by DanGrayson** [comment]
And here:
```
-- -*- M2-comint -*- hash: 1130073339
/bin/sh: /bin/qepcad: No such file or directory
--loading configuration for package "Cremona" from file /Users/dan/Library/Application Support/Macaulay2/init-Cremona.m2
--warning: Qepcad required but not present

i1 : --/Users/dan/src/M2/M2-Macaulay2/M2/Macaulay2/packages/CoincidentRootLoci/tests.m2:136: location of test code
      -- real rank boundary (even)
     k = 3

o1 = 3

i2 : n = 6

o2 = 6

i3 : time R = realRankBoundary(n,k+1)
Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS
```

**Comment by DanGrayson** [comment]
And here:
```
-- -*- M2-comint -*- hash: 916005463
/bin/sh: /bin/qepcad: No such file or directory
--loading configuration for package "Cremona" from file /Users/dan/Library/Application Support/Macaulay2/init-Cremona.m2
--warning: Qepcad required but not present

i1 : --/Users/dan/src/M2/M2-Macaulay2/M2/Macaulay2/packages/CoincidentRootLoci/tests.m2:189: location of test code
      -- singularLocus
     X10 = coincidentRootLocus(toList(10:1),ZZ/101,Variable=>x)
Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS
```

**Comment by DanGrayson** [comment]
This is suboptimal:
```
        OptionalComponentsPresent => try get "!$qe/bin/qepcad -h" then true else false,
```
It would be better to just look for `qepcad` to be found on the PATH, so I suggest
```
        OptionalComponentsPresent => try get "!qepcad -h" then true else false,
```
and something similar where it gets used.

The reason is that installing software is almost uniformly done by putting it on the PATH.

**Comment by giovannistagliano** [comment]
Sorry for the falling tests. I'll try to fix them soon.

**Comment by giovannistagliano** [comment]
I cannot understand why you get the error "Too many heap sections". All those codes should be fast.

**Comment by DanGrayson** [comment]
Me, too.  Let me know when it's ready to review again.

**Comment by giovannistagliano** [comment]
It seems ready to me. I applied your suggestions.

**Comment by DanGrayson** [comment]
Thanks.  I've silenced the test:
```
diff --git a/M2/Macaulay2/packages/CoincidentRootLoci.m2 b/M2/Macaulay2/packages/CoincidentRootLoci.m2
index aefb9c56b..9de541f16 100644
--- a/M2/Macaulay2/packages/CoincidentRootLoci.m2
+++ b/M2/Macaulay2/packages/CoincidentRootLoci.m2
@@ -11,7 +11,7 @@ newPackage(
         PackageExports => {"Cremona","Resultants"},
         DebuggingMode => false,
         AuxiliaryFiles => true,
-        OptionalComponentsPresent => try get "!qepcad -h" then true else false,
+        OptionalComponentsPresent => try get "!qepcad -h 2>&1" then true else false,
         CacheExampleOutput => true,
         Reload => false
 )
```

**Comment by giovannistagliano** [comment]
Thank to you!

**Comment by mahrud** [comment]
There seems to be something different with the qepcad-B software in my machine (64bit Fedora 28 kernel 4.19.15 with qepcad-B-1.69-17). I get the following error from M2:
```
-- -*- M2-comint -*- hash: 2051741543

i1 : R := QQ[x,y];

i2 : F = 2*x^7+7*x^6*y+168*x^5*y^2+140*x^4*y^3+70*x^3*y^4+21*x^2*y^5+56*x*y^6+4*y^7

       7     6        5 2       4 3      3 4      2 5        6     7
o2 = 2x  + 7x y + 168x y  + 140x y  + 70x y  + 21x y  + 56x*y  + 4y

o2 : QQ[x, y]

i3 : realrank F
/bin/sh: line 1: 19454 Killed                  qepcad +N20000000 +L10000 < '/tmp/M2-19420-0/0-input'
stdio:3:1:(3): error: error occured while executing QEPCAD. Please make sure that it is installed and configured correctly.
```
The contents of the input file is:
```
[Existence of real values of (a,b) such that a given polynomial in (QQ[a, b])[z] is real-rooted]
(a,b,z)
0
(F a) (F b) (X 5 z) [z^5 + b z^4 + a z^3 - 2 a z^2 - z - b = 0]. 
finish
```
And when I run that command directly this is what I get:
```
$ qepcad +N20000000 +L10000 < '/tmp/M2-19420-0/0-input'
=======================================================
                Quantifier Elimination                 
                          in                           
            Elementary Algebra and Geometry            
                          by                           
      Partial Cylindrical Algebraic Decomposition      
                                                       
               Version B 1.69, 16 Mar 2012
                                                       
                          by                           
                       Hoon Hong                       
                  (hhong@math.ncsu.edu)                
                                                       
With contributions by: Christopher W. Brown, George E. 
Collins, Mark J. Encarnacion, Jeremy R. Johnson        
Werner Krandick, Richard Liska, Scott McCallum,        
Nicolas Robidoux, and Stanly Steinberg                 
=======================================================
Enter an informal description  between '[' and ']':
[Existence of real values of (a,b) such that a given polynomial in (QQ[a, b])[z] is real-rooted]Enter a variable list:
(a,b,z)Enter the number of free variables:
0
Enter a prenex formula:
(F a) (F b) (X 5 z) [z^5 + b z^4 + a z^3 - 2 a z^2 - z - b = 0].

=======================================================

Before Normalization >
finish
^C 
```
Is the program supposed to return something after "finish"? I've tried reinstalling qepcad-B but it didn't help. Uninstalling qepcad-B (so that `qepcad -h` fails) isn't a solution either, since many packages depend on it.

For now I temporarily moved the qepcad binary and that helped finish compilation, but I thought I'd report the behavior.

**Comment by giovannistagliano** [comment]
Hi, on my machine (Ubuntu 18.04) with the same version of qepcad everything seems to work correctly.
After "finish" qepcad returns me the following:
```

=======================================================

Before Normalization >
finish

An equivalent quantifier-free formula:

TRUE


=====================  The End  =======================

```
So M2 returns the value 5.

**Comment by DanGrayson** [comment]
When running examples, Macaulay2 imposes a memory limit, and probably you're running into that.  If that's the reason, then we should probably make a simpler example so it can pass.  Try running it yourself with the same limits, which you can get from the command line displayed.

I've never installed qepcad on my machine, so it doesn't try to run the examples on my machine.  It's free software, so could theoretically be included with Macaulay2, and hence we'd be testing those examples regularly.

**Comment by mikestillman** [comment]
In fact, it would be nice to have a separate package that interfaces to qepcad...

**Comment by DanGrayson** [comment]
I just installed qepcad.  The package installs properly, but a test fails:
```

i13 : F = f(eps,x,y)

        7      6        5 2       4 3       3 4      2 5         2           
o13 = 8x  + 28x y - 168x y  - 140x y  + 280x y  + 84x y  + (70eps  - 140eps +
      -----------------------------------------------------------------------
            6        2              7
      14)x*y  + (5eps  - 10eps + 1)y

o13 : QQ[eps][x, y]

i14 : if CoincidentRootLoci.Options.OptionalComponentsPresent then assert(realrank(F,Range=>(0,1/2),Limit=>4) == (5, 6, 7))

i15 : if CoincidentRootLoci.Options.OptionalComponentsPresent then assert(realrank(F,Range=>[0,infinity],Limit=>5) == (5, 6, 7))

i16 : if CoincidentRootLoci.Options.OptionalComponentsPresent then assert(realrank(F,Range=>[-1/2,-1/2]) == 5)
/bin/sh: line 1: 55879 Segmentation fault: 11  qepcad +N20000000 +L10000 < '/var/folders/3j/8fqhbzs94cd8w5shy482xlmr0000gq/T/M2-55847-0/7-input'
stdio:19:69:(3):[1]: error: error occured while executing QEPCAD. Please make sure that it is installed and configured correctly.
```
That could be a memory limitation.  Can someone figure that out?  This is Mac OS X.

**Comment by mahrud** [comment]
I ran qepcad with the given input in a separate shell (output is in my first comment), so I don't think it's a memory issue in my case. I didn't see a segfault either. It seemed like qepcad took the inputs and just didn't do the computation.

Mike, SageMath has a nice interface with qepcad, though I'm not sure if it supports every functionality of qepcad or not.

**Pull request merged**
