### PR TITLE
Revert "Use clang-tidy to use nullptr instead of 0 or NULL in e direc…

### PR DESCRIPTION
**Pull request by mikestillman**
…tory."

This commit caused problems with another branch (feature/monoids) where it proved difficult to clean up and remove conflicts with these changes.  Instead, we will rerun the clang-tidy code that created 2886 later, after that code is merged in.

### CODE REVIEW

**Comment by mikestillman** [comment]
Thanks to @mahrud for creating this branch and reverting the 2886 commit.

**Comment by mikestillman** [comment]
@antonleykin, @mahrud, @DanGrayson OK if I merge this pull request which rolls back one commit (which we can easily do later)?  If so, I'll merge it.

**Comment by DanGrayson** [comment]
Go ahead.

**Comment by antonleykin** [comment]
I’m okay with that.

**Comment by mahrud** [comment]
I don't recall creating this branch! I'm fine with either merging this or Anton's suggestion, which is to only revert the files that are changed by [this branch](https://github.com/mahrud/M2/commits/feature/monoids):
```patch
 M2/Macaulay2/d/CMakeLists.txt                     |    2 +
 M2/Macaulay2/d/Makefile.files.in                  |    4 +-
 M2/Macaulay2/d/actors4.d                          |    4 +-
 M2/Macaulay2/d/interface.dd                       |  227 +--------
 M2/Macaulay2/d/monoid.dd                          |   51 +++
 M2/Macaulay2/d/monomial_ordering.dd               |  190 ++++++++
 M2/Macaulay2/e/CMakeLists.txt                     |    5 +-
 M2/Macaulay2/e/M2FreeAlgebra.cpp                  |   13 +-
 M2/Macaulay2/e/M2FreeAlgebra.hpp                  |    1 -
 M2/Macaulay2/e/M2FreeAlgebraQuotient.cpp          |    7 +-
 M2/Macaulay2/e/M2FreeAlgebraQuotient.hpp          |    1 -
 M2/Macaulay2/e/Makefile.files                     |    3 +-
 M2/Macaulay2/e/MonomialOrder.cpp                  |  606 ++++++++++++++++++++++++
 M2/Macaulay2/e/MonomialOrder.hpp                  |  250 ++++++++++
 M2/Macaulay2/e/MonomialOrderOld.cpp               | 1680 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 M2/Macaulay2/e/MonomialOrderOld.hpp               |  113 +++++
 M2/Macaulay2/e/NAG.cpp                            |    9 +-
 M2/Macaulay2/e/NCAlgebras/FreeAlgebra.cpp         |    5 -
 M2/Macaulay2/e/NCAlgebras/FreeAlgebra.hpp         |    8 +-
 M2/Macaulay2/e/NCAlgebras/FreeAlgebraQuotient.cpp |    8 +-
 M2/Macaulay2/e/NCAlgebras/FreeAlgebraQuotient.hpp |    8 +-
 M2/Macaulay2/e/engine-includes.hpp                |    2 +
 M2/Macaulay2/e/frac.cpp                           |   18 +-
 M2/Macaulay2/e/frac.hpp                           |    9 +-
 M2/Macaulay2/e/freemod.cpp                        |    1 +
 M2/Macaulay2/e/imonorder.cpp                      |  656 --------------------------
 M2/Macaulay2/e/imonorder.hpp                      |   67 ---
 M2/Macaulay2/e/interface/freemodule.cpp           |   17 +-
 M2/Macaulay2/e/interface/matrix.cpp               |    7 +-
 M2/Macaulay2/e/interface/monoid.cpp               |  224 +--------
 M2/Macaulay2/e/interface/monoid.h                 |   37 +-
 M2/Macaulay2/e/interface/monomial-ordering.cpp    |  834 +--------------------------------
 M2/Macaulay2/e/interface/monomial-ordering.h      |   31 +-
 M2/Macaulay2/e/interface/ringelement.cpp          |   29 +-
 M2/Macaulay2/e/interface/ringelement.h            |    1 +
 M2/Macaulay2/e/localring.cpp                      |   20 +-
 M2/Macaulay2/e/localring.hpp                      |    9 +-
 M2/Macaulay2/e/matrix.cpp                         |    4 +-
 M2/Macaulay2/e/matrix.hpp                         |    2 +-
 M2/Macaulay2/e/monideal.cpp                       |    3 +-
 M2/Macaulay2/e/monideal.hpp                       |    6 +-
 M2/Macaulay2/e/monoid.cpp                         |  334 ++++++--------
 M2/Macaulay2/e/monoid.hpp                         |  153 ++++---
 M2/Macaulay2/e/monordering.hpp                    |   40 --
 M2/Macaulay2/e/poly.cpp                           |   27 +-
 M2/Macaulay2/e/poly.hpp                           |   13 +-
 M2/Macaulay2/e/polyquotient.cpp                   |    2 +-
 M2/Macaulay2/e/polyquotient.hpp                   |   17 +-
 M2/Macaulay2/e/polyring.hpp                       |   11 +-
 M2/Macaulay2/e/reducedgb.cpp                      |    3 +-
 M2/Macaulay2/e/relem.cpp                          |   57 +--
 M2/Macaulay2/e/relem.hpp                          |   10 +-
 M2/Macaulay2/e/ring-vecs.cpp                      |   12 +-
 M2/Macaulay2/e/ring.cpp                           |   22 +-
 M2/Macaulay2/e/ring.hpp                           |   32 +-
 M2/Macaulay2/e/unit-tests/MonomialOrderTest.cpp   |  172 +++++++
 M2/Macaulay2/e/unit-tests/NCGroebnerTest.cpp      |    4 +-
```

**Pull request merged**
