### PR TITLE
Add new package

### PR DESCRIPTION
**Pull request by eisenbud**
Added a new package to addNewPackage, called HigherCIOperators, which implements work that I've done with Jesse Burke and Frank-Olaf Schreyer.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Please run M2 with -q and then run "check" on this package, so the examples and tests that use your init file will fail.

**Comment by DanGrayson** [comment]
Please add the name of the package to the end of the file =distributed-packages

**Comment by DanGrayson** [comment]
I'll record the "changes, 1.8" info here, so I can fetch it later:

The package HigherCIOperators implements some work of Burke, Eisenbud and Schreyer on a structure that exists on resolutions over a complete intersection. This structure allows one to “lift” a resolution over a complete intersection to a resolution over the ambient ring—a sort of dual construction to the well-known Eisenbud-Shamash construction, and this construction is also implemented.

**Comment by eisenbud** [comment]
Done. There was no problem.

D
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics, University of California, Berkeley
www.msri.org/~de

**Comment by eisenbud** [comment]
Done.

D
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics, University of California, Berkeley
www.msri.org/~de

**Comment by DanGrayson** [comment]
Oops, my mistake - the use of ```kk``` was in an example, not a test.  I've fixed it and added the package to the list. 

Thanks for the contribution.

**Pull request merged**
