### PR TITLE
MonodromySolver update, Subalgebrabases stub

### PR DESCRIPTION
**Pull request by timduff35**
There are some small updates to the package MonodromySolver and one to the package SLPexpressions. See related commit #1041 @antonleykin 

Also, there are some updates to the currently-defunct "SubalgebraBases" package that were made within the last year. I'm not sure if all tests pass now, since one the bugs discovered was in the core.

### CODE REVIEW

**Comment by DanGrayson** [comment]
There are various problems:

The new file NOCertify.m2 should be in the packages directory.  

The package name "NOCertify" is too cryptic.  What about "OverdeterminedSystems" instead?

The name of the new package should be added to the end of the list in the file =distributed-packages.  

A test fails:
```
i1 : --/Users/dan/src/M2/M2/M2/Macaulay2/packages/NOCertify/NOCertify.m2:68: location of test code
     
     R=QQ[x,y,z,MonomialOrder=>{Weights=>{-1,-1,-1},3},Global=>false]

o1 = R

o1 : PolynomialRing

i2 : A=lAlgebra {x*y,x*z,y*z}

o2 = LAlgebra{...5...}

o2 : LAlgebra

i3 : assert(hilbertFunction(5,A)==21)
stdio:5:8:(3):[1]: error: can't promote scalar to ring of matrix
```

An example fails:
```
i7 : N'=subalgebraBasis(M,Limit=>20)

o7 = | x+y xy xy2 xy3 xy4 xy5 xy6 xy7 xy8 xy9 xy10 xy11 xy12 xy13 xy14 xy15
     ------------------------------------------------------------------------
     xy16 xy17 xy18 xy19 |

             1       20
o7 : Matrix R  <--- R

i8 : N'=subalgebraBasis(M,Limit=>20,Strategy=>Engine)
stdio:8:4:(3): error: expected 4 arguments
```

Also this:
```
i9 : assert(
          time sagbi(F,Limit=>30,Strategy=>Engine)
          ==
          ans)
stdio:20:11:(3):[1]: error: expected 4 arguments
     -- used 0.00339325 seconds
```

There are more errors.

Please ensure that the various packages can be installed with "installPackage" and checked with "check".

**Comment by timduff35** [comment]
Including the "NOCertify" was inadvertent. I removed it in the series of commits above. As for "SubalgebraBases", this package isn't included in any recent releases, and is still rough. I can try to iron out the errors, but if this is pushing it I don't mind waiting til next release.

**Comment by DanGrayson** [comment]
Okay, but I don't know what you mean by "pushing it".  If the examples run and the tests pass by tomorrow, that's all I require.

**Comment by timduff35** [comment]
"Pushing it" meant fix things in time. Examples and tests for "SubalgebraBases" should all be ok now.

**Pull request merged**
