### PR TITLE
update from Anton

### PR DESCRIPTION
**Pull request by antonleykin**

### CODE REVIEW

**Comment by mikestillman** [comment]
Dan, I'm going to merge this pull request, and then let the tests check tonight (possibly the Bertini tests will fail again).  This is a merge request in preparation for a branch that Anton and will base off of this.

**Comment by DanGrayson** [comment]
The overnight build failed, so let's roll this pull request back.

**Comment by mikestillman** [comment]
Anton, Did you forget to checkin a file?  Is this something we can fix immediately?

**Comment by antonleykin** [comment]
Hmm... compiles for me. Does the overnight build recompile the d/ directory?

The problem seems to be coming from numericalAlgebraicGeometryTrace
introduced in this commit:
400107a6dd332d3d80c92c915c316a020d1f60e9

**Comment by DanGrayson** [comment]
Yes, it compiles everything.

Anton, the error is with "make check" in the directory "e/unit-tests".  Try
that.

**Comment by mikestillman** [comment]
I’m also recompiling, and I’ll run the tests in a bit.

**Comment by antonleykin** [comment]
Yep, I can reproduce that.
I am not sure what the problem is... Could it be that the object file
defining "_M2_numericalAlgebraicGeometryTrace" is missing?

**Comment by mikestillman** [comment]
It is probably quite simple: the tests do not link with the garbage collector, so we probably need to add an object file that got added.

Once my examples run, I’ll run the tests.

**Comment by DanGrayson** [comment]
The file in question is d/M2.o

**Comment by mikestillman** [comment]
OK, I need to look at it, but the fix should be the same as the way I had to deal with M2_gbTrace.

I’ll (hopefully) make the fix.

**Comment by mikestillman** [comment]
OK, I added a line to e/unit-tests/M2-replacement.c, and the e/unit-tests directory now passes.

I’ll be testing the other tests this morning too.

**Comment by mikestillman** [comment]
OK, all tests now pass (except that one for running externalM2, which always still fails on my mac).

**Pull request merged**
