### PR TITLE
Update to latest versions of givaro and fflas_ffpack

### PR DESCRIPTION
**Pull request by d-torrance**
As discussed in #1114, we currently build old versions of givaro and fflas_ffpack.  There have been some small API changes in the latest versions.  (In particular, `isunit` has become `isUnit` in givaro, and `Det` takes slightly different arguments in ffpack.)

In these commits, we install the latest versions and update our calls to these libraries.

### CODE REVIEW

**Comment by mikestillman** [comment]
@DanGrayson, can you merge this into the eigen branch?  The changes in `configure.ac` might require some care?  I can try too.

**Comment by DanGrayson** [comment]
Okay.

**Comment by DanGrayson** [comment]
Instead of cherry-picking, should I just merge master into eigen?

**Comment by mikestillman** [comment]
Yes, that is a good idea.

**Comment by DanGrayson** [comment]
The merging resulted in no conflicts!  Am testing...

**Comment by DanGrayson** [comment]
Merged.

**Comment by DanGrayson** [comment]
@d-torrance  -- Doug, how did you manage to update fflas_ffpack without being able to push to the repository at https://github.com/Macaulay2/fflas-ffpack.git ?

**Comment by d-torrance** [comment]
I was actually wondering the same thing!

Locally, I checked out the appropriate tag that I'd pulled from the upstream repository at https://github.com/linbox-team/fflas-ffpack and made commit https://github.com/Macaulay2/M2/pull/1115/commits/540948e.

I figured I was going to have to ping you to update the Macaulay2 fork, but it just worked!  The latest commit in the fork is from last August, which is a month or so after the last fflas_ffpack release.  So maybe you or someone else updated the fork sometime around then anticipating that we might eventually want to use the newest version?

**Comment by DanGrayson** [comment]
Well, last August I was active on the eigen branch, so maybe that's one of the things I attended to -- and the version you updated us to is from last June.

**Pull request merged**
