### PR TITLE
Remove slow case from SparseResultants test

### PR DESCRIPTION
**Pull request by d-torrance**
Closes: #1914

### CODE REVIEW

**Comment by mahrud** [comment]
It's better not to outright remove a test. At least comment it out and mention how long it is taking now so it can be compared and potentially re-enabled in the future.

**Comment by d-torrance** [comment]
> It's better not to outright remove a test. At least comment it out and mention how long it is taking now so it can be compared and potentially re-enabled in the future.

Fair enough!  I've force-pushed a new version.  I didn't mention a specific time since it will vary from system to system (~2 minutes on my office desktop, but presumably we hit 700 seconds on ppc64el in Ubuntu for it to get killed.)

**Comment by mahrud** [comment]
You should mention a specific time and a rough description of your machine, otherwise we wouldn't know if it has gotten better or worse. Alternatively, you can use `cpuTime` before and after.

**Comment by d-torrance** [comment]
> You should mention a specific time and a rough description of your machine, otherwise we wouldn't know if it has gotten better or worse. Alternatively, you can use `cpuTime` before and after.

Done!

**Pull request merged**
