### PR TITLE
Use lookup in validate for getting qname

### PR DESCRIPTION
**Pull request by d-torrance**
This allows us to use inheritance for getting the qname of hypertext types (e.g, `MaybeQuotedTT` is a child of `TT` and should inherit its qname).

This fixes all the `MaybeQuotedTT` warnings that are cropping up in #3370.  (@mahrud - would you rather I push this to that branch?)

We also fix a "no method" error that was occurring when we encountered this "no qname" warning with a positive `debugLevel`.

### CODE REVIEW

**Comment by mahrud** [comment]
Now that I look at it I have more problems with `MaybeQuotedTT`:
1. hypertext types shouldn't be defined outside hypertext.m2
2. `<tt>` is already deprecated in html5, so adding a subtype seems strange

I think we should be slowly removing TT and using it's replacements instead:
> Consider the [`<kbd>`](https://www.w3schools.com/tags/tag_kbd.asp) element (for keyboard input), the [`<var>`](https://www.w3schools.com/tags/tag_var.asp) element (for variables), the [`<code>`](https://www.w3schools.com/tags/tag_code.asp) element (for computer code), the [`<samp>`](https://www.w3schools.com/tags/tag_samp.asp) element (for computer output), or use CSS instead.

**Comment by d-torrance** [comment]
Good point regarding `<tt>`.  I switched `MaybeQuotedTT` to `MaybeQuotedM2CODE`, which will also give us syntax highlighting in the HTML "ways to use" list.  I also switched `M2CODE` from a method to a subclass of `CODE`.

**Comment by mahrud** [comment]
I think my preference is to keep the hypertext types as close to html elements as possible. So let's go back to `M2CODE` being a method. Why not have KBD (for `<kbd>`) be always syntax highlighted and use that instead? Afterall, if someone types on a keyboard in emacs it'll be syntax highlighted.

**Comment by d-torrance** [comment]
Currently, the css for KBD elements gives us something that looks like a literal keyboard key, much like GitHub's css, e.g., <kbd>Esc</kbd>.

**Comment by mahrud** [comment]
That sounds great, doesn't it? It would look like this:

* <kbd>new Type of HashTable</kbd>
* <kbd>new Type of BasicList</kbd>

@pzinn could even turn them clickable.

**Comment by d-torrance** [comment]
Right, it already looks like that! https://macaulay2.com/doc/Macaulay2/share/doc/Macaulay2/Text/html/___K__B__D.html

**Comment by pzinn** [comment]
currently, on Macaulay2Web, what makes something clickable is that it's code (preferably with language set to be "Macaulay2"). so `KBD` is not clickable:
https://www.unimelb-macaulay2.cloud.edu.au/usr/share/doc/Macaulay2/Text/html/___K__B__D.html

**Comment by mahrud** [comment]
Right now the css needs a little adjusting to get them not to intersect:
image
But I would be in favor of this:
image

**Comment by d-torrance** [comment]
I've removed the `M2CODE` stuff, switched to `KBD` for the "ways to use" list, and updated the `KBD` css.  I'll let someone more artistic fiddle with it if they'd like, but adjacent `KBD` elements in a list now no longer collide:

image

The `qname` change now doesn't really matter since `MaybeQuotedTT` is gone, but I think it's still a good change if we ever add any other children of existing `Hypertext` classes.

**Comment by pzinn** [comment]
What's the point of this change? As mentioned above, it used to be that only <code> was considered code, and in particular clickable in the web interface. Is <kbd> supposed to replace it somehow?

**Comment by mahrud** [comment]
There are two separate things going on:
1. `<tt>` is deprecated from html5, replaced by code, kbd, and var
2. we currently have a non-standard `MaybeQuotedTT` type which turns into `"blah"` in terminal but just `blah` on the web:
```m2
i16 : net MaybeQuotedTT "blah"

o16 = "blah"

i17 : html MaybeQuotedTT "blah"

o17 = <span class="tt">blah</span>
```
`<kbd>` is replacing `MaybeQuotedTT`, not `<code>`. This solves both problems in one in a sensible, non-hacky way, and it actually looks good.

**Comment by pzinn** [comment]
oh okay I misunderstood. I thought `M2CODE` was completely removed.

**Comment by mahrud** [comment]
No, at some point `M2CODE` was turned from a method into a subclass of `CODE`, but no longer. There are a few other "fake" hypertext types that I wouldn't mind getting rid of, but no need to worry about that here.

**Comment by mahrud** [comment]
I changed the css a little, here's what it looks like now.
image
Probably all should be `<kbd>` types. Here's the net output:
```
       * "quotient(Ideal,Ideal)"
       * "quotient(Ideal,RingElement)"
       * "quotient(Module,Ideal)"
       * "quotient(Module,Module)" -- ideal or submodule quotient
       * "quotient(Module,RingElement)"
       * "quotient(MonomialIdeal,RingElement)"
```

**Comment by pzinn** [comment]
to clarify: should `kbd` content be syntax-hilighted? for example, on Macaulay2Web, at the moment, only `code.language-macaulay2` is.

**Comment by mahrud** [comment]
I don't have a strong preference either way. I would, however, prefer everything under "Exports" to be `kbd` not just the secondary tags. The simple way to do this is to have `TO` always use `kbd` but I don't know how to prevent the nodes with string keys (e.g. "heft vectors") from being turned to `kbd`.

**Comment by pzinn** [comment]
I agree that for consistency, it would be nice to have all exports in the same style, say using `kbd`.

**Pull request merged**
