### PR TITLE
Bump Factory and don't check for Prem

### PR DESCRIPTION
**Pull request by mahrud**
cc: @d-torrance

### CODE REVIEW

**Comment by d-torrance** [comment]
This is fine with me -- we actually could have removed the `Prem` check whenever we made 4.1.0 the minimum version as that was the first version that made it public (see https://github.com/Singular/Singular/pull/755/commits/70e277e7041e1a8cbe985427d5b3a901ae241b2c).  And the oldest Ubuntu release that I build PPA packages for (18.04) has 4.1.0.

(I'll actually be patching the 4.2.0 requirement out of the Debian package because Singular is still at 4.1.1 there.)

**Comment by mahrud** [comment]
Doesn't your PPA for have Factory 4.2.0 for Ubuntu 20.04?

**Comment by d-torrance** [comment]
> Doesn't your PPA for have Factory 4.2.0 for Ubuntu 20.04?

Nope, all the PPA builds just use the existing Ubuntu packages (4.1.0 in 18.04 and 4.1.1 in the others).

I actually started working on packaging singular 4.2.0 for Debian experimental this morning.  If we need it in the PPA for the Ubuntu Github builds, I'd be happy to upload it there as well when it's ready.

**Comment by mahrud** [comment]
> I actually started working on packaging singular 4.2.0 for Debian experimental this morning. If we need it in the PPA for the Ubuntu Github builds, I'd be happy to upload it there as well when it's ready.

That'd be great. I don't want to build anything other than Macaulay2 on github. It's a waste.

**Comment by d-torrance** [comment]
> > I actually started working on packaging singular 4.2.0 for Debian experimental this morning. If we need it in the PPA for the Ubuntu Github builds, I'd be happy to upload it there as well when it's ready.
> 
> That'd be great. I don't want to build anything other than Macaulay2 on github. It's a waste.

Will do!

**Comment by mahrud** [comment]
Ah, I see, the tests didn't fail because CMake didn't compile Factory correctly, they failed because there is a bug in the 4.2.0 source package of Factory:
```cpp
[mahrud@noether build]$ grep -R VERSION factoryconf.h
#ifndef FACTORYVERSION
#define FACTORYVERSION "4.1.3"
#ifndef PACKAGE_VERSION
#define PACKAGE_VERSION "4.2.0"
#ifndef VERSION
#define VERSION "4.2.0"
```

**Comment by mahrud** [comment]
@DanGrayson github builds are broken without this.

**Pull request merged**
