### PR TITLE
make use of valgrind code optional

### PR DESCRIPTION
**Pull request by DanGrayson**

### CODE REVIEW

**Comment by DanGrayson** [comment]
@jkyang92 -- take a look at this

(on some machines, reported by Mike, the valgrind type "OrigFn" is not defined.)

**Comment by DanGrayson** [comment]
@mikestillman

**Comment by mahrud** [comment]
If you add a new configure option, could you please also add it to `cmake/configure.cmake` and `INSTALL-CMake.md`?

**Comment by DanGrayson** [comment]
> If you add a new configure option, could you please also add it to `cmake/configure.cmake` and `INSTALL-CMake.md`?

I would be happy to, if I knew anything about cmake.  But I don't, too bad!

**Comment by mahrud** [comment]
> I would be happy to, if I knew anything about cmake. But I don't, too bad!

It's easier to learn by example:
https://github.com/Macaulay2/M2/blob/ddacbc2601d51f9e88194462d103909fcda044d4/M2/cmake/configure.cmake#L30

**Comment by DanGrayson** [comment]
Closing, in deference to #2701

**Pull request closed without merging**
