### PR TITLE
Reduce legacy code

### LINKED ISSUE #1089: Delete Macaulay2/compat
The README says:

> In this directory is the source code for some routines to replace missing
> system calls under various operating systems.  The routines do nothing, and
> return an error indication.  The intention is to compile them, place them in
> a library, and link against it after linking against the standard C library.

It doesn't appear to be used anywhere anymore.

### LINKED ISSUE #1090: Delete Macaulay2/nash
The comment above `nash.c` reads:

>  nash = "naive shell"
>  a replacement for bash designed just to do commands like this:
> 	/bin/nash -c "exec command arg1 arg2 ..."
>  Hopefully we can use it to make gdb more transparent.

It is potentially useful, but it's not relevant to Macaulay2, so perhaps moving it to a personal repository is more appropriate.

### LINKED ISSUE #1092: Replace Macaulay2/regex with better regex engine
`regex.h` exists on modern systems and is compatible with the rest of our code. Only this chunk would need to be removed or put in a `#ifndef HAVE_REGEX_H` clause:
https://github.com/Macaulay2/M2/blob/002e48263d67673713f9ef42422484181eee1978/M2/Macaulay2/d/scclib.c#L975-L986
See https://github.com/mahrud/M2/commit/57c7ff009a61f308b199df64127f2e6d6c74c2e1 for an example of a fix while keeping the regex directory (note that this also makes building object files in the regex directory unnecessary), though I think we would be fine deleting it.

I tested this on the CMake build and works fine, at least on Linux. A test on Mac would be great.

### LINKED ISSUE #1093: Move kernel/bibasis + use/remove kernel/mixed-cells
- The contents of [mixed-cells](https://github.com/Macaulay2/M2/tree/master/M2/Macaulay2/kernel/mixed-cells) doesn't seem to be used anywhere
- [bibasis](https://github.com/Macaulay2/M2/tree/master/M2/Macaulay2/kernel/bibasis) is used in e/engine.h, so maybe it should become a subdirectory of Macaulay2/e.

Then Macaulay2/kernel can be removed.

### LINKED ISSUE #1094: Remove Macaulay2/e-includes
This directory seems to serve 4 unrelated purposes:

1. The README reads:
> The purpose of this directory is to make the include files needed by the source files in ../e/.

However, most header files are already in Macaulay2/e, and I think keeping .cpp and .hpp files together makes more sense.

2. [doc-generateD](https://github.com/Macaulay2/M2/blob/master/M2/Macaulay2/e-includes/doc-generateD) states: (along with much more)
> Want to automate the process of writing d functions.

This seems very useful, but other than templates.txt, no other files here seem to be related to this. Perhaps this can move to a separate branch for that project.

3. The [Makefile](https://github.com/Macaulay2/M2/blob/master/M2/Macaulay2/e-includes/Makefile.in) has three targets to read the file `geoT.hpp` and use some `sed` rules to generate `geogbvec.hpp`, `geores.hpp`, and `geovec.hpp`:
  - `geogbvec.hpp` is generated, but the class `gbvectorHeap` is actually defined in `e/gbring.hpp`;
  - `geores.hpp` is included in `e/res-a0.cpp`;
  - `geovec.hpp` is never generated, but `e/geovec.hpp` exists and looks approximately as if the generated output was saved there.

Since testing with `geores.hpp` was easier, I wrote a templated geobucket type and replaced it with `geores.hpp` and everything seems to have worked fine.

4. install [statuscodes](https://github.com/Macaulay2/M2/blob/master/M2/Macaulay2/e-includes/statuscodes) in the Core directory and generate statuscodes.h from it.

These two files are only used by `m2/gb.m2` and `e/engine.h` as enums, but perhaps there's a better way to do this so we don't have an extra moving part in the build.

### PR DESCRIPTION
**Pull request by mahrud**
- move kernel/bibasis to e/bibasis
- use system regex.h
- remove e-includes

Closes #1089, closes #1090, closes #1093, closes #1094

### CODE REVIEW

**Comment by DanGrayson** [comment]
Do you not want to remove the files in `Macaulay2/regex/` also?

**Comment by mahrud** [comment]
Currently I have logic in d/types.h that still includes those files if regex.h does't exist on the system. Can you check if Macs have regex.h?

Also, I want to add compat and util to this before it's merged. Should I also remove nash?

**Comment by DanGrayson** [comment]
sure, remove nash.

I'll test in on mac os.

**Comment by DanGrayson** [comment]
`/usr/include/regex.h` exists on mac os x

**Comment by mahrud** [comment]
Great! Also, I forgot to ask you about `Macaulay2/probe`. Is it still used?

**Comment by mikestillman** [comment]
Do we have tests that show it has the same syntax for regular expressions? (I don't quite trust apple/FreeBSD to not make changes...). But perhaps it is POSIX compliant, and that is what we are using? (I haven't looked to see what the POSIX situation is with regex...)

**Comment by DanGrayson** [comment]
Under Ubuntu, regex.h is part of the package libc6-dev.  Luckily, our instructions already say to install it.  I'll check a few other flavors of linux for the source of it.

**Comment by DanGrayson** [comment]
There are some tests in `Macaulay2/packages/Macaulay2Doc/test/regex.m2`.

**Comment by mikestillman** [comment]
Will removing load/dumpdata code be part of this pull request too, or will that be a separate pull request?

**Comment by mahrud** [comment]
Does regex.h on Mac start like this?
```
/* Definitions for data structures and routines for the regular
   expression library.
   Copyright (C) 1985, 1989-2019 Free Software Foundation, Inc.
   This file is part of the GNU C Library.
```
That's from Fedora, where that test passes, by the way.

**Comment by DanGrayson** [comment]
I bet `probe` is no longer used, so try.  I think I used it to see how memory was laid out, as a tool for helping me write the dumpdata stuff.

**Comment by DanGrayson** [comment]
No, regex.h starts like this:
```
/*
 * Copyright (c) 2000, 2011 Apple Inc. All rights reserved.
 *
 * @APPLE_LICENSE_HEADER_START@
 * 
 * This file contains Original Code and/or Modifications of Original Code
 * as defined in and that are subject to the Apple Public Source License
 * Version 2.0 (the 'License'). You may not use this file except in
 * compliance with the License. Please obtain a copy of the License at
 * http://www.opensource.apple.com/apsl/ and read it before using this
 * file.
 * 
 * The Original Code and all software distributed under the License are
 * distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 * EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 * INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 * Please see the License for the specific language governing rights and
 * limitations under the License.
 * 
 * @APPLE_LICENSE_HEADER_END@
 */
/*
 * Copyright (c) 2001-2009 Ville Laurikari <vl@iki.fi>
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 *   1. Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 * 
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*-
 * Copyright (c) 1992 Henry Spencer.
 * Copyright (c) 1992, 1993
 *	The Regents of the University of California.  All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Henry Spencer of the University of Toronto.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *	This product includes software developed by the University of
 *	California, Berkeley and its contributors.
 * 4. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 *	@(#)regex.h	8.2 (Berkeley) 1/3/94
 */
```

**Comment by mahrud** [comment]
@mikestillman I removed dumpdata in the cmake branch, but those changes are much more pervasive compared to how local these folders are. I'd rather wait for the cmake branch for that.

**Comment by DanGrayson** [comment]
I've put nash here : https://github.com/Macaulay2/nash

**Comment by DanGrayson** [comment]
GNU regex.h is present on several flavors of linux I just looked at.

**Comment by DanGrayson** [comment]
It would be good to remove all of regex in this PR.  If it doesn't work on Mac OS X, we'll figure out why ...

**Comment by mahrud** [comment]
Looks like on some versions of linux, not having __USE_GNU defined causes issues with regex. Does your regex.h have `RE_SYNTAX_POSIX_EXTENDED` and `re_set_syntax` defined?

**Comment by DanGrayson** [comment]
> Looks like on some versions of linux, not having __USE_GNU defined causes issues with regex. Does your regex.h have `RE_SYNTAX_POSIX_EXTENDED` and `re_set_syntax` defined?

No.

**Comment by mahrud** [comment]
I reverted the last commit. This is still an improvement, because we simply include the regex.h that is bundled with Macaulay2 rather than building and linking it.

**Comment by DanGrayson** [comment]
How is it possible that including our regex.h yields good results if we link with code in glibc intended for use with a different regex.h?

**Comment by mikestillman** [comment]
Hmm, it looks like we remove `probe` in the eigen branch.  I'm not sure why we did that, but that branch builds fine now, so perhaps it isn't needed.  That will be in a separate pull request soon (tomorrow I hope).

**Comment by DanGrayson** [comment]
I'm sure probe is not needed.

**Comment by mahrud** [comment]
@DanGrayson, I see, that's why we compiled regexec.c into a library and linked with it ..
I looked into this situation more and I think we should use the standard POSIX regex API from libc:
```
extern int regcomp (regex_t *_Restrict_ __preg,
		    const char *_Restrict_ __pattern,
		    int __cflags);

extern int regexec (const regex_t *_Restrict_ __preg,
		    const char *_Restrict_ __String, size_t __nmatch,
		    regmatch_t __pmatch[_Restrict_arr_],
		    int __eflags);

extern size_t regerror (int __errcode, const regex_t *_Restrict_ __preg,
			char *_Restrict_ __errbuf, size_t __errbuf_size);

extern void regfree (regex_t *__preg);
```
The above bit is from regex.h on my machine, which matches those [on Mac](https://github.com/aosm/Libc/blob/4b43e647f509ce003b5a3452621ab289c9ad3e8a/include/regex.h#L199-L216).

Currently we use `re_set_syntax`, `re_compile_pattern`, and `re_search`, which are GNU extensions and don't exist on Mac.

I'll revert the regex changes for now. Probably refactoring scclib.c should be a new issue.

**Comment by DanGrayson** [comment]
Maybe that's why we include the regex code -- because we like the GNU syntax better than the POSIX syntax.  One difference seems to be whether grouping uses `\(...\)` or `(...)`.

**Comment by mahrud** [comment]
Sure, makes sense. I think this PR is ready for now.

**Comment by mahrud** [comment]
Is this PR still waiting for review?

**Comment by DanGrayson** [comment]
Thanks for the reminder -- I'm currently looking at #1096 ...  and now there is something wrong on the master branch presumably caused by merging #1115.

**Pull request merged**
