### PR TITLE
Update SemidefiniteProgramming and SumsOfSquares

### PR DESCRIPTION
**Pull request by diegcif**
I am updating the packages SemidefiniteProgramming and SumsOfSquares, including some bug fixes and improvements.

### CODE REVIEW

**Comment by diegcif** [comment]
I'll fix this error and create a new pull request

**Comment by diegcif** [comment]
Sorry for the confusion. I closed second pull request then.

**Comment by diegcif** [comment]
I only made changes in "SumsOfSquares" and "SemidefiniteProgramming". I don't understand why there are errors in other packages.

**Comment by DanGrayson** [comment]
Yup, this time no problem.

**Pull request merged**
