### PR TITLE
Disable valgrind helpers when valgrind is disabled.

### PR DESCRIPTION
**Pull request by jkyang92**
@mikestillman @MichaelABurr Hopefully fixes the issue noted in https://github.com/Macaulay2/M2/issues/2683#issuecomment-1330734590. I don't have the ability to verify that this actually fixes the issue, but it should.

### CODE REVIEW

**Comment by d-torrance** [comment]
I can confirm that this works.  Currently building Macaulay2 on an M1 laptop (@mikestillman -- finally got it!), and adding `-DNVALGRIND` to `CPPFLAGS` got me past the `OrigFn` issue.

**Comment by jkyang92** [comment]
@d-torrance Can you also try it without the -DNVALGRIND flag? in theory the valgrind.h file should define it if it's on a platform it doesn't recognize, but I don't know if that actually works

**Comment by DanGrayson** [comment]
I prefer the solution in https://github.com/Macaulay2/M2/pull/2702 , because it's an option for the configure script, hence easier for users to implement.

**Comment by jkyang92** [comment]
@DanGrayson This should not require users to add anything to the CFLAGS, although we can certainly add a configure option to add a -DNVALGRIND to the CFLAGS to disable it even on platforms where valgrind works. Also none of the code here involved requires valgrind to be installed to compile.

**Comment by mahrud** [comment]
I also prefer this solution. Seems simpler and doesn't involve even more configure options.

**Comment by MichaelABurr** [comment]
Should the default for valgrind be on or off?  I lean towards disabling valgrind by default and only enabling if by compiler flag (perhaps combined with the solution here).

**Comment by d-torrance** [comment]
> Can you also try it without the -DNVALGRIND flag? in theory the valgrind.h file should define it if it's on a platform it doesn't recognize, but I don't know if that actually works

@jkyang92 - Oh nice -- I didn't realize it was already defined for me!  Yes, it works great without explicitly adding anything to `CPPFLAGS`.

**Comment by mahrud** [comment]
There's already a `MEMDEBUG` option in both autotools and cmake:
https://github.com/Macaulay2/M2/blob/ddacbc2601d51f9e88194462d103909fcda044d4/M2/cmake/configure.cmake#L21
https://github.com/Macaulay2/M2/blob/ddacbc2601d51f9e88194462d103909fcda044d4/M2/configure.ac#L447

Would be nice if this could replace that or be combined with it (e.g. define `NVALGRIND` if `MEMDEBUG` is not defined), but that's the main reason I want to avoid having multiple similar sounding options.

**Comment by DanGrayson** [comment]
The default for inclusion of valgrind code should definitely be *not*, for a user who runs into the problem Mike encountered, where OrigFn was an undefined type, will be mystified and have no idea about what to do.

So, instead of using a variable called "NVALGRIND", which means "no valgrind", use a variable that means "yes valgrind".

**Comment by jkyang92** [comment]
I don't mind hiding it behind a flag, but the issue Mike encountered is a bit of a special case, related to the fact that M1 is an architecture unsupported by the valgrind headers.

Of note, none of this code requires the installation of valgrind on the system, since the idea and the implementation is we include the headers needed for this in our own repository. And in fact, there's no case where installing valgrind would have fixed Mike's issue or any similar issue.

As for NVALGRIND macro name, the name is somewhat "standardized" in that for the valgrind.h and memcheck.h headers use this to disable themselves if defined. The name is also in analogy to the NDEBUG macro that nearly every project uses.

For now, on this pull request, I will add some code to tie NVALGRIND to NDEBUG. Although I'm conflicted as to whether to just add it to the M2mem.* files or whether to add NVALGRIND at the configure/cmake step

**Comment by DanGrayson** [comment]
> I don't mind hiding it behind a flag, but the issue Mike encountered is a bit of a special case, related to the fact that M1 is an architecture unsupported by the valgrind headers.


We're going to have more and more users with M1 machines, and some of them will try to compile from source code.  It is a special case, but our code should deal with all special cases.

**Comment by mikestillman** [comment]
I think that the apple M1 is an important case, and we should support it "out of the box"!

**Comment by jkyang92** [comment]
> I think that the apple M1 is an important case, and we should support it "out of the box"!

Sure, my point was mostly that we aren't likely to encounter this issue again. And this pull request would certainly fix the M1 case sufficiently. We can't fix the fact that they can't use valgrind on those platforms of course.

As a note again, the valgrind.h header included via the memcheck.h header defines NVALGRIND if it doesn't find a platform it knows how to deal with.

**Comment by mahrud** [comment]
Until earlier this year gfan would not work on M1 because of an architecture problem (it would compile fine, and show its version and such fine, but no computations). That didn't force us to exclude gfan by default on all systems. I'm sure Valgrind support on M1 isn't far behind either.

**Comment by DanGrayson** [comment]
> > I think that the apple M1 is an important case, and we should support it "out of the box"!
> 
> Sure, my point was mostly that we aren't likely to encounter this issue again. And this pull request would certainly fix the M1 case sufficiently. We can't fix the fact that they can't use valgrind on those platforms of course.
> 
> As a note again, the valgrind.h header included via the memcheck.h header defines NVALGRIND if it doesn't find a platform it knows how to deal with.

Interesting!  @mikestillman -- could you test this pull request on your M1 mac to see if it works?

**Comment by mikestillman** [comment]
Hi all, this works on my apple M1 mac.  Well, it fails while running ForeignFunctions examples, but that fix is I think in Doug's pull request #2705, but no build errors from my standard build for this (on cmake and autotools builds).  I recommend we accept it!

**Pull request merged**
