### PR TITLE
Update Resultants.m2

### PR DESCRIPTION
**Pull request by giovannistagliano**

### CODE REVIEW

**Comment by DanGrayson** [comment]
This is strange: two of your examples, unrelated to this pull request, often crash under Mac OS X with our development version (on the master branch).  For example, this code crashes:
```
needsPackage "Resultants"
ZZ[t,u][x,y,z]
resultant genericPolynomials({1,2,3},ZZ)
```
If I run it in the version built for debugging, it doesn't crash.  

@mikestillman - Mike, can you try it?

**Comment by giovannistagliano** [comment]
Under Fedora 27 with the development version of M2 (v 1.10.0.1) everything seems to work well for me, and I have no way to test on Mac OS X. I hope the problem is solved soon...

**Comment by giovannistagliano** [comment]
I'd like to know if the problem is in "genericPolynomials" or in the main method "resultant".
For instance, does the following equivalent code crash?
`needsPackage "Resultants"
ZZ[a_0..a_2,b_0..b_5,c_0..c_9][x_0..x_2]
G = {a_0*x_0+a_1*x_1+a_2*x_2, 
b_0*x_0^2+b_1*x_0*x_1+b_3*x_1^2+b_2*x_0*x_2+b_4*x_1*x_2+b_5*x_2^2,
c_0*x_0^3+c_1*x_0^2*x_1+c_3*x_0*x_1^2+c_6*x_1^3+c_2*x_0^2*x_2+c_4*x_0*x_1*x_2+c_7*x_1^2*x_2+c_5*x_0*x_2^2+c_8*x_1*x_2^2+c_9*x_2^3}
resultant G
`
Thanks to anyone who can try this.

**Comment by giovannistagliano** [comment]
Does it still crash with these last changes?

**Comment by DanGrayson** [comment]
Yes, but that's our fault, since your code works with version 1.10, so I'm merging your pull request.

**Comment by giovannistagliano** [comment]
Thanks.

**Comment by DanGrayson** [comment]
The rewritten version crashes, too:
```
Macaulay2, version 1.10.0.1 with packages: ConwayPolynomials, Elimination,
IntegralClosure, InverseSystems, LLLBases, PrimaryDecomposition, ReesAlgebra,
TangentCone

i1 :needsPackage "Resultants"; ZZ[a_0..a_2,b_0..b_5,c_0..c_9][x_0..x_2]; G = {a_0*x_0+a_1*x_1+a_2*x_2, b_0*x_0^2+b_1*x_0*x_1+b_3*x_1^2+b_2*x_0*x_2+b_4*x_1*x_2+b_5*x_2^2, c_0*x_0^3+c_1*x_0^2*x_1+c_3*x_0*x_1^2+c_6*x_1^3+c_2*x_0^2*x_2+c_4*x_0*x_1*x_2+c_7*x_1^2*x_2+c_5*x_0*x_2^2+c_8*x_1*x_2^2+c_9*x_2^3}; resultant G
--warning: symbol "resultant" in Elimination.Dictionary is shadowed by a symbol
--  in Resultants.Dictionary use the synonym Elimination$resultant warning:
--  symbol "discriminant" in Elimination.Dictionary is shadowed by a symbol in
--  Resultants.Dictionary use the synonym Elimination$discriminant SIGSEGV
--  stack trace, pid 75028: level 0 -- return addr: 0x0x105b56911 -- frame:
--  0x0x70000ca3a8b0 level 1 -- return addr: 0x0x7fff6928af5a -- frame:
--  0x0x70000ca3a8d0 level 2 -- return addr: 0x0x10911e828 -- frame:
--  0x0x70000ca3a8e0 level 3 -- return addr: 0x0x105b571f1 -- frame:
--  0x0x70000ca3ae60 level 4 -- return addr: 0x0x1068a91b2 -- frame:
--  0x0x70000ca3ae90 level 5 -- return addr: 0x0x1061413bc -- frame:
--  0x0x70000ca3aeb0 level 6 -- return addr: 0x0x106148619 -- frame:
--  0x0x70000ca3af20 level 7 -- return addr: 0x0x10614bac7 -- frame:
--  0x0x70000ca3af80 level 8 -- return addr: 0x0x10614b039 -- frame:
--  0x0x70000ca3b0c0 level 9 -- return addr: 0x0x10614b0d9 -- frame:
--  0x0x70000ca3b110 level 10 -- return addr: 0x0x105f023a0 -- frame:
--  0x0x70000ca3b150 level 11 -- return addr: 0x0x1 -- frame: 0x0x70000ca3b200
--  end stack trace
```

**Comment by giovannistagliano** [comment]
I have no idea where the problem may be. Under Ubuntu 17.10 and Fedora 27, with the development version of M2, all seems work fine...

**Comment by DanGrayson** [comment]
By the way, I finally managed to get a stack trace (by using lldb) and all the crashes seem to be in the garbage collector.  I tried linking in the older version of it that we used in 1.10 and an even older version, but that didn't help, so it's not the fault of the garbage collector, either.  My latest idea is that I have managed to get things confused by linking in two versions of the collector ...

**Comment by DanGrayson** [comment]
Okay, I recompiled everything and now it doesn't crash.  Sorry for the noise!

**Pull request merged**
