### PR TITLE
comment out use of <concepts> header file

### PR DESCRIPTION
**Pull request by mikestillman**
Forgot to comment out this header file for use with <= c++17...

### CODE REVIEW

**Comment by mahrud** [comment]
Could you use this instead?
```cpp
#if __cplusplus >= 202002L
    // C++20 (and later) code
#endif
```

**Comment by mikestillman** [comment]
@mahrud @d-torrance We decided to not try to maintain two different c++ versions for the moment.  We are already maintaining TBB and no TBB.  Actually, now that TBB has settled down, perhaps we can insist on TBB support.   Thoughts?

**Comment by mahrud** [comment]
I'm not asking for supporting two different versions. I just don't like the use of `#if 0` because it's unclear what it means. Is this code deprecated and should be deleted? Is it experimental and not ready yet? Is it disabled because it's wrong and should be fixed?

**Comment by d-torrance** [comment]
>We are already maintaining TBB and no TBB. Actually, now that TBB has settled down, perhaps we can insist on TBB support. Thoughts?

That's fine with me -- the Debian/Ubuntu packages build with TBB support in all cases.

**Comment by mahrud** [comment]
> > We are already maintaining TBB and no TBB. Actually, now that TBB has settled down, perhaps we can insist on TBB support. Thoughts?
> 
> That's fine with me -- the Debian/Ubuntu packages build with TBB support in all cases.

Is it tbb 2020 in all cases though?

**Comment by d-torrance** [comment]
> Is it tbb 2020 in all cases though?

Yeah.  I had to backport TBB 2020 for a couple of the older releases.

**Pull request merged**
