### PR TITLE
NumericalAG update

### PR DESCRIPTION
**Pull request by antonleykin**
Incorporates the forks of @janverschelde (see pull request https://github.com/Macaulay2/M2/pull/1036 )
and @JoseMath ( the current state of https://github.com/JoseMath/M2/tree/IMA-Bertini )

The dependent MonodromySolver (@timduff35) and NumericalImplicitization (@jchen419 and @Joe-Kileel) should make their own pull requests if necessary.

### CODE REVIEW

**Comment by DanGrayson** [comment]
You probably don't want to change M2/submodules/fflas_ffpack

**Comment by DanGrayson** [comment]
Please rerun all examples with RerunExample => true.  (You have misspelled OutputStyle.)

**Comment by antonleykin** [comment]
There is a commit correcting the misspelling.

... but somehow 
```RerunExample => true```
does not help. 
It looks like the code for the documentation is grabbed from somewhere else. How can I track down the location? 

The log seems to indicate things get copied over from the correct location, e.g.:
```
i1 : installPackage ("Bertini", RemakeAllDocumentation=>true, RerunExamples=>true)                                                                                                                                                                                                 
--loading configuration for package "Bertini" from file /home/aleykin3/.Macaulay2/init-Bertini.m2                                                                                                                                                                                  
--installing package Bertini in /home/aleykin3/.Macaulay2/local/ with layout 1                                                                                                                                                                                                     
--using package sources found in /home/aleykin3/H/M2-anton/M2/Macaulay2/packages/                                                                                                                                                                                                  
--copying auxiliary source files from /scratch/aleykin3/M2-anton/M2/Macaulay2/packages/Bertini                                                                                                                                                                                     
--copying: /scratch/aleykin3/M2-anton/M2/Macaulay2/packages/Bertini/testSuiteForBertini.m2 -> /home/aleykin3/.Macaulay2/local/share/Macaulay2/Bertini/testSuiteForBertini.m2                                                                                                       
...
```

**Comment by antonleykin** [comment]
There were a couple more "OutputSyle" in Bertini.m2
Now the docs and example seem to install.

**Comment by mahrud** [comment]
It might be my fault, but I'm getting compilation errors that seem to be related to this change:
```
: installing package Bertini
/usr/bin/install -c -d Bertini-temporary
make: Entering directory `/home/mahrud/Projects/M2/M2/M2/BUILD/mahrud/build-gcc/Macaulay2/packages/Bertini-temporary'
cd Bertini-temporary && /home/mahrud/Projects/M2/M2/M2/BUILD/mahrud/build-gcc/usr-dist/x86_64-Linux-Fedora-30/bin/M2  -q --stop --silent -e errorDepth=3 -e debugLevel=0  -e "installPackage(\"Bertini\", RemakeAllDocumentation => false, IgnoreExampleErrors => false, RerunExamples => false, CheckDocumentation => true, UserMode => false, Verbose => false, InstallPrefix => \"/home/mahrud/Projects/M2/M2/M2/BUILD/mahrud/build-gcc/usr-dist/\", SeparateExec => true, DebuggingMode => true); exit 0"
--making example results for Variable groups in file /home/mahrud/Projects/M2/M2/M2/BUILD/mahrud/build-gcc/usr-dist/common/share/doc/Macaulay2/Bertini/example-output/___Variable_spgroups.out
ulimit -c unlimited; ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; ulimit -n 512; cd /tmp/M2-26029-0/2-rundir/; GC_MAXIMUM_HEAP_SIZE=400M /home/mahrud/Projects/M2/M2/M2/BUILD/mahrud/build-gcc/usr-dist/x86_64-Linux-Fedora-30/bin/M2-binary --silent --print-width 77 --stop --int --no-readline -q --no-randomize -e 'needsPackage("Bertini", Reload => true, FileName => "/home/mahrud/Projects/M2/M2/M2/Macaulay2/packages/Bertini.m2")' <"/tmp/M2-26029-0/1___Variable_spgroups.m2" >>"/home/mahrud/Projects/M2/M2/M2/BUILD/mahrud/build-gcc/usr-dist/common/share/doc/Macaulay2/Bertini/example-output/___Variable_spgroups.errors" 2>&1
/home/mahrud/Projects/M2/M2/M2/BUILD/mahrud/build-gcc/usr-dist/common/share/doc/Macaulay2/Bertini/example-output/___Variable_spgroups.errors:0:1: (output file) error: Macaulay2 exited with status code 1
/tmp/M2-26029-0/1___Variable_spgroups.m2:0:1: (input file)
M2: *** Error 1
```
Here is the error output:
```
[mahrud@noether mahrud]$ cat /home/mahrud/Projects/M2/M2/M2/BUILD/mahrud/build-gcc/usr-dist/common/share/doc/Macaulay2/Bertini/example-output/___Variable_spgroups.errors
-- -*- M2-comint -*- hash: -273104196

i1 : R = CC[x,y];

i2 : F1 = {x*y+1,2*x*y+3*x+4*y+5};

i3 : bertiniZeroDimSolve(F1, AffVariableGroup=>{{x},{y}});
sh: bertini: command not found
true

stdio:3:1:(3): error: Bertini run failed. 
```

Is there a step I'm missing for making bertini optional?

**Comment by DanGrayson** [comment]
Fixed in commit 8aba1c4831a83387feaf206689b119a7bdb3cb54

There were some new example output files for the package Bertini that should have been added to this pull request.

**Pull request merged**
