### PR TITLE
Hookify and add top level caching for basis, pushForward

### LINKED ISSUE #909: 'basis' gives incorrect answer in presence of variables of degree 0
The following is incorrect:
```
A = ZZ/101[a..d, Degrees=>{4:0}]
basis(2, A^1)
```

The basis command returns ```image matrix {{1_A}}```, but the answer should be the zero module.

The problem seems to stem from the computation in findHeftAndVars in Macaulay2/m2/modules2.m2, which somehow returns a heft vector {0} in this case.  The internal engine code apparently doesn't check that the heft vector is correct.

### PR DESCRIPTION
**Pull request by mahrud**
(Naturally, this is on top of #1918, but I think only 26 files are changed in the commits specific to this PR)

- [x] fixes #909
- [x] `basis`:
  - [x] moved to `basis.m2`
  - [x] hookify (so a strategy can be added for associative algebras) and use top level computation caching
  - [x] fixed various related bugs and added more tests
  - [x] changed the behavior of `findHeft` when no variables are given
- [x] more features for the cached computations pattern
- [x] changed `new OptionTable from List` to just ignore null entries, so matches `HashTable`
- [x] `pushForward`:
  - [x] moved to `pushforward.m2`
  - [x] hookify (so pushFwd can be added as a strategy) and use top level computation
  - [x] added more tests
  - [x] unexport `PushforwardComputation`
  - [x] added strategy based on #1522
- [x] simplify a few things with resolutions and make sure FastNonminimal resolutions are cached.

Many more TODO items are added at the top of added files, however, @mikestillman, this bug likely requires a fix in the engine:
```m2
basis(0, ZZ/101[a, Degrees => {0}]) -- should give error
basis(0, ZZ/101[a, Degrees => {0}]/ideal (a^3)) -- should be {1 a a2}
```
Perhaps I'm misunderstanding the point of degree zero elements, but since `a` is not invertible I think it should be considered a generator, and the basis for the first one should be `1 a a2 a3 ...` which isn't finite. But even then, these two seem to be wrong:
```m2
basis(0, ZZ/101[a, Degrees => {0}], Variables => {0})
basis(0, ZZ/101[a, Degrees => {0}]/ideal (a^3), Variables => {0})
```
These two should still work though:
```m2
basis(0, frac(ZZ/101[a, Degrees => {0}]))
basis(0, frac(ZZ/101[a, Degrees => {0}]), Variables => {0})
```

### CODE REVIEW

**Comment by mahrud** [comment]
@d-torrance @DanGrayson have either of you seen an InvariantRings error before? Also, shouldn't the artifacts file contain the error output?

**Comment by DanGrayson** [comment]
> @d-torrance @DanGrayson have either of you seen an InvariantRings error before? Also, shouldn't the artifacts file contain the error output?

Sorry, I don't remember.  One would hope that the artifacts file would contain everything we need.

**Comment by d-torrance** [comment]
> @d-torrance @DanGrayson have either of you seen an InvariantRings error before? Also, shouldn't the artifacts file contain the error output?

Yes -- #1773

**Comment by mahrud** [comment]
Thanks, I restarted the builds.

**Comment by mahrud** [comment]
I can't reproduce it, but here is the error:
```m2
2021-02-11T10:01:01.6128114Z /home/runner/work/M2/M2/M2/Macaulay2/packages/InvariantRing/Tests.m2:112:1: error:
2021-02-11T10:01:01.6165505Z  -- i3 : invariants2 = set {x_1*x_2*x_3,x_1^2*x_3*x_4}
2021-02-11T10:01:01.6166463Z  -- 
2021-02-11T10:01:01.6167210Z  --                    2
2021-02-11T10:01:01.6167836Z  -- o3 = set {x x x , x x x }
2021-02-11T10:01:01.6168468Z  --            1 2 3   1 3 4
2021-02-11T10:01:01.6169053Z  -- 
2021-02-11T10:01:01.6169638Z  -- o3 : Set
2021-02-11T10:01:01.6170198Z  -- 
2021-02-11T10:01:01.6170937Z  -- i4 : assert(set invariants T2 === invariants2)
2021-02-11T10:01:01.6172718Z  -- stdio:6:1:(3): error: assertion failed
2021-02-11T10:01:01.6175907Z  -- 
2021-02-11T10:01:01.6176823Z stdio:1:1:(3): error: test(s) #9 of package InvariantRing failed.
```
It's probably the same bug that you saw in #1773. @DanGrayson could you take a look at the code for equality of sets?

**Comment by DanGrayson** [comment]
> @DanGrayson could you take a look at the code for equality of sets?

It looks okay to me:
```
equal(x:HashTable,y:HashTable):Expr := (
     if x == y then return True;
     if x.hash != y.hash then return False;
     if x.Class != y.Class || x.parent != y.parent then return False;
     if x.hash == 0 && x.Class == cacheTableClass then return True; -- cache tables have hash code 0
     if x.Mutable || y.Mutable then return False;
     if x.numEntries != y.numEntries || length(x.table) != length(y.table) then return False;
     foreach a at i in x.table do (
	  p := a;
	  q := y.table.i;
	  if p.next == q.next then (
	       -- p.next and q.next must both be bucketEnd
	       if p.hash != q.hash 
	       || p.key != q.key && False == equal(p.key,q.key) 
	       || p.value != q.value && False == equal(p.value,q.value) 
	       then return False;)
	  else (
	       plen := 0; pp := p; while pp != pp.next do (pp=pp.next; plen=plen+1);
	       qlen := 0; qq := q; while qq != qq.next do (qq=qq.next; qlen=qlen+1);
	       if plen != qlen then return False;
	       while true do (
		    if p == p.next then break;
		    z := q;
		    while true do (
			 if z.key == p.key
			 || z.hash == p.hash && equal(z.key,p.key)==True
			 then (
			      if z.value == p.value
			      || True == equal(z.value, p.value)
			      then break
			      else return False;
			      );
			 z = z.next;
			 if z == z.next then return False;
			 );
		    p = p.next;
		    )));
     True);
```

**Comment by mahrud** [comment]
One thing mentioned by Mike and I agree with: Perhaps `basis` should do _less_.
- the option `SourceRing` should probably be eliminated and left to user to change the basis to another ring. At the very least, instead of assuming that there's always a canonical map from the source ring to the ring of the basis, the option should be replaced with an option that takes a `RingMap`, so the user can decide what the `DegreeLift` map should be. Better yet, we should eliminate this and add a new function `liftBasis` for lifting the source of a map to another module.
- the option `Truncate` should probably be deprecated, since we already have `truncate`

One possible thing that should be added instead of the above is to have the option `Limit` allow computing a finite number of basis elements of a module that is not finite over the base. Say, `basis(kk[x], Limit => 3)` should probably be `| 1 x x2 |` rather than an error.

**Pull request closed without merging**
