### PR TITLE
findProgram/runProgram updates

### PR DESCRIPTION
**Pull request by d-torrance**
This is a partial response to #2762 (wishlist items 1 - 5).   For example:

```m2
i1 : M2 = findProgram "M2"

o1 = M2

o1 : Program

i2 : M2 << "2 + 2"

o2 = 0

o2 : ProgramRun

i3 : status oo

o3 = 0

i4 : toString ooo

o4 = 
     i1 : 2 + 2
          
     o1 = 4

i5 : peek runProgram("M2", "--version")

o5 = ProgramRun{command => /usr/bin/M2 --version}
                error => 
                output => 1.21

                return value => 0
```

The related documentation has also been converted to `SimpleDoc` format.

I plan on working on the `MinimumVersion` suggestions (wishlist item 6) soon, but in another PR.

### CODE REVIEW

**Comment by d-torrance** [comment]
All the builds were failing because I tried documenting `(toString, ProgramRun)`, but that conflicts with the following:

https://github.com/Macaulay2/M2/blob/048c777dc703365e44c3865b2c1faed698b82b3a/M2/Macaulay2/packages/Macaulay2Doc/functions/toString-doc.m2#L5

Just force-pushed a fix.

**Comment by mahrud** [comment]
> All the builds were failing because I tried documenting `(toString, ProgramRun)`, but that conflicts with the following:
> 
> https://github.com/Macaulay2/M2/blob/048c777dc703365e44c3865b2c1faed698b82b3a/M2/Macaulay2/packages/Macaulay2Doc/functions/toString-doc.m2#L5
> 
> Just force-pushed a fix.

This shouldn't cause a conflict; a document tag that is marked as undocumented can be later documented without an error. This allows for marking every method undocumented by default and then documenting the exceptions.

**Comment by mahrud** [comment]
Deleted the previous comment. I'm not sure what is going on, but the `undocumented methods toString` line should not have caused a conflict ...

**Comment by d-torrance** [comment]
I'm not sure if this is what we want or not, but currently `undocumented methods toString` set up dummy documentation for each of the various `toString` method functions.

Here's a toy example:

```m2
i1 : newPackage("Foo", Headline => "foo");

i2 : foo = method();

i3 : foo ZZ := foo RR := x -> null;

i4 : beginDocumentation()

i5 : undocumented methods foo

i6 : peek Foo#"raw documentation"

o6 = MutableHashTable{foo(RR) => HashTable{DocumentTag => Foo :: foo(RR)}}
                                           filename => stdio
                                           linenum => 6
                                           undocumented => true
                      foo(ZZ) => HashTable{DocumentTag => Foo :: foo(ZZ)}
                                           filename => stdio
                                           linenum => 6
                                           undocumented => true
```

**Comment by d-torrance** [comment]
The failing `cmake-macos-12-clang-15` build is puzzling.  It was from the "Example: Translation and rotation sub-actions of the adjoint action of SE(3)" example from the `SubalgebraBases` package.

From the artifacts for this build:
```m2
i5 : R = QQ[x_1..x_9, MonomialOrder => Lex];
stdio:5:5:(3): error: expected a list, hash table, database, or dictionary
```

**Pull request merged**
