### PR TITLE
NumericalAG and other updates

### PR DESCRIPTION
**Pull request by antonleykin**

### CODE REVIEW

**Comment by DanGrayson** [comment]
I've started making some 1.9.1 distributions but not released them.  If this represents a major enough improvement, I might, however, be convinced to repeat that work and put this into 1.9.1.

**Comment by DanGrayson** [comment]
Okay, I'll put it into 1.9.1.  I see I overlooked some other older pull requests, too.

**Comment by antonleykin** [comment]
By the way, I have an old pull request to... my fork:
https://github.com/antonleykin/M2/pull/1

I am pretty sure Mike incorporated the changes elsewhere. What should I do
with this pull request?

**Comment by DanGrayson** [comment]
First bring your linalg branch up to date with our master branch and push it to github.  I predict you will see that the diffs vanish here on the web site.

**Comment by DanGrayson** [comment]
This adds a file `AlphaTest.m2` to `packages` that is not a package.  This adds packages without adding them to `=distributed-packages`.  This adds a package `ReactionNetworks` whose author is Jane Doe.  Package `EquivariantGB` does not load.  There is a new directory in `packages` called `Vision` but no package file called `Vision.m2`.

**Comment by antonleykin** [comment]
Those are packages that are in various states of development. They are not
meant for distribution.

I could fix EquivariantGB.m2.
Is there a good way to remove everything else you mentioned from my master
branch?

**Comment by DanGrayson** [comment]
The command for removing stuff is `git rm ...`.  After that, commit the removals and push to github.  Then make a new branch with a new name like "development" and use `git revert ...` to revert the removal.  I'm not sure how the history of the files will look at that point, but at lest you'll get them back.

Most people use the "master" branch to keep in sync with what's on the master branch upstream.  Another convenient strategy is to use separate development branches for separate development projects, so that when one is ready, it's easy to issue a pull request from it.

Don't both fixing that one unless it's important and easy and quick to fix.

**Comment by antonleykin** [comment]
I followed the instructions: git revert seems to not mess up the history as
much as I feared. I'll use it more often :)

As to EquivariantGB, it does load for me. It had a failing test, which I
commented out.
What kind of problems do you have?



On Sat, Jul 9, 2016 at 11:14 AM, Daniel R. Grayson <notifications@github.com

**Comment by DanGrayson** [comment]
Here's the error:
```
stdio:2:1:(3): error: package EquivariantGB has auxiliary files in "/Users/dan/src/M2/M2-Macaulay2/M2/Macaulay2/packages/EquivariantGB", but newPackage wasn't given AuxiliaryFiles=>true
```

**Comment by antonleykin** [comment]
Fixed that.
I am not sure why it worked for me before... Perhaps the package was
installed.

**Comment by DanGrayson** [comment]
Checking EquivariantGB fails with 
```
     needs concatenate(EquivariantGB#"source directory","./examples.m2")
stdio:3:1:(3): error: file not found: "/Users/dan/Library/Application Support/Macaulay2/local/share/Macaulay2/./examples.m2"
```
Consider using the function `currentFileDirectory`.

**Comment by antonleykin** [comment]
I am not sure why you get this error -- this line was commented out...
https://github.com/Macaulay2/M2/pull/496/commits/3ce4101016d9e757bc480cace3f044e735512983

**Comment by DanGrayson** [comment]
oops, it was using the installed version.

**Pull request merged**
