### PR TITLE
Add magnitude of posets

### PR DESCRIPTION
**Pull request by fchapoton**
The magnitude is an integer, a natural "cardinality" for posets (and finite categories more generally). See the article by Tom Leinster in Documenta Mathematica for more information.

Even if it often takes the value 1 (on posets with a maximum or a minimum), this is an interesting quantity.

I have also found something fishy in the method to check for isomorphisms of posets, and tried to fix that. This was found when implementing the degree polynomial, where I tried to copy-paste this part of the code, and it was not doing what was expected.

### CODE REVIEW

**Comment by fchapoton** [comment]
I have undone my dubious "fix" to isomorphism test.

**Comment by fchapoton** [comment]
@dcookii , @gwynwhieldon -- Dear authors, are these changes acceptable?

**Comment by gwynwhieldon** [comment]
Looks fine to me!

**Comment by dcookii** [comment]
lgtm; Thanks :)

**Pull request merged**
