### PR TITLE
Development

### PR DESCRIPTION
**Pull request by mikestillman**
This pull request contains 2 separate changes:
1. A newer version of the experimental Complexes package, joint with Greg Smith(mostly documentation additions, but some bug fixes too).
2. A new package, joint with David Eisenbud, named MonomialOrbits.m2

I would like both of these to be in M2 1.17, if possible.

### CODE REVIEW

**Comment by mikestillman** [comment]
@DanGrayson Hold off on accepting this merge request.  I'm going to simplify MonomialOrbits, by removing the Perms option (and resulting documentation), which is semantically muddy and not worth the effort.

**Comment by DanGrayson** [comment]
I converted it to a draft for you.  Just change it back when ready.

**Comment by mikestillman** [comment]
@DanGrayson This pull request should be good to merge now.

**Comment by DanGrayson** [comment]
I've added the new package "MonomialOrbits" to the list.  What keyword phrase(s) would you like to add to it?

@eisenbud @mikestillman

**Pull request merged**
