### PR TITLE
ChainComplexExtras package updated and augmented

### PR DESCRIPTION
**Pull request by eisenbud**

### CODE REVIEW

**Comment by DanGrayson** [comment]
I tried checking TateOnProducts with "check", but a test fails, because ChainComplexExtras wasn't loaded.  Please fix.

**Comment by DanGrayson** [comment]
ChainComplexExtras and TateOnProducts both export the following symbols: InitialDegree appendZeroMap nonzeroMin minimize trivialHomologicalTruncation
prependZeroMap chainComplexMap nonzeroMax removeZeroTrailingTerms
isMinimalChainComplex resolutionOfChainComplex isChainComplex.  That's probably a mistake, so please fix.

**Comment by DanGrayson** [comment]
Do you want the package TateOnProducts to be distributed with binary releases of Macaulay2?  If so, add its name to the end of the file =distributed-packages, or let me do it for you.

**Comment by eisenbud** [comment]
Please do it for us! (Unless Frank objects!) 

I hope the number on the package is suitably far below 1.0!

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Comment by DanGrayson** [comment]
Okay, I took care of that and fixed the two failing tests.  One test failed because "chainComplexData"
is not exported -- I deleted that part of the test.  The other failed because "boxDegrees" was not exported -- I exported it.

**Comment by eisenbud** [comment]
Thanks! -- David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Pull request merged**
