### PR TITLE
Updates to NumericalSchubertCalculus and MonodromySolver

### PR DESCRIPTION
**Pull request by antonleykin**
... and some other minor changes.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Is this pull request going to continue to change for a while?  If so, when will it be stable?

**Comment by antonleykin** [comment]
It is stable and is not going to change.  
I believe it did not change since submission... until I added some minor stuff yesterday.

**Comment by DanGrayson** [comment]
PHCpack includes new examples now, so running "check" will run 'phc' and produce new example output files.  Could you use "git status" to detect the new and changed example output files and commit them, too, so I don't need to install phc at my end?

**Comment by DanGrayson** [comment]
Thanks!

But now I see that the package NumericalSchubertCalculus also needs its example output
cached, now that the examples involve phc.

Can you take care of it, too?

**Comment by antonleykin** [comment]
I have a problem with
`installPackage "NumericalSchubertCalculus"`

It gives 
`stdio:2:1:(3): error: example results terminate prematurely: setVerboseLevel`

I've observed this error message before... it is always mysterious.

**Comment by antonleykin** [comment]
If EXAMPLEs in the document nodes that are NOT using SimpleDoc are deleted (there are only two such nodes in NSC)... the documentation installs without errors.

**Comment by DanGrayson** [comment]
An example consists of some input lines, which we run through M2 to get the
results.  We need to be able group the input lines with the output lines
for good display in html.  Consider this input:

  3+
  4

That's one input expression on two lines, and we expect one output
expression.  But if we tell M2 that it's two input expressions, we'll get
that error message.

Look at the error output file and try to find something like that.

On Dec 26, 2016 19:23, "antonleykin" <notifications@github.com> wrote:

I have a problem with
installPackage "NumericalSchubertCalculus"

It gives
stdio:2:1:(3): error: example results terminate prematurely: setVerboseLevel

I've observed this error message before... it is always mysterious.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Macaulay2_M2_pull_536-23issuecomment-2D269263875&d=DQMFaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=PAZ_jTPLrSb1btCfAu4RkycWe57N0sGyzbjgeOn2wN0&m=xixvfhrnj42a1xYon90hVuDwQn4xlOS0J4j_Haw2BmA&s=XoOWt-JncFoK8IQA9k__JNoNgKtzILtP6C8nnOB--Js&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAqvRHXK0pfY5q5O0mNhXrI-5FQjSmnm-2Ddks5rMISUgaJpZM4K0He0&d=DQMFaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=PAZ_jTPLrSb1btCfAu4RkycWe57N0sGyzbjgeOn2wN0&m=xixvfhrnj42a1xYon90hVuDwQn4xlOS0J4j_Haw2BmA&s=yTeBbdAndy_LC9KwvsF7R9PT4C6wAmwWx7DwnHSg1lc&e=>
.

**Comment by DanGrayson** [comment]
In this code
```
     EXAMPLE lines ///
     k = 3;
     n = 6;
     SchPblm = {
	 ({2,1}, random(CC^6,CC^6)),
	 ({2,1}, random(CC^6,CC^6)),
	 ({2,1}, random(CC^6,CC^6))
	 };
     solveSchubertProblem(SchPblm, k,n)
     ///,
```
you are telling M2 that each line is a complete example expression, so use
```
     EXAMPLE {
	  "k = 3;",
	  "n = 6;"
	  "SchPblm = {
	      ({2,1}, random(CC^6,CC^6)),
	      ({2,1}, random(CC^6,CC^6)),
	      ({2,1}, random(CC^6,CC^6))
	      };",
	  "solveSchubertProblem(SchPblm, k,n)"
	  }
```
instead.

The point is that the function `lines` does not look at indentation.

**Comment by antonleykin** [comment]
Fixed. There were two lines in the problematic EXAMPLE that looked fine, but had to be glued together:
```
-- The problem of 4 lines w.r.t. random flags
SchPblm = randomSchubertProblemInstance ({{1},{1},{1},{1}},2,4)
```

**Comment by DanGrayson** [comment]
Now we also need cached example output for another package that uses phc, see https://github.com/Macaulay2/M2/pull/536#issuecomment-269260270

**Comment by DanGrayson** [comment]
@antonleykin : can you suggest some brief text for the changes file that will describe the important improvements to the various packages, if any?

**Comment by antonleykin** [comment]
MonodromySolver is  a new package for solving systems of polynomial systems. 
AlphaTest implements Smale's alpha test that certifies solutions to square polynomial systems.
ReactionNetworks facilitates creation and manipulation of reaction networks and associated polynomial systems.

NumericalSchubertCalculus received a major update of homotopy continuation methods stemming from the geometric Littlewood-Richardson rule.

All other improvements (NumericalAG, SLPexpressions, etc.) are relatively minor.

**Comment by antonleykin** [comment]
I forgot `EquivariantGB` (mostly developed by @kroner), which got a major update: several strategies for computing equivariant Groebner bases are now available.

**Pull request merged**
