### PR TITLE
Added nanosleep function.

### PR DESCRIPTION
**Pull request by kschwede**
Hi, myself and Boyana Martinova (bmartinova18) have added a nanosleep function.  

It seems to work on our systems.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Thank you.  The code looks good and it seems to work.  Could you add some documentation and link to it from appropriate places?

**Comment by DanGrayson** [comment]
Something like this would be a good example for the documentation:
```

i10 : elapsedTime nanosleep 500000000
     -- 0.503543 seconds elapsed

o10 = 0
```

**Comment by bmartinova18** [comment]
We have updated it with documentation. Let us know if this works.

**Comment by DanGrayson** [comment]
Thanks!

**Pull request merged**
