### PR TITLE
Miura: Divisor Class Group Arithmtic

### PR DESCRIPTION
**Pull request by prof-joe**
Dear Profs. Michael E. Stillman and Daniel R. Grayson

My name is Joe Suzuki, associate professor of Department of Mathematics, Osaka University, Japan. 

Used to be, I was doing research on algebraic geometric cryptography.
http://link.springer.com/chapter/10.1007%2F3-540-49649-1_10

I propose a new package Miura: Divisor Class Group Arithmetic.

Thank you very much for your response.

Joe.

### CODE REVIEW

**Comment by DanGrayson** [comment]
You should you organize the file as a Macaulay2 "package"?  See
http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.8.2/share/doc/Macaulay2/Macaulay2Doc/html/_creating_spa_sppackage.html to get
started.

**Comment by prof-joe** [comment]
Dear Daniel,
Thank you very much for suggestion.  
I will follow the instruction.
Joe.
-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by prof-joe** [comment]
I made a mistake. Please tell me what I should do to include the Miura package in M2. I got confused. Thank you very much.

**Comment by DanGrayson** [comment]
Package added in commit e01daa4

**Comment by prof-joe** [comment]
Dear  Dan

I am sorry but immediate before I gave the file,
I have changed the source in a wrong way (I have 
removed brackets). Can you change the line 30 as
attached. Thank you very much.

Joe.
--------------------------------
Line 30 (the attached file is new)

old:
add=(J,K)-> reduced J*K

new:
add=(J,K)-> reduced (J*K)

-- 
Joe Suzuki <suzuki@math.sci.osaka-u.ac.jp>

**Comment by DanGrayson** [comment]
Done in commit d5660de9658b0d0bc7e0e3261e6f54fb7e176b46

**Pull request closed without merging**
