### PR TITLE
Revert "Restore missing diagrams from MonomialAlgebras package."

### PR DESCRIPTION
**Pull request by DanGrayson**
Reverts Macaulay2/M2#1131

### CODE REVIEW

**Comment by DanGrayson** [comment]
@d-torrance  --  I've reverted the merge until one of us can fix that issue.

**Comment by d-torrance** [comment]
Sounds good.

**Comment by mahrud** [comment]
This branch seems safe to delete.

**Comment by DanGrayson** [comment]
How did that branch even get into our repository??

**Pull request merged**
