### PR TITLE
Some "tests" updates

### PR DESCRIPTION
**Pull request by d-torrance**
As requested in https://github.com/Macaulay2/M2/pull/2026#issuecomment-818258809

### CODE REVIEW

**Comment by d-torrance** [comment]
I added a few more related commits to this branch.  In particular, `(code, ZZ)` now works with `tests`.  The functionality is so similar to `methods` and `hooks` that I figured it would make sense.

```m2
i1 : tests "Graphs"

o1 = HashTable{0 =>                                         }
                    ../../packages/Graphs.m2:5355:1-5360:1:
               1 => 
                    ../../packages/Graphs.m2:5361:1-5370:1:
               2 => 
                    ../../packages/Graphs.m2:5371:1-5383:1:
               3 => 
                    ../../packages/Graphs.m2:5384:1-5390:1:
               4 => 
                    ../../packages/Graphs.m2:5391:1-5395:1:
               5 => 
                    ../../packages/Graphs.m2:5396:1-5404:1:
               6 => 
                    ../../packages/Graphs.m2:5405:1-5419:1:
               7 => 
                    ../../packages/Graphs.m2:5420:1-5441:1:
               8 => 
                    ../../packages/Graphs.m2:5442:1-5449:1:
               9 => 
                    ../../packages/Graphs.m2:5450:1-5455:1:
               10 => 
                     ../../packages/Graphs.m2:5457:1-5464:1:

o1 : HashTable

i2 : code 4

o2 = --/home/profzoom/src/macaulay2/M2/M2/Macaulay2/packages/Graphs.m2:5395: location of test code

     --check diameter
     assert(diameter(pathGraph(7))===6);
```

**Comment by d-torrance** [comment]
Oops, made a typo, and the builds are all failing:

```m2
../../../../../../../../Macaulay2/m2/debugging.m2:20:6:(1):[43]: error: unrecognized keyword, line 37 of string: "Test"; expected: CannedExample, Code, Example, Pre, Text, Tree
```
I'll fix it shortly.

**Comment by d-torrance** [comment]
There is a potential disadvantage to allowing `(code,ZZ)` to work with `tests`.  Since `check` calls `tests`, calling `check` will silently overwrite `previousMethodsFound`.  So running `methods` or `hooks`, followed by `check`, followed by `code` may result in unexpected results.  For example:

```m2
i1 : methods rank

o1 = {0 => (rank, CoherentSheaf)}
     {1 => (rank, GradedModule) }
     {2 => (rank, Matrix)       }
     {3 => (rank, Module)       }
     {4 => (rank, MutableMatrix)}

o1 : NumberedVerticalList

i2 : check "FirstPackage"
 -- capturing check(0, "FirstPackage")                                       -- 0.0347993 seconds elapsed

i3 : code 0

o3 = --/home/dtorrance/src/macaulay2/M2/M2/Macaulay2/packages/FirstPackage.m2:57: location of test code

         assert ( firstFunction 2 == "D'oh!" )
```

I don't think this is a huge issue -- if you've just called `methods` or `hooks`, then you're very likely to call `code` immediately and not start running `check` -- but I figured I'd mention it.

**Comment by d-torrance** [comment]
Just added a commit fixing the issue I mentioned above.

**Comment by DanGrayson** [comment]
Thanks!

**Pull request merged**
