### PR TITLE
Numerical packages update

### PR DESCRIPTION
**Pull request by antonleykin**
Updates to MonodromySolver, NumericalAlgebraicGeometry, NAGtypes, etc. for 1.9.3 release.

### CODE REVIEW

**Comment by DanGrayson** [comment]
I've merged this, but I'd like to know why MonodromySolver and NumericalSchubertCalculus cache their example output.  If there's no good reason, we should undo that.

**Comment by DanGrayson** [comment]
Oh, I see now that MonodromySolver may run phc, which isn't distributed with Macaulay2.  So perhaps that's the reason for that.  Is it?

**Comment by antonleykin** [comment]
Yes, I think `phc` is the reason `NumericalSchubertCalculus` caches examples too.
By the way, is there a recommended way to run tests (TEST statements) that involve some software that is not in the distribution?

**Comment by DanGrayson** [comment]
Like this:

```
installPackage ("PHCpack", RerunExamples=>true)
```

**Pull request merged**
