### PR TITLE
Fast exponentiation in prime characteristic

### LINKED ISSUE #264: fast powers in char p
should be implemented in the engine.  I.e., do f^p by additivity and do f^n by expanding n in base p.

Hat tip to PosChar authors, see https://github.com/Macaulay2/Workshop-2014-Berkeley/blob/master/F-sing/PosChar.m2

### PR DESCRIPTION
**Pull request by radoslavraynov**
This fixes #264.

I've moved the actual logic from PolyRing::power() into a new PolyRing::power_direct(), making the former a dispatcher based on the characteristic being 0 or not. In particular, the overhead in zero-characteristic is a single function call.

In the way of benchmarking, below is the average runtime of raising to power a given random polynomial `f` using engine and high-level code (for example, as in #657). The `(p,{n1,n2,...},k)` col spec describes a test case, in which `f` is the sum of random forms in `ZZ/p[x,y,z]` of degrees `n1,n2,...` and `k` is the exponent. ~~I am not sure why~~ the high-level code before is sometimes *slightly* faster than the engine code after the change.

```
               (5,{4, 3},10), (17,{5},4), (19,{10},21), (7,{5, 6},31), (11,{3},51)
[engine-before] .0698586,    .000479839, 2.37298,     26.8513,       .347187,
[hi-lvl-before] .000392648,  .00162537,   .00630307,    .379307,     .0127448
[engine-after ] .0000616816, .000492968,  .0092006,     .487706,     .0149149
[hi-lvl-after ] .000453994,  .00159426,   .0100856,     .500135,     .0171947
```

### CODE REVIEW

**Comment by DanGrayson** [comment]
Thanks!  I'll let Mike take a look at this.

**Comment by radoslavraynov** [comment]
I just noticed that the optimization takes place only if the ring is syntactically `ZZ/p[...]`. Calculations in `ZZ[x,y]/5` or `ZZ/5[x,y,z]/z`, for instance, fall back to Ring::power(const ring_elem, mpz_t), which is implemented in the typical fashion. So I am not sure how useful the optimization would be without rewiring the power() methods in the related classes. Either way, let me know what you think when you get the chance.

**Comment by DanGrayson** [comment]
I think we don't have to worry about rings such as `ZZ[x,y]/5`.  We would also like it to work for rings over fields such as GF 81.

At top level, polynomial rings over finite fields have the characteristic stored under the key `symbol char`, by the way.

**Comment by radoslavraynov** [comment]
I pushed another commit addressing the issues below. I'll take another look over the weekend and then leave it in that state for Mike to review when he gets the chance.

I limited Ring::power() to `int`. This is the behavior for all rings except for the number rings and it resulted in the following inconsistency before.
```
S=ZZ[x]; (x+1)^2147483648;       -- throws stdio:2:15:(3): error: exponent too large
S=ZZ[x,y]/y; (x+1)^2147483648;   -- runs for a very long time
```

PolyRingQuotient::power() now uses PolyRing::power(), so the optimization takes place for `K[...]/I` for `K` being `ZZ/p` or `GF p^k` and `I` being trivial or not. For example, on my build
```
S=ZZ/5[x,y] -- or ZZ/5[x,y,z]/z or (GF 125)[x,y]
f=(x+y)
tot = 0.0;
for i from 1 to 100 do tot = tot + (timing f^5001)#0;
tot / 100
```
consistently gives 0.00001s instead of the 0.03987s before.

**Comment by radoslavraynov** [comment]
Incidentally, this also fixes #874.

**Comment by radoslavraynov** [comment]
I reverted the last commit (0d26ecb70b0fcc1c4bff58e8a2be837276ceae82) because it was too invasive. I will reimplement those changes later.

**Comment by mikestillman** [comment]
This pull request looks good, and really speeds up exponentiation over finite fields.  I will add a test that I wrote for it after I accept the pull request.

**Pull request merged**
