### PR TITLE
Allow modification of preloaded packages in init.m2

### PR DESCRIPTION
**Pull request by d-torrance**
We run the start functions (which, among other things, loads the `User` package that loads all of the preloaded packages) *after* loading `init.m2` rather than before it.  This allows us to modify the list of preloaded packages.

For example, if we put the following in `init.m2`:

```m2
Core#"pre-installed packages" = {"FirstPackage"}
```

Then we get:

```m2
Macaulay2, version 1.24.05-160-gc1436f9cbf-dirty (pre-installed-packages)
with packages: FirstPackage

i1 : 
```

Closes: #1644

### CODE REVIEW

**Comment by mahrud** [comment]
Isn't "pre-installed packages" a misnomer? They are all pre-installed. Maybe we should also rename this option to "preloaded packages"?

**Comment by d-torrance** [comment]
Yeah, that was bugging me too.  Renamed!

**Comment by mahrud** [comment]
Thanks! Maybe along with that, we should rename the "m2/installedpackages" file, or better yet define the list in Core.m2?

**Review by mahrud — APPROVED** [review]

**Comment by mahrud** [comment]
I think we broke the ability to do `importFrom_Core "blah"` in `init.m2`!

**Comment by d-torrance** [comment]
Oops, we did!  I think the problem is that now we load `init.m2` before we load the `User` package, and so `currentPackage` is null.  And in particular, there's no dictionary to add the imported symbols to.

**Comment by mahrud** [comment]
Yes, I figured this much, but wasn't sure what's the best solution. Thoughts on setting currentPackage to be Core before init.m2 is loaded? Then importFrom essentially acts like export!

**Comment by mahrud** [comment]
No that doesn't work ... surprisingly using `export` in `init.m2` also fails ...

**Pull request merged**
