### PR TITLE
Minor change in documentation

### PR DESCRIPTION
**Pull request by goelKriti**
Corrected a reference in the documentation.

### CODE REVIEW

**Comment by DanGrayson** [comment]
@goelKriti  --  the first three bytes of your new first line for the file consist of the encoding for an invisible unicode character:
```
             position: 236 of 237 (99%), column: 2
            character: ﻿ (displayed as ﻿) (codepoint 65279, #o177377, #xfeff)
              charset: unicode-bmp (Unicode Basic Multilingual Plane (U+0000..U+FFFF))
code point in charset: 0xFEFF
               script: arabic
               syntax: w 	which means: word
             to input: type "C-x 8 RET feff" or "C-x 8 RET ZERO WIDTH NO-BREAK SPACE"
          buffer code: #xEF #xBB #xBF
            file code: #xEF #xBB #xBF (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
    mac-ct:-*-Courier New-normal-normal-normal-*-12-*-*-*-m-0-iso10646-1 (#x3FD)

Character code properties: customize what to show
  name: ZERO WIDTH NO-BREAK SPACE
  old-name: BYTE ORDER MARK
  general-category: Cf (Other, Format)
  decomposition: (65279) ('﻿')
```

Can you fix it?

**Comment by goelKriti** [comment]
The package file runs smoothly in my laptop (windows 10, with version 1.16 of Macaulay2). The first commit only involved changing a reference in the documentation. The first line of the file, which is a line of dashes, was untouched. In later commits, I tried changing the first line to avoid the invisible unicode character, but it doesn't seem to work. Any suggestions?

**Comment by DanGrayson** [comment]
I'll take a look at it.  Meanwhile, this problem has prompted me to post this issue : https://github.com/Macaulay2/M2/issues/1427

**Comment by DanGrayson** [comment]
(To even see the character, I had to open your file in emacs with the `raw-text-unix` coding system.)

**Comment by goelKriti** [comment]
Thanks for helping.

**Comment by mahrud** [comment]
@goelKriti what editor did you use for editing the file?

**Comment by goelKriti** [comment]
Emacs, on windows 10

**Pull request merged**
