### PR TITLE
A package for Multiplier ideals in dimension 2

### PR DESCRIPTION
**Pull request by ferrandc**
MultiplierIdealsDim2 is a package that contains several tools related
with the computations of multiplier ideals and jumping numbers. The 
algorithms implemented are the ones from the papers:
[AAD14] Multiplier ideals in two-dimensional local rings with rational
singularities, M. Alberich-Carrami\~nana, J. \`Alvarez Montaner, F.
Dachs-Cadefau, 2014 (arXiv:1412.3605),
[AADG14] Poincar\'e series of multiplier ideals in two-dimensional
local rings with rational singularities, M. Alberich-Carrami\~nana,
J. \`Alvarez Montaner, F. Dachs-Cadefau, V. Gonz\'alez-Alonso, 2014
(arXiv:1412.3607)
[Tuc10] Jumping numbers on algebraic surfaces with rational
singularities, K. Tucker, 2010 (Trans. Amer. Math. Soc. 362 (2010),
no. 6, 3223–3241.)

### CODE REVIEW

**Comment by DanGrayson** [comment]
Would you also like to add it to the end of the list ```=distributed-packages``` of packages to be distributed?

**Comment by ferrandc** [comment]
Yes, I would like to. Should I do something?

**Comment by DanGrayson** [comment]
Yes, add the line to the file, commit it, and push it.

**Comment by zteitler** [comment]
If you would like, you could add your code to the MultiplierIdeals package, and add your name to the list of authors of the package.

Zach

**Comment by ferrandc** [comment]
@DanGrayson Now it's done. Thank you for that.

@zteitler I think it is a good idea. However there is a problem: in my package I use the divisor and the intersection matrix associated to the ideal, while on the MultiplierIdeal package they use directly the ideal. To make them compatible, I would need some package or something to compute a resolution.

**Comment by DanGrayson** [comment]
I ran the tests, but got an assertion error:

```
i1 : --/Users/dan/src/M2/M2-Macaulay2/M2/Macaulay2/packages/MultiplierIdealsDim2.m2:763: location of test code
     
     E = matrix(
     {{ -5,  0,  1,  0,  1},
      {  0, -2,  1,  0,  0},
      {  1,  1, -1,  0,  0},
      {  0,  0,  0, -2,  1},
      {  1,  0,  0,  1, -1}})

o1 = | -5 0  1  0  1  |
     | 0  -2 1  0  0  |
     | 1  1  -1 0  0  |
     | 0  0  0  -2 1  |
     | 1  0  0  1  -1 |

              5        5
o1 : Matrix ZZ  <--- ZZ

i2 : F = matrix({{4,5,10,5,10}})

o2 = | 4 5 10 5 10 |

              1        5
o2 : Matrix ZZ  <--- ZZ

i3 : assert(#MultiplierIdeals(F,E,SmallestJN => 1 / 2,BiggestJN => 1,algorithm => "Tucker") == 3)
stdio:10:1:(3): error: assertion failed
```

**Comment by ferrandc** [comment]
I've solved the problem, there was a little mistake on saving some data. Thank you.

**Pull request merged**
