### PR TITLE
Give subscript operators higher precedence than superscript ones

### PR DESCRIPTION
**Pull request by d-torrance**
This is a response to https://github.com/Macaulay2/M2/issues/3198#issuecomment-2094071558.

In many languages (or at least the three I checked -- Python, R, and Javascript), subscripting/indexing operators have higher precedence than exponentiation.  But to this point in Macaulay2, they have the same precedence.

We re-order the precedence so that all of the subscript operators (`.`, `#`, `_`, etc.) have higher precedence than  the superscript ones (`^`, etc.)

### Before

```m2
i1 : L = {1,2,3,4}

o1 = {1, 2, 3, 4}

o1 : List

i2 : L#1^L#2
stdio:2:4:(3): error: no method for binary operator ^ applied to objects:
--            2 (of class ZZ)
--      ^     {1, 2, 3, 4} (of class List)
```

### After
```m2
i2 : L#1^L#2

o2 = 8
```

### CODE REVIEW

**Comment by d-torrance** [comment]
After playing around with this for a bit, I think this is too much of a breaking change.  Things like `dd^C_i` are everywhere in the `Complexes` package, and this should be parsed like `(dd^C)_i`, not `dd^(C_i)`.

**Comment by mahrud** [comment]
Was Complexes the main issue? I think you've convinced me that this is something that should definitely be fixed in M2, so I'm wondering if there's a workaround for `dd^C_i`.

**Comment by mahrud** [comment]
cc: @mikestillman @ggsmith

**Comment by d-torrance** [comment]
Yeah, `Complexes` seemed to be the main issue that I ran into.  There were a few other instances `A^i_j` that needed changing to `(A^i)_j` (mostly columns of powers of matrices and generators of Cartesian powers of modules), and this seems reasonable since the notation is otherwise ambiguous.  But `dd^C_i` is pretty ubiquitous in `Complexes`.

**Comment by mahrud** [comment]
Fortunately `dd^C_i` is a new notation, so it's not used very widely. I'm a bit confused reading the [documentation](https://macaulay2.com/doc/Macaulay2-1.23/share/doc/Macaulay2/Complexes/html/_differential_spof_spa_spchain_spcomplex.html), since `dd_C` is also listed, but doesn't work.

**Pull request closed without merging**
