### PR TITLE
New operators

### PR DESCRIPTION
**Pull request by mahrud**
- **added postfix ops `^! _! ^~ _~`**
- **added binary ops `^> ^>= ^< ^<= _> _>= _< _<=`**

I also wanted to add postfix op `^#` (for instance used in math for the ring map corresponding to a map of ringed spaces) and `_#` but currently this would conflict with things like `2^#L`. Perhaps they could be changed to `2 ^ #L`, but this could be an annoying breaking change.

### CODE REVIEW

**Comment by mahrud** [comment]
@d-torrance if you'd like to switch `~` to a prefix op in this PR, feel free to push commits to do that here.

**Comment by d-torrance** [comment]
I think if we do switch `~` to a prefix operator, it should wait for at least another release to give folks time to transition from `M~` to `M^~` for sheafification.

For the failed builds, I think either the other four operators should be added to the augmented assignment blacklist in `binding.d` or their augmented versions should be added to `exports.m2`.

**Comment by DanGrayson** [comment]
An operator that begins with _ or ^ should be unary and postfix.

**Comment by mahrud** [comment]
Why? I'd like to use the binary operators for truncations of modules, complexes, and filtrations in general.

**Comment by d-torrance** [comment]
We already have several binary operators that begin with `_` or `^`:  `_` and `^` themselves, as well as `^**`, `^^`, and all the corresponding augmented assignment operators.

**Pull request merged**
