### PR TITLE
add in new packages QuartenaryQuartics and GroebnerStrata, added chan…

### PR DESCRIPTION
**Pull request by mikestillman**
2 new packages: QuartenaryQuartics, GroebnerStrata

### CODE REVIEW

**Comment by mikestillman** [comment]
@mahrud There is an interesting bug, that I didn't notice on the caching pull request.  I still need to check, but here is the problem: compute a resolution of an ideal I (e.g. compute regularity).  Then try minimalBetti I.  This fails, as the resolution computed is the wrong type.  Probably minimalBetti should use the cached resolution that is there, if it is done.  The previous behavior though was to simply recompute the resolution, using FastNonminimal.  Either way, it gave an answer, now we get an error.

I can fix this example or test so it doesn't fail.  But maybe we should fix this behavior.  It might not be so easy though...  Thoughts?

Here is the bug (I should make this into a github issue):
```
R = ZZ/101[a..d]
I = monomialCurveIdeal(R, {1,3,4})
regularity I -- behind the scenes, computes a free resolution of I
minimalBetti I -- fails, as it requires a FastNonmimal resolution type.
```

**Comment by mahrud** [comment]
I've seen that error in other issues related to minimalBetti, like #2039, so I think it's a bug in minimalBetti that should be fixed.

**Comment by mahrud** [comment]
I think minimalBetti should just call `betti` if a minimal resolution is already cached, right? There's no point in using FastNonminimal in that case.

**Comment by mahrud** [comment]
@mikestillman #2305 fixes this issue.

**Comment by mahrud** [comment]
I'm not sure if rerunning the checks picks up the changes in that PR. You can try merging with development.

**Comment by mikestillman** [comment]
@mahrud Thanks!  @DanGrayson: I would really like this pull request in version 1.19.  Hopefully the latest change in #2305 will fix this problem.  We will see in a few hours.  There is one more type in an example that I will fix, but first I'll wait for these tests to finish.

**Comment by mikestillman** [comment]
@DanGrayson Should I merge in development into my this branch?  I think the changes in #2305 (which were merged into development) fix the errors that are happening.

**Pull request merged**
