### PR TITLE
Master

### PR DESCRIPTION
**Pull request by prof-joe**
Hi,

I have commited a new version (0.1 -> 0.2). Please pull it and make it public.
Thank you.

Joe.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Your package doesn't work.  Try running `installPackage "Miura"` and `check "Miura"` and fix the errors.

**Comment by DanGrayson** [comment]
Also merge with the current master branch to prevent a conflict.  You seem to be basing your work on a commit before Miura version 0.1 was added.

**Comment by prof-joe** [comment]
Hi

Thanks for the notice.
I am fixing it but I may take a week.

Joe.

Joe Suzuki, Osaka, Japan
-------------------------------
joe@suzuki.email.ne.jp

2017-11-12 8:10 GMT+09:00 Daniel R. Grayson <notifications@github.com>:

**Comment by mikestillman** [comment]
@prof-joe Did you ever make these changes?

**Comment by prof-joe** [comment]
Hi

I think I can push the changes promptly. But the power seems to be off at
http://habanero.math.cornell.edu:3690/

Can you ask your staff to recover it? Thank you very much.

Joe.

Joe Suzuki, Osaka, Japan
-------------------------------
joe@suzuki.email.ne.jp

2017-12-04 2:19 GMT+09:00 Mike Stillman <notifications@github.com>:

**Comment by mikestillman** [comment]
Dear Joe,

Thanks for letting me know.  I’ll try to fix that today.

Best,

Mike

**Comment by DanGrayson** [comment]
There are conflicts.

Does anyone want this to be in release 1.11?  The deadline is past.

**Comment by prof-joe** [comment]
Hi

I have been trying to remove the warning message for more two weeks but I
cannot still complete it.
I think the fix will be plain for the experts, can you fix it for me?
I will push it once the one bug is removed.

Thank you very much.

Joe.




Joe Suzuki, Osaka, Japan
-------------------------------
joe@suzuki.email.ne.jp

2017-12-17 11:26 GMT+09:00 Daniel R. Grayson <notifications@github.com>:

**Comment by DanGrayson** [comment]
I get an error message, not a warning message:
```

i3 : loadPackage ("Miura",DebuggingMode => true)
Miura.m2:43:15:(3):[7]: error: expected left hand parameter to be a function, type, or a hash table
Miura.m2:43:15:(3):[7]: --entering debugger (type help to see debugger commands)
Miura.m2:43:1-46:41: --source code:
inverse(Ideal):=J->(
if ring(J) =!=QR then error "-- expected the same ring";
quotient(ideal (entries gens gb J)#0#0, J)
)

ii5 : inverse

oo5 = inverse

oo5 : Symbol
```

I turned on debugging mode so I could see the problem -- `inverse` is a symbol.

You probably intended to attach your method to the method function `inverse` that is already in the core of Macaulay2, so you should remove `"inverse"` from the list of symbols exported by your package, because the symbol created by that masks the core's version of `inverse`.

**Pull request closed without merging**
