### PR TITLE
Update poset-example.html

### PR DESCRIPTION
**Pull request by fchapoton**
trying to fix the broken web page https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/Macaulay2/Visualize/poset-example.html

### CODE REVIEW

**Comment by DanGrayson** [comment]
The new version still has an error.  You can verify that by uploading it to https://validator.w3.org/.

**Comment by fchapoton** [comment]
Here are some more fixes that make the validator happy. Thanks for the feedback.

**Comment by DanGrayson** [comment]
What about the other html files in the package?  Does the validator like them?

**Comment by fchapoton** [comment]
They should be given the same treatment, yes. Should I do so here ?

**Comment by DanGrayson** [comment]
Yes, that would be great, it you have the spare time to donate.  Time is tight, though, since we are about to release 1.17.

Maybe, in the future, we should validate such html files included in packages.  We already validate the ones we generate.

**Comment by DanGrayson** [comment]
Authors ( @bstone, ... ) : are these changes okay with you?

**Comment by fchapoton** [comment]
ok, all done. I did not check wether the validator is fully happy, but it is certainly less angry.

**Comment by DanGrayson** [comment]
Okay, thanks!

**Comment by bstone** [comment]
I don't have any problems with these changes.  Thanks for your work on this.

**Pull request merged**
