### PR TITLE
build and upload tarfile from actions

### PR DESCRIPTION
**Pull request by mahrud**

### CODE REVIEW

**Comment by DanGrayson** [comment]
I wonder how annoyed with us github will be when we starting leaving such gigantic artifacts lying around all over.

**Comment by mahrud** [comment]
> I wonder how annoyed with us github will be when we starting leaving such gigantic artifacts lying around all over.

1. it's not so heavy, here is on my machine:
> Finished uploading artifact artifact. Reported size is 39536572 bytes. There were 0 items that failed to upload

2. they get discarded after 90 days by default, but I can also reduce it by `retention-days: 5`.
3. compute costs are a much more significant cost for github than storage costs, mainly because storage doesn't produce heat

**Comment by DanGrayson** [comment]
40 mb is pretty heavy, especially when we're making 6-10 of those per day

**Comment by DanGrayson** [comment]
What purpose do these tarfiles serve?

**Comment by mahrud** [comment]
> 40 mb is pretty heavy, especially when we're making 6-10 of those per day

Each github build is downloading and uploading hundreds of megabytes. Again, storage is nearly free! A public repository can be up to 100GB and each file up to 2GB. 40MB is really nothing.

> What purpose do these tarfiles serve?

I want to download them and make sure the documentation is generated okay.

**Comment by DanGrayson** [comment]
> > 40 mb is pretty heavy, especially when we're making 6-10 of those per day
> 
> Each github build is downloading and uploading hundreds of megabytes. Again, storage is nearly free! A public repository can be up to 100GB and each file up to 2GB. 40MB is really nothing.
> 
> > What purpose do these tarfiles serve?
> 
> I want to download them and make sure the documentation is generated okay.

Ah, that's worthwhile.

**Comment by mahrud** [comment]
Should I also omit the html validation check, as mentioned in #1639?

**Comment by DanGrayson** [comment]
> Should I also omit the html validation check, as mentioned in #1639?

No, that's important to check.

**Comment by mahrud** [comment]
> No, that's important to check.

Sure, but why not just do that on the nightly builds that you run? Certainly not every commit pushed warrants an hour of checking thousands of links across Macaulay2Doc!

Also, are you checking your slack messages?

**Comment by DanGrayson** [comment]
> > No, that's important to check.
> 
> Sure, but why not just do that on the nightly builds that you run? Certainly not every commit pushed warrants an hour of checking thousands of links across Macaulay2Doc!
> 

Well, that's a good idea.  Weekly should be enough.  We could also check various compilers weekly.

> Also, are you checking your slack messages?

The slack notification on my laptop pops up for 1 second and then disappears.  After that I don't know how to find it.  Just send me email instead.

**Comment by mahrud** [comment]
> Well, that's a good idea. Weekly should be enough. We could also check various compilers weekly.

So should I remove it from the github builds and have you do it once a week, or setup a system to do it once a week on github?

If the latter, can you show me how to excluded a target from a subdirectory? Does `-o run-html-check` work even if that target is inside `Macaulay2/html-check-links`?

**Comment by DanGrayson** [comment]
> > Well, that's a good idea. Weekly should be enough. We could also check various compilers weekly.
> 
> So should I remove it from the github builds and have you do it once a week, or setup a system to do it once a week on github?
> 
> Eitherway, can you show me how to excluded a target from a subdirectory? Does `-o run-html-check` work even if that target is inside `Macaulay2/html-check-links`?

Checking the links is quick, I believe, so don't worry about that.  The (slow) validation step can be omitted with `-o validate-html` at top level.

**Comment by mahrud** [comment]
Sorry, that was silly of me: I didn't see there was just a `make validate-html` that I needed to erase. I also updated the CPack scripts and changed it to create an ubuntu package. It should automatically detect dependencies, I believe, so it should be usable by developers at least.

**Pull request merged**
