### PR TITLE
Combine Core alarm tests and skip them during "check"

### PR DESCRIPTION
**Pull request by d-torrance**
As suggested in https://github.com/Macaulay2/M2/issues/1834#issuecomment-765858951.

### CODE REVIEW

**Comment by mahrud** [comment]
Do you mind also un-commenting these lines to see if this patch works?
https://github.com/Macaulay2/M2/blob/7f27a79786a671862f38286daa4041410e93196f/.github/workflows/test_build.yml#L187-L189

**Comment by d-torrance** [comment]
> Do you mind also un-commenting these lines to see if this patch works?
> https://github.com/Macaulay2/M2/blob/7f27a79786a671862f38286daa4041410e93196f/.github/workflows/test_build.yml#L187-L189
> 
> 
> (and remove the TODO line)

Sure thing!

**Comment by mahrud** [comment]
Sigh, Singular's website is down. Do you mind replacing the link for `factory-4.2.0` in `cmake/build-libraries.cmake` with `https://faculty.math.illinois.edu/Macaulay2/Downloads/OtherSourceCode/factory-4.2.0.tar.gz`? I hope the checksum is the same.

**Comment by d-torrance** [comment]
> Sigh, Singular's website is down. Do you mind replacing the link for `factory-4.2.0` in `cmake/build-libraries.cmake` with `https://faculty.math.illinois.edu/Macaulay2/Downloads/OtherSourceCode/factory-4.2.0.tar.gz`?

Done!

> I hope the checksum is the same.

It is:

```shell
profzoom@peg-amy:~/tmp$ wget https://faculty.math.illinois.edu/Macaulay2/Downloads/OtherSourceCode/factory-4.2.0.tar.gz
--2021-01-23 13:43:05--  https://faculty.math.illinois.edu/Macaulay2/Downloads/OtherSourceCode/factory-4.2.0.tar.gz
Resolving faculty.math.illinois.edu (faculty.math.illinois.edu)... 128.174.199.46
Connecting to faculty.math.illinois.edu (faculty.math.illinois.edu)|128.174.199.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4271595 (4.1M) [application/octet-stream]
Saving to: ‘factory-4.2.0.tar.gz’

factory-4.2.0.tar.g 100%[===================>]   4.07M   604KB/s    in 6.7s    

2021-01-23 13:43:12 (619 KB/s) - ‘factory-4.2.0.tar.gz’ saved [4271595/4271595]

profzoom@peg-amy:~/tmp$ sha256sum factory-4.2.0.tar.gz 
b66c4c78847e24b71386a42ea2fb368b721f5cb03966c8c78801f1677c45e6c0  factory-4.2.0.tar.gz
```

**Comment by mahrud** [comment]
Thanks! Also, I forgot to mention you can use `${M2_SOURCE_URL}/factory-4.2.0.tar.gz` instead. No need to push it now, maybe along with the next fix.

**Comment by DanGrayson** [comment]
Is this ready to be merged now?

**Comment by d-torrance** [comment]
> Is this ready to be merged now?

I think so -- the `ubuntu-latest-clang10` build worked, and the offending test was skipped as expected:

```m2
 -- capturing check(6, "Core")                                               -- 0.0320972 seconds elapsed
 -- capturing check(7, "Core")                                               -- 0.0352545 seconds elapsed
 -- skipping  check(8, "Core")                                               -- 0.000055801 seconds elapsed
 -- capturing check(9, "Core")                                               -- 0.0350842 seconds elapsed
 -- capturing check(10, "Core")                                              -- 0.0880943 seconds elapsed
```

**Pull request merged**
