### PR TITLE
Correction of an error in the package

### PR DESCRIPTION
**Pull request by DiffAlg**
It seems that the line 5 of the package had a wrong definition of the imaginary unit i. Now it is corrected.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Thanks for the correction.  I wonder why no test failed as a result.

**Comment by DiffAlg** [comment]
Hi Dan.
It seems that the problem it is still there. How can we fix it?!
It is on line 5. Where it says: F := toField (QQi / QQi_0^2)
it should say: F := toField (QQi / QQ(i_0^2+1))

**Comment by DiffAlg** [comment]
Ok, no. Here on github it is everything fine. It should be updated in the web page of Macaulay2.

**Comment by DanGrayson** [comment]
Which web page?

**Comment by DiffAlg** [comment]
http://www2.macaulay2.com/Macaulay2/Packages/

**Comment by DanGrayson** [comment]
I think in commit 81eff478f5715d250645bbf177eb481fb7372377 you made the desired change, and then in commit 6de1e663ce9c7876991cf6b16d5a9219200285d5 you mysteriously undid it.  So make the change again and submit a pull request.

**Pull request merged**
