### PR TITLE
Properly restore missing diagrams from MonomialAlgebras package.

### PR DESCRIPTION
**Pull request by d-torrance**
In the previous attempt (#1131), an absolute path using prefixDirectory
was used for the src attribute of each img tag.  This was hardcoded into
the documentation during build, and so the image links were still broken.

We now skip using prefixDirectory and let html.m2 compute the proper
relative path to the images.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Thanks.  I trust this one will work!

**Comment by d-torrance** [comment]
It should!  Here's a snippet from the generated html:

```

<p><img src="../../../../Macaulay2/MonomialAlgebras/projr_33.jpg" alt=""/></p>
--
  | <p><img src="../../../../Macaulay2/MonomialAlgebras/projc_33.jpg" alt=""/></p>
  | <p><img src="../../../../Macaulay2/MonomialAlgebras/projd_33.jpg" alt=""/></p>
  | <p><img src="../../../../Macaulay2/MonomialAlgebras/EGplane_33.jpg" alt=""/></p>
  | <p><img src="../../../../Macaulay2/MonomialAlgebras/EGbar_33.jpg" alt=""/></p>


```

That relative path should always work to get from the html directory to the package directory where the images are located, regardless of where everything is installed.

**Comment by DanGrayson** [comment]
Sounds good.  Do the images appear when you view the html in a browser?

**Comment by d-torrance** [comment]
Yes

**Comment by DanGrayson** [comment]
Great!

**Pull request merged**
