### PR TITLE
documentation improvements

### PR DESCRIPTION
**Pull request by lilysilverstein**
Includes new documentation nodes for many list and sequence functions, several table functions, and several string functions. Also a complete overhaul of the "lists and sequences" overview page. 

This should close issue #778.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Thanks, you're just in time for the next release -- I'll take a look at it.

**Comment by DanGrayson** [comment]
Thanks, it looks good to me.

**Comment by lilysilverstein** [comment]
Great! Don't hesitate to suggest or assign more places that need attention.

**Comment by DanGrayson** [comment]
It's probably easy to find more such places!

**Pull request merged**
