### PR TITLE
First refactored version of Polyhedra.

### PR DESCRIPTION
**Pull request by lkastner**
Please see my latest comment at [issue 516](https://github.com/Macaulay2/M2/issues/516).

Besides Polyhedra.m2 I made changes to
1. LatticePolytopes.m2
2. MonomialAlgebras.m2

I did not make changes to SRdeformations.m2, although I think they might be relatively straight forward.

### CODE REVIEW

**Comment by lkastner** [comment]
As @DanGrayson recommended, I will comment here:

1. @eisenbud @jankoboehm : I made changes to MonomialAlgebras.m2 to make it run with the new version of Polyhedra.m2. Please see commit [9797233b765b816a957cc535a1189c70702e369e](https://github.com/lkastner/M2/commit/9797233b765b816a957cc535a1189c70702e369e). Are you ok with these changes? Also I did not find Max Nitsche on github.
2. @alundman @mikestillman : I made changes to LatticePolytopes.m2 to make it run with the new version of Polyhedra.m2. This fixed a few bugs, but there are more. Maybe this is due to the latticePoints method from NormalToricVarieties.m2. @mikestillman : Did we already have a similar issue? How did we resolve it? Also I did not find Gustav Saeden Staahl on github.
3. @jankoboehm SRdeformations.m2 will not work with this version of Polyhedra.m2. Since you also know MonomialAlgebras.m2, the changes here should be relatively straightforward for you.

**Comment by lkastner** [comment]
@kathlenkohn Does gfanInterface2.m2 work with this version? Just to make sure.

**Comment by eisenbud** [comment]
Dear Lars,

Looks fine to me. I don't have Max' address either. Janko might...

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Comment by jankoboehm** [comment]
Hello Lars,

changes to MonomialAlgebras.m2 look fine to me too. I will ask Max but I think he is fine. I will do the changes to SRdeformations.

Best,
Janko

**Comment by mikestillman** [comment]
This compiles and all tests run.  I need to now check to make sure that NormalToricVarieties doesn't have any issue.  Perhaps @ggsmith should look too. There are a couple of undocumented functions which redefine hilbertBasis in a way that was not compatible with new versions in Polyhedra.  This might have been fixed, I just need to check.

**Comment by mikestillman** [comment]
I am getting the following error when building:

make: Entering directory `/Users/mike/src/M2-lkastner/M2/BUILD/mike/builds.tmp/darwin64-gcc4.9/Macaulay2/packages/Polyhedra-temporary'
cd Polyhedra-temporary && /Users/mike/src/M2-lkastner/M2/BUILD/mike/builds.tmp/darwin64-gcc4.9/usr-dist/x86_64-Darwin-MacOS-10.10.5/bin/M2  -q --stop --silent -e errorDepth=3 -e debugLevel=0  -e "installPackage(\"Polyhedra\", RemakeAllDocumentation => false, IgnoreExampleErrors => false, RerunExamples => false, CheckDocumentation => true, AbsoluteLinks => false, UserMode => false, Verbose => false, InstallPrefix => \"/Users/mike/src/M2-lkastner/M2/BUILD/mike/builds.tmp/darwin64-gcc4.9/usr-dist/\", SeparateExec => true, DebuggingMode => true); exit 0"
currentString:1:1:(3):[3]: error: mutable unexported unset symbol(s) in package Polyhedra: 'nFacets'
../../../../../../../Macaulay2/packages/Polyhedra/core/cone/properties.m2:58:14-58:21: here is the first use of 'nFacets'

**Comment by lkastner** [comment]
I'm sorry, I had some issue with nFacets. It should work now.

**Comment by mikestillman** [comment]
I am also removing SRdeformations from the distributed package list (on my copy of this pull request), so I can see if all other packages build correctly.

**Comment by mikestillman** [comment]
ToricVectorBundles doesn’t build (installPackage gives errors).  Possibly the function isPointed now takes optional arguments, or no longer does?  I’ll need to check.

**Comment by lkastner** [comment]
The ''LatticePolytopes.m2'' package will not work. Presumably the issue with latticePoints is the same as with hilbertBasis. It might even be solved by just solving the issue for hilbertBasis. Do you see an easy solution?

**Comment by mikestillman** [comment]
I just disabled ToricVectorBundles, and I’m trying NormalToricVarieties.  There are 5 example errors here.  I’ll look at the latticePoints, hilbertBasis problems here.  Hopefully they are easy to fix.

**Comment by mikestillman** [comment]
Here is one of the errors from NormalToricVarieties:

i1 : PP3 = projectiveSpace 3;

i2 : F = fan PP3

o2 = F

o2 : Fan

i3 : rays F
stdio:3:1:(3): error: No input rays given.

**Comment by lkastner** [comment]
The 'isPointed' function for fans was not fixed yet. I also modified the constructor for a fan in 'NormalToricVarieties.m2', your code works now for me.

Are there any other packages that I've missed? I cannot get 'ToricVectorBundles.m2' to run.

**Comment by mikestillman** [comment]
Here is another issue.  hilbertBasis is (re-)defined in NormalToricVarieties, but now the function takes optional arguments in Polyhedra, whereas it didn't previously.  I think that @ggsmith said that the version in NormalToricVarieties was a stopgap measure until the Polyhedra function improved enough to use.

     ../../../../Macaulay2/packages/Polyhedra/core/cone/methods.m2:26:32-30:12: --source code:
     hilbertBasis Cone := List => o -> (C -> (
           if isPointed C then getProperty(C, computedHilbertBasis)
           else error("Hilbert basis not implemented for non-pointed cones yet.")
        )
     )
     ---------------------------------
     -- code for method: hilbertBasis(Matrix)
     ../../../../Macaulay2/packages/NormalToricVarieties.m2:722:36-723:55: --source code:
     hilbertBasis Matrix := Matrix => C -> (
       transpose (normaliz(transpose C,"integral_closure"))#"gen")

**Comment by mikestillman** [comment]
This function in NormalToricVarieties needs to be rewritten for new Polyhedra interface.  @ggsmith
It should be easy, as the new ‘rays C’ is more what Greg wanted anyway, I think.

-- this function interfaces with the Polyhedra package
normalToricVariety Fan := opts -> FF -> (
  R := rays FF;
  F := sort apply(maxCones FF, C -> (
      Cr := rays C; 
      Cr = set apply(numColumns Cr, i -> Cr_{i}); 
      positions(R,r -> Cr#?r)));
  R = apply(R, r -> flatten entries r);
  return normalToricVariety(R, F,  
    WeilToClass => opts.WeilToClass,
    CoefficientRing => opts.CoefficientRing,
    Variable => opts.Variable))

**Comment by mikestillman** [comment]
There appear to be only two issues with NormalToricVarieties and its interface to Polyhedra: hilbertBasis, and the fact that the interface for maxCones has changed (line 316 in that file).  Both of these are easy to fix.  @ggsmith: should I just do so, and show you the result afterwords for your review?

**Comment by lkastner** [comment]
The optional arguments for hilbertBasis originate from FourTiTwo.m2, which I am using to compute a hilbert Basis.

The rays are probably not easier as before, but the maxCones should be exactly what NormalToricVarieties.m2 wants.

**Comment by mikestillman** [comment]
Lars, @ggsmith did the following for Hilbert basis in NormalToricVarieties:

hilbertBasis(Matrix) := Matrix => opts -> (C) -> (
    transpose (normaliz(transpose C,"integral_closure"))#"gen")

(The cone is generated by the columns of this matrix, whereas the hilbertBasis command in 4ti2 package wants the walls of the cone.

I changed the code in NormalToricVarieties to use your version, via posHull.

Which is better?

**Comment by mikestillman** [comment]
Lars, it looks like there are a number of issues with LatticePolytopes.  One option is for us to review it together, on skype, sometime in next few days. I'll continue to look at it.

**Comment by lkastner** [comment]
I am adding @nilten , since he hopefully knows ToricVectorBundles.m2 better than us. Most minor problems are fixed, but now the following issue came up:
```
i1 : E = tangentBundle hirzebruchFan 3

o1 = {dimension of the variety => 2 }
      number of affine charts => 4
      number of rays => 4
      rank of the vector bundle => 2

o1 : ToricVectorBundleKlyachko

i2 : HH_0^E {matrix{{1},{0}},matrix{{-1},{0}}}
stdio:2:5:(3): error: expected nonempty list
```
I had to make a small change to the cechComplex funtion for the Klyachko case, which is probably triggering this, see my [commit](https://github.com/Macaulay2/M2/pull/523/commits/dd94010607e8fa00150e5c6eb56562884667f084). Basically I am just turning list of indices back into cones. @nilten Can you make any sense of this?

@mikestillman is there already a Cech complex functionality in M2 we could use to get rid of the cechComplex methods in ToricVectorBundles?

**Comment by lkastner** [comment]
We were able to fix all documentation errors by replacing cones as keys in hashtables by pairs of matrices. The problem is now that matrices cannot be sorted canonically. Thus I added the old sorting method from Polyhedra and wrapped it into customConeSort. This is very inelegant. And some tests produce really different output than before. Probably the sorting will still not be the same everywhere, since Polyhedra.m2 will not sort the rays and instead just accept the output from FourierMotzkin, hence changing the ordering of the cones. Thus, if lrs or cdd are used instead of FourierMotzkin.m2, this might break things again. This seems very fragile.

**Comment by lkastner** [comment]
Some final comments on my fixes in ToricVectorBundles.m2:
- It is still not clear why the ordering of cones is important. Maybe a
  different data structure should be used?
- There is a lot of old commented out code. Should this maybe be removed to
  improve readability? The file is under version control after all.
- All the fixes have been done without any understanding how this package
  works. I just adapted every call to Polyhedra.m2 to the new usage and removed the usage of cones as keys in HashTables.
- CacheTables are used in a weird way, more like MutableHashTables. The usage as in NormalToricVarieties would probably enhance readability.

**Comment by mikestillman** [comment]
All examples passed, but 3 tests failed, one in NormalToricVarieties, and 2 in the schenck book (could be the same issue).  I’ll isolate it, and post failing code here (but right now I am busy for the next few hours…)

**Comment by kathlenkohn** [comment]
I'm very busy until November 1, but I'll look into it in November!
Diane had some problems either way with the latest M2 update, so I'll try
this as well.

Am 05.09.2016 23:48 schrieb "lkastner" <notifications@github.com>:

**Comment by mikestillman** [comment]
Lars, I’m going to build it from scratch, test it.  Is it at the point where I should allow the pull request?

**Comment by lkastner** [comment]
I got one test failing in NormalToricVarieties.m2, which I could fix. The examples all worked for me. Did you already fix something?

Which package has the book examples?

**Comment by mikestillman** [comment]
The problems I had were in ‘make check’, where it runs stuff from the book examples, and flags changes.  The examples, I believe, ran to completion.

The ones that had issues were some of: packages/Macaulay2Doc/test/schenck-book-*

**Comment by lkastner** [comment]
I found schenck-book-2.m2 and fixed the usage there. I also added a few extra tests, to make sure that it still gives the right things.
```
make check
```
does not work for me unfortunately. I will make a reinstall tonight.

**Comment by mikestillman** [comment]
try make -k check, 

search for *** through the log.

**Comment by lkastner** [comment]
```
make -k check
```
reports many errors, but they seem not to be related to Polyhedra.m2. Does it work for you? I still have my submodules problem, even though I restarted + -compiled from scratch. I did --recurse-submodules when I cloned.

If it works for you now, it should be ok to accept the pull request.

**Comment by mikestillman** [comment]
make -k check
should report very few (i.e. zero) errors.  What errors is it reporting?

**Comment by lkastner** [comment]
It is just asking for gtest.h over and over, e.g.
```
src/test/Scanner.cpp:6:25: fatal error: gtest/gtest.h: No such file or directory
```
I don't have a gtest.h. I'll try to reconfigure and -build with enabling gtest as a build library.

**Comment by lkastner** [comment]
I configured with
```
FC=gfortran ../M2/configure --enable-download --enable-build-libraries="pari gtest"
```
but I still haven't got gtest.h. The final message I get after make -k check is
```
make[1]: Leaving directory '/home/user/M2/lars/check-configure'
make: Target 'check' not remade because of errors.
make: Leaving directory '/home/user/M2/lars'
```

**Comment by DanGrayson** [comment]
What is the status of this pull request?  Should I test it and install it?  If not, we could close it until it's ready.

**Comment by DanGrayson** [comment]
What's the point of introducing new packages with these names?
```
OldPolyhedra
OldToricVectorBundles
```

**Pull request merged**
