### PR TITLE
Merge pre-master branch and bump to development version 1.17.1.1

### PR DESCRIPTION
**Pull request by d-torrance**
I noticed that the `development` branch was still sitting at version 1.17.  The bump to 1.17.1 was still in `pre-master`, but it hasn't been merged yet.  This PR does the merge.

I also bumped `M2/VERSION` to 1.17.1.1, following the usual convention after a release.  Feel free to close if there are other plans!

### CODE REVIEW

**Comment by mahrud** [comment]
This sort of merge makes the history actively nonlinear ... @DanGrayson have you seen #1783?

**Comment by DanGrayson** [comment]
> This sort of merge makes the history actively nonlinear ... @DanGrayson have you seen #1783?

Yes, indeed.

**Comment by d-torrance** [comment]
I think ideally everything should go into `development` first, so there would never be a need to merge `pre-master` (or `master`) into it.

**Comment by mahrud** [comment]
Agreed. No commits or merges directly into master. There's also no need for pre-master. Development is already tested.

**Comment by DanGrayson** [comment]
> I think ideally everything should go into `development` first, so there would never be a need to merge `pre-master` (or `master`) into it.

That's the plan.

**Comment by DanGrayson** [comment]
> Agreed. No commits or merges directly into master. There's also no need for pre-master. Development is already tested.

No, development is not tested.

**Comment by mahrud** [comment]
> No, development is not tested.

Because you disabled it. Why did you disable it?

All that is needed is to test PR's, and once they pass and are merged into development, it should be tested one more time before being merged into master. Now, it can either be tested at midnight, so you can merge it in the morning, or you can test it after each PR that is merged into it.

There's no need for pre-master.

**Comment by d-torrance** [comment]
> > I think ideally everything should go into `development` first, so there would never be a need to merge `pre-master` (or `master`) into it.
> 
> That's the plan.

The bump to 1.17.1 happened in `pre-master`, and #1813 was merged into `master`.

**Comment by mahrud** [comment]
> The bump to 1.17.1 happened in `pre-master`, and #1813 was merged into `master`.

It may have been better to cherry-pick the version bump commits on top of development instead of merging.

**Comment by d-torrance** [comment]
> It may have been better to cherry-pick the version bump commits on top of development instead of merging.

Yeah...  oh well :(

**Comment by DanGrayson** [comment]
> > > I think ideally everything should go into `development` first, so there would never be a need to merge `pre-master` (or `master`) into it.
> > 
> > 
> > That's the plan.
> 
> The bump to 1.17.1 happened in `pre-master`, and #1813 was merged into `master`.

No, nothing happens in pre-master, except development getting merged in.  At least that's the plan.

**Comment by DanGrayson** [comment]
> > No, development is not tested.
> 
> Because you disabled it. Why did you disable it?
> 
> All that is needed is to test PR's, and once they pass and are merged into development, it should be tested one more time before being merged into master. Now, it can either be tested at midnight, so you can merge it in the morning, or you can test it after each PR that is merged into it.
> 
> There's no need for pre-master.

The reason for having pre-master and for not testing development is so pull requests get tested just one more time before being merged into master.  It was a big pain when 5 builds would be in progress simultaneously after pulling 5 pull requests, and it was a waste of cpu time.

**Comment by mahrud** [comment]
Okay, then have it be tested overnight, so you can merge in the morning. Or you can add a manual trigger instead, and run it whenever you want to merge into master.

There's no need for pre-master.

**Comment by DanGrayson** [comment]
Merging into pre-master is a manual trigger, and while that's building, it's useful that the development branch can advance, as usual, without interfering.

**Comment by mahrud** [comment]
> Merging into pre-master is a manual trigger, and while that's building, it's useful that the development branch can advance, as usual, without interfering.

But then you randomly forgot and bumped the version in pre-master? If your trigger messes up history so easily, maybe it's not worth it, but I give up. If you want nonlinear history, you have it.

**Comment by DanGrayson** [comment]
> > Merging into pre-master is a manual trigger, and while that's building, it's useful that the development branch can advance, as usual, without interfering.
> 
> But then you randomly forgot and bumped the version in pre-master? 

No, I don't think so.

> If your trigger messes up history so easily, maybe it's not worth it, but I give up. If you want nonlinear history, you have it.

Almost every pull request makes the history nonlinear, so we already have it.

**Comment by mahrud** [comment]
> No, I don't think so.

Yes, you did. Hence why this PR was necessary to begin with, as @d-torrance noted:

> The bump to 1.17.1 happened in `pre-master`, and #1813 was merged into `master`.

> Almost every pull request makes the history nonlinear, so we already have it.

Here is how to avoid that:
- open the menu next to the merge button:
image
- click "rebase and merge"

**Pull request merged**
