### PR TITLE
PHCpack fixes

### PR DESCRIPTION
**Pull request by antonleykin**
Should close
https://github.com/Macaulay2/M2/issues/1308
https://github.com/Macaulay2/M2/issues/1315

PHCpack version check implemented; derandomized only if --no-randomize; fixed the line that was breaking either numericalIrreducibleDecomposition or cascade

### CODE REVIEW

**Comment by DanGrayson** [comment]
Now it always gives an error if phc is not present, whereas it should silently accept that.
```
2020-06-23T20:18:30.7473749Z sh: 1: phc: not found
2020-06-23T20:18:30.7476994Z Which version of phc is in your execution path?
2020-06-23T20:18:30.7477115Z 
2020-06-23T20:18:30.7478539Z ../../../../../Macaulay2/packages/PHCpack.m2:1822:1:(2):[75]: error: expected PHCpack version 2.4.77 or higher
```

**Comment by DanGrayson** [comment]
Anton, here's an idea: at the top of the package, say that phc is present if and only if the program exists and has a suitable version number.  Later, when it's time to run it, if it isn't marked as present, give an error.

**Comment by antonleykin** [comment]
I think, I've implemented a version of what you proposed.

**Comment by DanGrayson** [comment]
Can you hush this output to stderr?
```
2020-06-24T22:43:54.4112841Z make: Entering directory `/home/runner/work/M2/M2/M2/BUILD/cicd/Macaulay2/packages/PHCpack-temporary'
2020-06-24T22:43:54.4116166Z cd PHCpack-temporary && /home/runner/work/M2/M2/M2/BUILD/cicd/usr-dist/x86_64-Linux-Ubuntu-18.04/bin/M2  -q --stop --silent -e errorDepth=3 -e debugLevel=0  -e "installPackage(\"PHCpack\", RemakeAllDocumentation => false, IgnoreExampleErrors => false, RerunExamples => false, CheckDocumentation => true, UserMode => false, Verbose => false, InstallPrefix => \"/home/runner/work/M2/M2/M2/BUILD/cicd/usr-dist/\", SeparateExec => true, DebuggingMode => true); exit 0"
2020-06-24T22:43:54.8486474Z sh: 1: phc: not found
2020-06-24T22:43:54.8520669Z Which version of phc is in your execution path?
2020-06-24T22:43:54.8521009Z 
```

**Comment by antonleykin** [comment]
See if all works now.
I'm curious: what version of phc triggered this?

**Comment by mikestillman** [comment]
What version of phc should we be using with this package?

**Comment by DanGrayson** [comment]
I had 2.4.67 until recently, and now I have 2.4.77.

**Comment by DanGrayson** [comment]
I seem to have screwed up your branch, @antonleykin , so will close this and make a pull request of my own.

**Pull request closed without merging**
