### PR TITLE
changed caching in minimalBetti

### PR DESCRIPTION
**Pull request by mahrud**
- **cached the ChainComplex, instead of Resolution, in minimalBetti**
- **simplified caching for res and minimalBetti of ideals**

### CODE REVIEW

**Comment by mahrud** [comment]
Hmm this is unfortunate, because the changes from Varieties package during the workshop also involve a lot of changes to Complexes. I was hoping there would be some communication when this was going to happen.

**Comment by mikestillman** [comment]
When I say: "as we speak", that means we are working on it.  Currently, on a branch, we can preload Complexes automatically, but it will still take some effort to tease out the nontrivial use of ChainComplex.  That said, what other changes do you envision for Complexes? (other than this and PR #3342 ?

**Comment by mahrud** [comment]
Those are the only ones where the work is already done, but I don't mind repeating the changes in this PR later. Only #3342 could be a lot more work if there are conflicts.

Other things involve future changes:
- retire `PruneComplex` and merge it in `Complexes` because `minimize` is currently too slow.
- we need `(resolution, Complex)` to be functorial, and I want to talk to you and Greg about how to do this.

**Comment by mahrud** [comment]
Ah, I don't think Mike wanted this to be merged ...

**Pull request merged**
