### PR TITLE
Updating the SimplicialComplexes package

### PR DESCRIPTION
**Pull request by ggsmith**
In collaboration with @bhersey1 and @sashahbc, this is a significant update to the ```SimplicialComplexes``` package.  It adds constructors for many classic examples, implements a new data type for simplicial maps, incorporates many improvements to the methods, improves interoperability with ```Polyhedra```, and completely overhauls the documentation.  Changes that break backwards compatiblity include changing the output of ```faces``` and ```facets``` from ```Matrix``` to ```List```, changing the output type of ```fVector``` from ```HashTable``` to ```List```, and replacing ```==``` with ```===``` for ```SimplicialComplexes```.

@diegcif, @parrilo : This pull request also makes some very minor changes to the ```Chordal``` package that reflect the changes in ```SimplicialComplexes```.

@ahhoefel : This pull request also makes some very minor changes to the ```EdgeIdeals``` package that reflect the changes in ```SimplicialComplexes```.

@dcookii : This pull request also makes some very minor changes to the ```Graphs``` package that reflect the changes in ```SimplicialComplexes```.

@jankoboehm : This pull request also makes some changes to the ```KustinMiller``` package that reflect the changes in ```SimplicialComplexes```.  In particular, the```Face``` class and related methods have been moved from ```SimplicialComplexes``` into this package.

@jchen419 : This pull request also makes some very minor changes to the ```Matroids``` package that reflect the changes in ```SimplicialComplexes```.

@gwynwhieldon : This pull request also makes some very minor changes to the ```Posets``` package that reflect the changes in ```SimplicialComplexes```.

@aadams22 : This pull request also makes some very minor changes to the ```ResolutionsOfStanleyReisnerRings``` package that reflect the changes in ```SimplicialComplexes```.

@dcookii : This pull request also makes some very minor changes to the ```SimplicialDecomposability``` package that reflect the changes in ```SimplicialComplexes```.

@eloisagrifo : This pull request also makes some very minor changes to the ```SpectralSequences``` package that reflect the changes in ```SimplicialComplexes```.

@alvisetrevisan : This pull request also makes some very minor changes to the ```ToricTopology``` package that reflect the changes in ```SimplicialComplexes```.

@d-torrance, @bbarwick, @bstone : This pull request also makes some very minor changes to the ```Visualiz``` package that reflect the changes in ```SimplicialComplexes```.

### CODE REVIEW

**Comment by mikestillman** [comment]
@DanGrayson @ggsmith Dan, these failing tests look like something more basic has failed, not related to this pull request (can't tell if this one is working, as it the build doesn't make it very far...)

**Comment by DanGrayson** [comment]
Yes, it seems to be a documentation issue.  I'll try to figure it out.

**Comment by ggsmith** [comment]
I wonder if it is related to some naming clashes between the various packages.  For example,```Graphs``` and ```EdgeIdeals``` have about 27 exported functions with the same name.

**Comment by DanGrayson** [comment]
This will fix it.

```diff
diff --git a/M2/Macaulay2/packages/SimplicialComplexes.m2 b/M2/Macaulay2/packages/SimplicialComplexes.m2
index c2821a46c..4e9e47187 100644
--- a/M2/Macaulay2/packages/SimplicialComplexes.m2
+++ b/M2/Macaulay2/packages/SimplicialComplexes.m2
@@ -29,7 +29,7 @@ newPackage(
 	 Email => "18az45@queensu.ca"}
      },
     Headline => "exploring abstract simplicial complexes within commutative algebra",
-    Keywords => {"simplicial complex",},
+    Keywords => {"simplicial complex"},
     PackageExports => { "Polyhedra" },
     AuxiliaryFiles => true,
     DebuggingMode => true
```

The error message should be improved.

**Pull request merged**
