### PR TITLE
"Ways to use" improvements

### PR DESCRIPTION
**Pull request by mahrud**
- add "Ways to use" for method Commands (e.g. help) and Manipulators (e.g. flush)
- add "Ways to use this method" for method keys

### CODE REVIEW

**Comment by pzinn** [comment]
this PR causes trouble in WebApp mode. specifically, `LATER` (is this a new feature? what is it for?) does not produce the correct output.

**Comment by pzinn** [comment]
I think the content of `LATER` should always be a `Hypertext` element, not just a string or sequence of strings.

**Comment by pzinn** [comment]
anyway I can't pinpoint when the problem appeared but my comment stands:
I think the content of `LATER` should always be a `Hypertext` element, not just a string or sequence of strings. e.g. 
```
text = if text =!= null and #text > 0 then text else if tag =!= opttag then LATER {() -> SPAN headline opttag};
```

**Comment by mahrud** [comment]
I'm pretty sure anything that can be rendered by html (or other output method) is fine. Do you know what document tag is causing an issue? I wonder if `headline` was returning null or something due to #2323?

**Comment by mahrud** [comment]
Here is a run on WebApp mode:
```m2
[mahrud@noether m2]$ M2 --webapp --silent
i1 : debug Core;
debug Core;
i2 : a = LATER {() -> "abcd"};
a = LATER {() -> "abcd"};
i3 : html a
html a

o3 = <pre style="display:inline">
&lt;pre style=&quot;display:inline&quot;>
abcd&lt;/pre></pre>
i4 : a
a

o4 = <pre style="display:inline">
abcd</pre>

o4 : <pre style="display:inline">
LATER</pre>
```
The main difference I notice here is the last output; where it's printing `LATER` instead of evaluating it.

**Comment by pzinn** [comment]
sorry about the successive edits making my point unclear. a screenshot is probably easier:
- before the suggested fix above:
before
- after:
after
notice the change of font in the LATER part

**Comment by pzinn** [comment]
ah, oops. `headline` does return `null` occasionally. `nonnull SPAN headline opptag` then?

**Comment by mahrud** [comment]
Sorry, I'm still not following the issue is related to the use of strings in `LATER`, or how the output you get is different.

That's a silly text to appear after `Degree`, by the way. Someone should combine the documentation of `matrix` and `(matrix, List)` and `[matrix, Degree]` I think.

**Comment by pzinn** [comment]
I'm not judging the content, just the form. in the first version the `LATER` text is output in `PRE` rather than the normal font.

**Comment by mahrud** [comment]
Or maybe that's not feasible the way `LATER` is designed, in which case yea your solution sounds good.

**Pull request merged**
