### PR TITLE
Method degree polynomial posets

### PR DESCRIPTION
**Pull request by fchapoton**
The main aim here is to add a method `degreePolynomial` to the Posets package.

Warning : I did my best to write correct code, but I could not test it.

Also tweaking the doc of `tuttePolynomial` and adding some accents to `Poincaré`

### CODE REVIEW

**Comment by DanGrayson** [comment]
All the tests have failed.

What prevents you from testing at home?

**Comment by fchapoton** [comment]
I have difficulties in compiling M2. I have now tried and fixed the proposed code using sagemathcell.

**Comment by fchapoton** [comment]
This seems to be working fine now. I hope I have not messed with the commits, which looks a bit strange here in github.

**Comment by fchapoton** [comment]
ooch, I tried to merge, and it got even worse in terms of modified files

**Comment by fchapoton** [comment]
ok, I have rebase and it is now showing the only modified file

**Comment by gwynwhieldon** [comment]
Also, that was just a suggestion. I'd also be fine with it being merged as
is.

**Comment by DanGrayson** [comment]
@fchapoton - what do you think of Gwyn's suggestion.  Could you do it easily?

**Comment by fchapoton** [comment]
I can do that, except that I do not know where it should go.. somewhere in the same file?

**Comment by DanGrayson** [comment]
Maybe Gwyn had a test in mind, in which case you could put it in `TEST /// ... ///` toward the end of the file.

**Comment by gwynwhieldon** [comment]
Yes, that's what I was thinking.

The tests start at line 6164 in the file, and the first two are (small,
easy to read) examples of tests for (respectively) a new constructor and
the equality operator, and a function on a poset.

In theory, the tests would be nicely in order matching the order of methods
in the package. In practice, I don't think that's true at all here, so just
throwing it down at the bottom of the tests would probably be best (but
above line 6695, where the package functionality and tests ends at "end;").

Best,

Gwyn

**Comment by fchapoton** [comment]
I have added a doctest on the boolean poset.

**Comment by gwynwhieldon** [comment]
Alright, that LGTM too.

**Pull request merged**
