### PR TITLE
fix #2950 + minor texMath

### LINKED ISSUE #2950: texMath MultigradedBettiTally
a minor issue, but the TeX formatting of `MultigradedBettiTally` is incorrect

### PR DESCRIPTION
**Pull request by pzinn**
I fixed #2950, though I'm still not sure whether `compactMatrixForm` is used appropriately, as mentioned in the comments.
I also threw in a bunch of small fixes, including an expression bug I introduced when removing `NonAssociativeProduct` (try `expression 0 * x`) and a double superscript bug.

### CODE REVIEW

**Comment by pzinn** [comment]
oh yeah, I pushed a fix of #2951 too. the olf, buggy, behaviour can still be reproduced with `read stdio`.

**Comment by pzinn** [comment]
don't merge yet, additional problem detected with `multigraded`, cf https://github.com/Macaulay2/M2/issues/2950. needs fixing.

**Comment by DanGrayson** [comment]
It's up to the ultimate user to set `compactMatrixForm`, which controls how matrices are printed.  The default value is `true`.  Are you setting it somewhere?

**Comment by pzinn** [comment]
this PR has nothing to do with `compactMatrixForm` whatsoever. I was pointing out in comments of https://github.com/Macaulay2/M2/issues/2950 that I suspected that the output of `MultigradedBettiTally` with/without `compactMatrixForm` was switched. Ultimately, it's a matter of taste, and I don't particularly care, just thought whoever wrote this code might want to check.

**Comment by mahrud** [comment]
It wasn't switched.

**Pull request merged**
