### PR TITLE
Remove engine documentation workflow

### PR DESCRIPTION
**Pull request by d-torrance**
It was creating a massive branch inside the repository.  Partially addresses #2586.

### CODE REVIEW

**Comment by DanGrayson** [comment]
I get variable results when I try to measure the size of the repository now: 806MB on Mac OS, 180MB on Debian.

**Comment by DanGrayson** [comment]
> I get variable results when I try to measure the size of the repository now: 806MB on Mac OS, 180MB on Debian.

Never mind -- I think it had to do with multiple remotes.   Now I get 139MB on both.

If there really is bloat in the repository, how will we get rid of it?

**Comment by d-torrance** [comment]
`git push origin :gh-pages` should do the trick

**Comment by DanGrayson** [comment]
According to the list at https://github.com/Macaulay2/M2/branches/all the branch named gh-pages doesn't exist.

**Pull request merged**
