### PR TITLE
Organizing quotring.m2

### PR DESCRIPTION
**Pull request by mahrud**
- reorganized quotring.m2
- updated printing of QuotientRings

### CODE REVIEW

**Comment by mahrud** [comment]
To be clear, I didn't change `isQuotientRing`. This PR is just organizing the codebase before future changes.

**Comment by DanGrayson** [comment]
What's the point of "reorganizing" existing code, Mahrud?

**Comment by mahrud** [comment]
> What's the point of "reorganizing" existing code, Mahrud?

So when I make a subsequent PR with substantial changes, the diff is just a few lines and not a whole file, and the PR is reviewed and merged in a reasonable time. While the diff looks like the whole file in this PR, you can check and confirm that nothing has substantially changed fairly easily when it's only reorganization. Does that make sense?

This is the case for this PR, but in general improving readability and auditing the code base after a decade or three is necessary.

**Comment by DanGrayson** [comment]
> So when I make a subsequent PR with substantial changes, the diff is just a few lines and not a whole file

What's the mechanism for producing this result?

**Comment by mahrud** [comment]
> What's the mechanism for producing this result?

How to view diffs?

**Comment by DanGrayson** [comment]
I mean, why would the diff be just a few lines later on?

**Comment by mahrud** [comment]
I think it's easiest to accept this PR and see the diff when I submit subsequent PRs.

**Comment by mahrud** [comment]
@DanGrayson @mikestillman this PR has no mathematical or algorithmic changes (the most significant change is removing the duplicate method I mentioned above). I opened it because I believe programming code is not so different than prose in a paper or book, and poorly organized prose makes it hard to read, understand, or improve. If this sort of contribution is not welcome, you can simply reject and close the pull request.

**Comment by mikestillman** [comment]
@mahrud Of course cleaning up code is welcome (if it is clear no bugs are being introduced).  I just got back last night from Stockholm, will be reviewing this soon!

**Comment by DanGrayson** [comment]
@mahrud -- could you repair the conflicts,please?

**Review by mikestillman — APPROVED** [review]
@DanGrayson Let's accept this as is.  It does make the file cleaner, and doesn't seem to introduce any bugs.  @mahrud Sorry it took a while for me to finally get to this!  Thanks for cleaning up this code.

**Pull request merged**
