### PR TITLE
Iterating over strings

### PR DESCRIPTION
**Pull request by d-torrance**
One nice thing in languages like Python is the ability to iterate over strings.  After all, they're just arrays of characters!

I've started implementing some string iteration features in the D language.  In particular, `toList`, `toSequence`, `for` loops, and `scan`.

Still to do:
- [x] `apply` (this is trivial if we want the output to be a `Sequence`, but a little trickier if we want the output to be another `String`)
- [ ] any other methods that might make sense?
- [x] documentation
- [x] unit testing

Opening a draft PR for comments in the meantime.

Looking forward into the future, it would be cool if we could define arbitrary types to be iterable so these things would work out of the box.

### CODE REVIEW

**Comment by d-torrance** [comment]
A quick example:


```m2
i1 : toList "foo"

o1 = {f, o, o}

o1 : List

i2 : toSequence "foo"

o2 = (f, o, o)

o2 : Sequence

i3 : for c in "foo" do print c
f
o
o

i4 : scan("foo", print)
f
o
o
```

**Comment by mahrud** [comment]
Have you seen `ascii`?
```m2
i1 : for i in ascii "foo" do print ascii i
f
o
o

i2 : scan(ascii "foo", print @@ ascii)
f
o
o
```

Here's a cool feature to have, though: the disadvantage here is that `ascii` pre-allocates the memory for an integer array, but a cool feature of more developed languages like Python is that they have iterators. It would be a very cool feature if M2 supported something like the `yield` keyword in Python, so you could have something like `for c in nextChar str` or `for p in nextPrime N`. This would require the interpreter to make a new call to that function on every cycle to get the next character or prime.

**Comment by DanGrayson** [comment]
Doug, I wonder whether your iteration will support unicode with utf8 encoding.  Mahrud has mentioned "ascii" -- there is also "utf8":
```m2

i14 : for i in utf8 "我是美国人。" do print i
25105
26159
32654
22269
20154
12290

i15 : for i in utf8 "我是美国人。" do print utf8 i
我
是
美
国
人
。
```

**Comment by d-torrance** [comment]
> PS: maybe this is what you're suggesting as well, in which case sorry for the explanation! I thought I'd mention it since `strtoseq` in the current draft also pre-allocates memory.

Yes, that's what I was thinking, too.  No worries!

> Doug, I wonder whether your iteration will support unicode with utf8 encoding. Mahrud has mentioned "ascii" -- there is also "utf8":

It doesn't yet.  :(

```m2
i1 : toList "我是美国人。"

o1 = {�, �, �, �, �, �, �, �, �, �, �, �, �, �, �, �, �, �}

o1 : List
```
For that matter, neither does subscripting:

```m2
i2 : "我是美国人。"_0

o2 = �
```

**Comment by DanGrayson** [comment]
Maybe we should have various subtypes of String: UnicodeString and AsciiString.

**Comment by d-torrance** [comment]
Multiple types sound confusing to me...  Since ASCII is a subset of Unicode, wouldn't just the latter suffice?

`length` also doesn't return the expected thing for Unicode strings:

```m2
i3 : #"我是美国人。"

o3 = 18
```

**Comment by DanGrayson** [comment]
> Multiple types sound confusing to me... Since ASCII is a subset of Unicode, wouldn't just the latter suffice?

You may actually wish to know whether a string consists just of ascii characters.  Your remark is useful, however,
for it suggests that AsciiString should be a subtype of UnicodeString.

You remark also suggests sticking with just String and regarding all strings as sequences of unicode characters.  However, there might be a use for sequences of bytes.  Hmm, maybe not.

> 
> `length` also doesn't return the expected thing for Unicode strings:
> 
> ```m2
> i3 : #"我是美国人。"
> 
> o3 = 18
> ```

Fixing that would be possible if UnicodeString were introduced.

**Comment by mahrud** [comment]
There are two stagnant issues regarding unicode: #1069, #1186
I'm certain that focusing on having allocation-less iterators would be far more useful to virtually all M2 users than supporting Chinese characters.

**Comment by pzinn** [comment]
maybe not chinese characters but I do like using greek letters for my ring variables.

**Comment by mahrud** [comment]
> maybe not chinese characters but I do like using greek letters for my ring variables.

You can already do that.

Seems like the idea I described above is not the same as Doug's intention for this PR.

**Comment by pzinn** [comment]
> > maybe not chinese characters but I do like using greek letters for my ring variables.
> 
> You can already do that.
> 
> Seems like the idea I described above is not the same as Doug's intention for this PR.

you can, but as mentioned in https://github.com/Macaulay2/M2/issues/1069, formatting will be incorrect. In Standard of course -- in WebApp mode everything looks perfect...

**Comment by mahrud** [comment]
I didn't mean to sidetrack the point of this PR. I mentioned those issues so this discussion of unicode characters can move there, not the other way around!

**Comment by d-torrance** [comment]
> Seems like the idea I described above is not the same as Doug's intention for this PR.

Initially, not for this PR, no.  Adding support for iterables does seem like the best way to make these features work for unicode strings, though, so I've been considering starting over from scratch.

But at this point, I think I'm going to keep it essentially the way it is, for consistency with the current behavior of subscripting and `length` with strings, and how `for`, `scan`, and `apply` are currently implemented (they need sequences).

But looking forward, whenever #1904 is implemented, then I would absolutely like to see string iteration use that instead, possibly using [CharacterIterator](https://unicode-org.github.io/icu/userguide/strings/characteriterator.html) from ICU.

**Comment by d-torrance** [comment]
I realized that it made no sense for `apply` to return a string when it had a string argument as there's no guarantee that the function we're applying will returns characters/strings that could be glued back together into a string!  So it returns a sequence.

I think this is in pretty good shape now, so I've removed the draft status.

**Comment by mahrud** [comment]
Is there anything that isn't accomplished by inserting `ascii` or `utf8` by the user? If not, I feel like you could simply mention in the documentation that strings can be turned into a list using those functions.

**Comment by d-torrance** [comment]
> Is there anything that isn't accomplished by inserting `ascii` or `utf8` by the user? If not, I feel like you could simply mention in the documentation that strings can be turned into a list using those functions.

It's true that those accomplish the task, but it seems unnecessarily complicated since we need to call them twice -- once to convert each character to an integer and again to convert back -- `ascii \ ascii "foo"` vs. just `toList "foo"`.

**Comment by mahrud** [comment]
You can define only `toList String := List => s -> utf8 \ utf8 s`, then the rest would follow by adding `toList`.

**Comment by d-torrance** [comment]
> You can define only `toList String := List => s -> utf8 \ utf8 s`, then the rest would follow by adding `toList`.

That doesn't work since `toList` is defined in the interpreter:

```m2
i1 : toList String := List => s -> utf8 \ utf8 s

o1 = List => -*Function[stdio:1:28-1:43]*-

o1 : Option

i2 : toList "foo"
stdio:2:1:(3): error: expected list, sequence, or set

```

And even if it did, we'd still need to include `toList` in `for`, `scan`, and `apply`, which is what I was trying to avoid in the first place.

**Comment by mahrud** [comment]
Ah, I forgot that it's not an actual method. I'm only skeptical that the improvement of saving the user the trouble of typing `toList` (assuming it is defined in the interpreter) is worth the added complexity. In particular, the proposed solution is strictly less time & memory efficient than using an index to loop over a string. That's just my preference though, so feel free to ignore.

**Comment by d-torrance** [comment]
I agree that the implementation isn't ideal, but the current code for `for`, `scan`, and `apply` code all expect sequences, which are tagged arrays.  Strings aren't tagged array, though, so copying them over into a new sequence seemed to be the simplest way to add the feature without rewriting a bunch of other things.  (Which should definitely be rewritten in the long term for iterators!)

**Comment by DanGrayson** [comment]
If scanning over strings is useful, then modifying "for" to accept strings would be useful, too.

**Comment by d-torrance** [comment]
> If scanning over strings is useful, then modifying "for" to accept strings would be useful, too.

Yup!  That's https://github.com/Macaulay2/M2/pull/1897/commits/c38b45bfcd070c356515b5b79b88d446b89f82a5

**Pull request merged**
