### PR TITLE
Update SpectralSequences.m2

### PR DESCRIPTION
**Pull request by n-m-g**

### CODE REVIEW

**Comment by mahrud** [comment]
In general, you don't need to open new pull requests. You can push (or force push) to the same branch to update an existing pull request. I closed the other one for you.

**Comment by n-m-g** [comment]
Thanks.  I’ve updated the AbstractSimplicialComplexes in my branch.  Can you see those changes?  Do I need to issue a pull request for that?

Best,
Nathan

**Comment by n-m-g** [comment]
I've closed this as the SpectralSequences update has been pushed elsewhere and the AbstractSimplicialComplexes pull request is continuing on another pull request.

**Comment by mahrud** [comment]
I don't see another pull request with SpectralSequences currently.
@mikestillman are you going to include this in the complexes PR?

**Comment by n-m-g** [comment]
Hi,

Again, I am happy to issue a new pull request with the updated SpectralSequences package but I believe that the updates we made have (at the request of Mike and Greg) already been pushed into the development branch.  Again, we are limited somewhat with what we can do to make everything entirely forward compatible because we don’t know 100% what the “core static” features of the “Complexes” package actually will be.  The other main issue is the current “Complexes” compatibility with the existing “SimplicialComplexes” package.  The intent is to make additional updates in due time as our time allows but also as things become in a more static form within the M2 system.

Best,
Nathan

**Pull request closed without merging**
