### PR TITLE
fixed an unidentified "kk"

### PR DESCRIPTION
**Pull request by eisenbud**
Thought I'd gotten rid of the last of those -- sorry!

### CODE REVIEW

**Comment by DanGrayson** [comment]
You can verify the tests work with

     check "MCMApproximations"

**Comment by eisenbud** [comment]
Of course I did that. But I don't know a good way of starting M2 within emaics *without* invoking my .init file -- how should one do that?

Thanks,

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Comment by DanGrayson** [comment]
Add "-q" to the M2 command line.  To do that in emacs, use C-u f12 instead
of f12 to start M2.
It will then give you an opportunity to edit the command line for M2.

**Comment by eisenbud** [comment]
Thanks! -- D
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Pull request merged**
