### PR TITLE
David dev

### PR DESCRIPTION
**Pull request by eisenbud**
pull request for new CompleteIntersectionResoluitions, MCMApproximations, and 2 packages from Warwick workshop, RandomIdeals (note plural; RandomIdeal has been removed) and ResidualIntersections. 

Brandon Stone is still working on Depth package

### CODE REVIEW

**Comment by DanGrayson** [comment]
When adding or renaming packages, it is important to update the file `=distributed-packages`, too.

**Comment by eisenbud** [comment]
I'll do so as soon as I have a connection...

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Comment by eisenbud** [comment]
OK, I edited that file, committed and pushed. I thought I would have to start a new pull request, but from what I saw it seemed to me now included in the yet-unmerged pull request from yesterday. Correct?

Thanks,

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Comment by DanGrayson** [comment]
Yes, pull requests always reflect the current state of the branches specified when the pull request was made.

**Comment by DanGrayson** [comment]
David, can resolve the conflicts in your pull request?  That's done by pulling (to your branch), repairing the conflicts, and pushing.

**Comment by eisenbud** [comment]
OK, conflicts fixed, did add, commit, push as instructed. All seemed to work...

Thanks,

David


--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Comment by eisenbud** [comment]
Working on CompleteIntersectionResolutions again. Should be done this weekend.

**Comment by eisenbud** [comment]
Done -- again! -- with CompleteIntersectionResolutions.m2

**Pull request merged**
