### PR TITLE
Bertini.m2 Release

### PR DESCRIPTION
**Pull request by JoseMath**
bertiniTrackHomotopy is a user homotopy of type 1.
The functions here do not have to be polynomials. We should account for
this.
bertiniUserHomotopy is a user homotopy of type 2.
The polynomials here can be defined over product spaces (Use
AffVariableGroup and HomVariableGroup). The parameters must be
specified in terms of a path variable.

### CODE REVIEW

**Comment by DanGrayson** [comment]
I get this error when running `installPackage "Bertini"`:
```
Macaulay2/m2/debugging.m2:20:6:(1):[12]: error: internal error: documentation node not processed yet: B'Exe
```
Do you?

I suspect you are doing something fishy with B'Exe and BExe.

**Comment by DanGrayson** [comment]
See my previous message, @JoseMath .  We'd to issue a release soon.

**Comment by JoseMath** [comment]
I see--yes I get this error to. I need to delete these changes from the branch as many of the changes were unnecessary and just complicated things. 
The previous #596 everything seemed to go well, correct?
-Jose

**Comment by DanGrayson** [comment]
Yes, that was merged and has been working fine.

**Comment by DanGrayson** [comment]
We'll release 1.9.3 soon, so please resolve the issues if you want your changes included.

**Comment by DanGrayson** [comment]
If you could resolve the conflicts and fix up the pull request, we could take a look at this again.

**Comment by mikestillman** [comment]
What is the status of this pull request?

**Comment by DanGrayson** [comment]
@JoseMath - we are wondering whether you will update this pull request before we release 1.11

**Comment by mikestillman** [comment]
@JoseMath How close is this pull request to being ready to be considered?

**Pull request closed without merging**
