### PR TITLE
Varieties: reorganizing varieties.m2

### PR DESCRIPTION
**Pull request by mahrud**
This is the first of a sequence of PR's towards a Varieties package.
- organized variety.m2 (no mathematical changes)
- moved randomKRationalPoint to genmat.m2
- changed codim to work for any Variety
- set typical value of (variety, EmbeddedProjectiveVariety)

The changes to varieties.m2 look like a lot, but are purely reorganization/non-mathematical and will make reviewing future changes easier.

### CODE REVIEW

**Comment by mahrud** [comment]
@ggsmith @mikestillman could you review this PR? There are a lot more changes to come.

**Comment by mikestillman** [comment]
@mahrud Will do!

**Comment by mikestillman** [comment]
@ggsmith @mahrud Did this get the OK from your group?  Should I merge it?

**Comment by mikestillman** [comment]
@DanGrayson I'm confused, did you accept this pull request?  It is still open?

**Comment by DanGrayson** [comment]
> @DanGrayson I'm confused, did you accept this pull request? It is still open?

Yes, I merged it, and it's closed.

**Pull request merged**
