### PR TITLE
Typos abc packages

### PR DESCRIPTION
**Pull request by fchapoton**
some typos in A*-C* packages

### CODE REVIEW

**Comment by DanGrayson** [comment]
You've accidentally changed the emacs submodule in commit e59ba9a827537762712db9da834f10e7fd1cf39d 👍 
```
commit e59ba9a827537762712db9da834f10e7fd1cf39d
Author: Frédéric Chapoton <chapoton@unistra.fr>
Date:   Sat Jan 16 14:19:27 2021 +0100

    typos in A-C packages

diff --git a/M2/Macaulay2/editors/emacs b/M2/Macaulay2/editors/emacs
index 8128eadca..310601c59 160000
--- a/M2/Macaulay2/editors/emacs
+++ b/M2/Macaulay2/editors/emacs
@@ -1 +1 @@
-Subproject commit 8128eadcadcf9628955c2f338c67d8c1bb14ced3
+Subproject commit 310601c59196cd70cc105191ce8771676c25f5b4
...
```

Can you put it back?

**Comment by fchapoton** [comment]
hopefully fixed now. Sorry for the mistake. I do not understand why the development branch contains non-commited files. Should I use another base branch for my work ?

**Comment by fchapoton** [comment]
It seems that this is not fixed. My git understanding may not suffice for the task.

**Comment by DanGrayson** [comment]
I'll fix it.

Typically the way the problem arises is that you pull from one of our branches, and it changes one of the submodules.  But the submodule doesn't really change until you do `git submodule update`.  If you omit that step, then `git status` shows the submodule has "new commits".  Then if you use `git commit` with the `-a` option, you'll commit those changes.

**Pull request merged**
