### PR TITLE
Add "member" as alias for "isMember" for RRi's

### PR DESCRIPTION
**Pull request by d-torrance**
As suggested by Luke Oeding at MAAG.

### CODE REVIEW

**Comment by d-torrance** [comment]
Converting to a draft for now, as after some discussion at MAAG, there are better solutions.  One possibility that came up is to convert `member` to `isMember` everywhere, and maybe add `member` as a synonym for now, possibility to be removed at some point.

**Comment by mahrud** [comment]
fwiw I prefer `isMember` and `isMutable` over `member` and `mutable` as a convention.

**Comment by d-torrance** [comment]
I've updated this so that there's only one method, `isMember`, with `member` as a synonym.  I only bothered changing instances in `Core`.

**Comment by d-torrance** [comment]
I went ahead and also switched `mutable` -> `isMutable` (retaining `mutable` as a synonym) and also fixed a display issue with an error I ran into while working on this:

### Before
```m2
i1 : foo = 2

o1 = 2

i2 : export{"foo" => "bar"}
stdio:2:1:(3): error: symbol intended as exported synonym already used internally: "foo"
new FilePosition from {"stdio",1,0,1,3,$: it was used here
```

### After
```m2
i1 : foo = 2

o1 = 2

i2 : export {"foo" => "bar"}
stdio:2:1:(3): error: symbol intended as exported synonym already used internally: "foo"
stdio:1:0-1:3: it was used here
```

**Comment by DanGrayson** [comment]
Let's deprecate "member".  If code out there runs "member", there should be an error message stating that it has been replaced by "isMember".

**Comment by d-torrance** [comment]
> Let's deprecate "member". If code out there runs "member", there should be an error message stating that it has been replaced by "isMember".

What about `mutable`?  Should using it also raise an error saying to use `isMutable`?

**Comment by mahrud** [comment]
Isn't it a bit rushed to deprecate them without warning, 2 weeks before a release?

**Comment by DanGrayson** [comment]
> Isn't it a bit rushed to deprecate them without warning, 2 weeks before a release?

No, the error message is the warning.

**Comment by DanGrayson** [comment]
> What about `mutable`? Should using it also raise an error saying to use `isMutable`?

Good idea.

**Comment by d-torrance** [comment]
Why not a warning instead of an error?  Maybe we could even introduce a function like Elips's `make-obsolete`:

```m2
makeObsolete = method()
makeObsolete(Symbol, Function, String) := (oldfunc, newfunc, ver) -> (
    oldfunc <- x -> (
	printerr("warning: the function ", format toString oldfunc,
	    " is obsolete since ", ver, "; use ", format toString newfunc,
	    " instead.");
	newfunc x);)
```

Which gives:

```m2
i3 : foo = () -> "Hello, world!"

o3 = foo

o3 : FunctionClosure

i4 : makeObsolete(bar, foo, "1.22")

i5 : bar()
 -- warning: the function "bar" is obsolete since 1.22; use "foo" instead.

o5 = Hello, world!
```

Then we could just put `makeObsolete(member, isMember, "1.22")` and `makeObsolete(mutable, isMember, "1.22")` somewhere to warn folks without breaking a bunch of code.

**Comment by DanGrayson** [comment]
But we want to break the code -- that's the only reliable way to replace all  the uses of "member" in our own code.

**Comment by d-torrance** [comment]
I think we should break the code eventually -- warn users for a year or so to give them time to switch and then remove `member` and `mutable` after that.

**Pull request merged**
