### PR TITLE
Add section ring functionality

### PR DESCRIPTION
**Pull request by thelongdiv**

### CODE REVIEW

**Comment by DanGrayson** [comment]
One test failed for me:
```
-- -*- M2-comint -*- {* hash: 100344856 *}

i1 : --/Users/dan/src/M2/M2-Macaulay2/M2/Macaulay2/packages/SectionRing.m2:464: location of test code
     
     R = QQ[x,y,z]/ideal(x^3+y^3-z^3);

i2 : I = ideal(x,y-z);

o2 : Ideal of R

i3 : assert( globallyGenerated(I) == 1)
stdio:5:1:(3): error: assertion failed
```

**Comment by thelongdiv** [comment]
You are write.  I will update the file.

**Comment by DanGrayson** [comment]
Your most recent commit created a file `SectionRing.m2` in the wrong directory, instead of updating the one you had before.

**Comment by thelongdiv** [comment]
I made the changes, deleting the extra file and modifying the file in the correct directory, as well as updating the =distributed-packages file.

**Pull request merged**
