### PR TITLE
Use PPA for additional Ubuntu packages for GitHub Actions

### PR DESCRIPTION
**Pull request by d-torrance**
As discussed in #1639.

### CODE REVIEW

**Comment by d-torrance** [comment]
Hrm, something's not working:

```
/bin/sh: 1: cd: can't cd to /home/runner/work/M2/M2/M2/BUILD/build/usr-host/lib
make[1]: *** [install-dynamic-libraries] Error 2
make: *** [all-in-libraries] Error 2
```

**Comment by DanGrayson** [comment]
> Hrm, something's not working:
> 
> ```
> /bin/sh: 1: cd: can't cd to /home/runner/work/M2/M2/M2/BUILD/build/usr-host/lib
> make[1]: *** [install-dynamic-libraries] Error 2
> make: *** [all-in-libraries] Error 2
> ```

Probably that directory doesn't exist, because no dynamic libraries got installed (for the first time).  Try this:

```diff
diff --git a/M2/libraries/Makefile.in b/M2/libraries/Makefile.in
index b16219af3..b8423eea5 100644
--- a/M2/libraries/Makefile.in
+++ b/M2/libraries/Makefile.in
@@ -34,12 +34,14 @@ install-dynamic-libraries:
 	: installing sharable library files in @pre_librariesdir@
 	rm -rf @pre_librariesdir@
 	@INSTALL@ -d @pre_librariesdir@
-	cd $(BUILTLIBPATH)/lib &&					\
-	   for i in *.dll *.so.* *[0-9].dylib ;				\
-	   do if [ -e $$i ] ;						\
-	      then @TAR@ cf - $$i | @TAR@ xfv - -C @pre_librariesdir@ ;	\
-	      fi ;							\
-	   done
+	if test -d $(BUILTLIBPATH)/lib ;					\
+	then cd $(BUILTLIBPATH)/lib &&						\
+		for i in *.dll *.so.* *[0-9].dylib ;				\
+		do if [ -e $$i ] ;						\
+		   then @TAR@ cf - $$i | @TAR@ xfv - -C @pre_librariesdir@ ;	\
+		   fi ;								\
+		done ;								\
+	fi
 ifeq (@SHARED@,yes)
 ifneq (@BUILDLIBLIST@,)
 all: install-dynamic-libraries
```

**Comment by d-torrance** [comment]
> > Hrm, something's not working:
> > ```
> > /bin/sh: 1: cd: can't cd to /home/runner/work/M2/M2/M2/BUILD/build/usr-host/lib
> > make[1]: *** [install-dynamic-libraries] Error 2
> > make: *** [all-in-libraries] Error 2
> > ```
> 
> Probably that directory doesn't exist, because no dynamic libraries got installed (for the first time). Try this:

Yeah, that was it.  I just pushed an equivalent commit that just skips that target if gtest is the only built library.

**Comment by d-torrance** [comment]
> This is sort of indirect. Try the fix I proposed.

Sounds good.  Your fix also works for any other libraries that, like gtest, may not install anything into that directory.

**Comment by d-torrance** [comment]
We're down to just building nauty now!

```
configure: using BUILDLIBLIST  = 
configure: using BUILDSUBLIST  = 
configure: using BUILDPROGLIST =  nauty
configure: using BUILDLIST     =  nauty
configure: using BUILD_ALWAYS  = 
```

**Comment by DanGrayson** [comment]
> We're down to just building nauty now!
> 


Very good.  Is there any hope for not building nauty?

**Comment by d-torrance** [comment]
> > We're down to just building nauty now!
> 
> Very good. Is there any hope for not building nauty?

I think we can probably switch the check for version 2.7 over to just see whether `nauty-biplabg` throws an error not.  Based on my experiences with #1408, it seems like we'll either always encounter the error or we'll never encounter it.  The Ubuntu 20.10 package was the only one that I ever got it on -- it seemed to work just fine everywhere else.  (And fortunately, version 2.7 migrated to Ubuntu before 20.10 was released, so it's not even an issue there any more!)

**Comment by d-torrance** [comment]
Hurray!

```
configure: using BUILDLIBLIST  = 
configure: using BUILDSUBLIST  = 
configure: using BUILDPROGLIST = 
configure: using BUILDLIST     = 
configure: using BUILD_ALWAYS  = 
```

**Comment by mahrud** [comment]
It's interesting that CMake builds still finish faster, despite the fact that I've set higher minimum versions for a few libraries and so they compile more stuff. Ccache is really magic.

**Comment by DanGrayson** [comment]
That's strange: github won't show me why that one check failed.

**Comment by DanGrayson** [comment]
> It's interesting that CMake builds still finish faster, despite the fact that I've set higher minimum versions for a few libraries and so they compile more stuff. Ccache is really magic.

What does it cache?  Do the logs show it?

**Pull request merged**
