### PR TITLE
Some minor update to SpecialFanoFourfolds and SparseResultants

### PR DESCRIPTION
**Pull request by giovannistagliano**

### CODE REVIEW

**Comment by DanGrayson** [comment]
Giovanni, the diff doesn't match the description.  In particular, your pull requests seems to include commits not by you.  Could you merge with "development" and push?

**Comment by mahrud** [comment]
> Giovanni, the diff doesn't match the description. In particular, your pull requests seems to include commits not by you. Could you merge with "development" and push?

This is because earlier you merged the FastLinAlg PR directly into master, so pull requests that started with master at that point were actually ahead of development:

From https://github.com/Macaulay2/M2/pull/1495#issuecomment-695782339:
>> @DanGrayson was this intentionally merged directly into master?
>
> Oops, no.  Oh, well, no harm done.

In particular, if you look at only the last commit in this PR you'll see the right diff.

**Comment by mahrud** [comment]
Fixed it.

**Comment by giovannistagliano** [comment]
Hi, is it solved then? or do i have to do something? I had noticed strange interference with other commits from @kschwede and others...

**Comment by DanGrayson** [comment]
All is well.

**Comment by giovannistagliano** [comment]
OK, thanks!

**Pull request merged**
