### PR TITLE
Add support for entering integers in binary, octal, and hexadecimal

### PR DESCRIPTION
**Pull request by d-torrance**
For example:

```m2
i1 : 0b10101

o1 = 21

i2 : 0o755

o2 = 493

i3 : 0xdeadbeef

o3 = 3735928559
```

### CODE REVIEW

**Comment by jchen419** [comment]
Hi Doug, do you know if base conversion between base 10 and an arbitrary (integer) base already exists in M2?

**Comment by d-torrance** [comment]
> Hi Doug, do you know if base conversion between base 10 and an arbitrary (integer) base already exists in M2?

I don't believe so, no.

**Comment by jchen419** [comment]
Hmm, OK, thanks - maybe a future feature request!

**Comment by DanGrayson** [comment]
Or maybe a current feature request...

**Pull request merged**
