### PR TITLE
WIP: Update to Dmodules package

### PR DESCRIPTION
**Pull request by mahrud**
This is still a work in progress, but as requested added this PR to track progress.
See https://github.com/Macaulay2/Workshop-2019-Minneapolis/projects/2 for the status.

Note: the work is being done on the Dmodules branch of the Workshop-2019-Minneapolis repository, but in order to make this PR I added that branch to my own fork of this repository and made the PR from there. I will keep the branch updated with the original branch.

### CODE REVIEW

**Comment by antonleykin** [comment]
@mahrud Perhaps it's time to update from 
https://github.com/Macaulay2/Workshop-2019-Minneapolis/tree/Dmodules
and finalize this PR.

**Comment by mahrud** [comment]
@antonleykin I updated the PR. However, I don't think the PR will be ready before the coding sprint in March. If you'd like, I can close the PR for now and reopen it later.

**Comment by antonleykin** [comment]
It's true that not all work planned is done... but there are some bug fixes, so it would be good to pull in the changes. 
Are there any major problems? E.g., tests failing?

**Comment by DanGrayson** [comment]
Well, should I pull it?

**Comment by antonleykin** [comment]
Please do.

**Comment by mahrud** [comment]
Not yet though. Sorry for the delay, I've been trying to get a few packages updates but I have been having trouble compiling with the changes. I'll finish my work and submit tonight.

**Comment by mahrud** [comment]
I think I was doing something silly with incorrect rebasing. Again, sorry for the delay. It should be good now.

**Pull request merged**
