### PR TITLE
polarize(MonomialIdeal) function, documentation update, and topcom build issue

### PR DESCRIPTION
**Pull request by lilysilverstein**
It was easiest for me to combine these three separate issues into a single pull request, hope that is okay.

1) Adding a function and documentation for polarizing a monomial ideal. This code is slightly modified from the Computations... book. It would be better for the function to be called "polarization" instead of "polarize," but this creates a conflict with the book. Is there a better way to resolve this than the name change?

2) Some recent documentation page rewrites, specifics are in the commit messages. Additionally, these should close issues #695 and #651 

3) Commented out a line from the topcom configure.ac problem which caused me to be unable to build from source. When someone has the software SoPlex installed, as I do, this line checks that SoPlex exists and then demands nonexistent files from an older version of SoPlex. Not finding them causes the entire build to fail. Simply removing the command seems to fix the problem.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Edit the file again, in the build directory corresponding to M2/libraries/topcom/ run "make diffs", take the resulting file and put the part of it that corresponds to your change into the file M2/libraries/topcom/patch-0.17.8 .  Test it with "make" after "make clean" in that same build directory.

> Oof, I just realized the Topcom configure file is generated during the build. Force committing the manually edited and usually git-ignored .ac file is surely wrong... What is the right way to address the problem?

**Comment by DanGrayson** [comment]
We'll wait for you to let us know that the pull request is ready to consider once again.

**Comment by lilysilverstein** [comment]
Thanks for your instructions, I changed the patch file as described and it
works on my computer. Please consider the pull request again

**Comment by mikestillman** [comment]
@DanGrayson are you ok with accepting this pull request yet?

**Comment by DanGrayson** [comment]
Mike, I'm busy with other things, so if it looks okay to you after testing, go ahead.

**Comment by mikestillman** [comment]
Ok, compiling it all now!

**Comment by mikestillman** [comment]
Thanks @lilysilverstein , the doc changes are very nice!

I'm going to accept the pull request, but first I'd like your thoughts on the following:

  One thing that might be nice to add to the "llists and sequences" page might be to also mention:
`for a in L list a+1`
`for a in L do print a`
and perhaps things like:
`for a in L list if a === null then continue else a`
Basically, the for loop over a list can be used instead of apply, scan, select, and is sometimes clearer in code. (break also works in here).  "/" and "\" are still very useful, and my favorites for when they apply.

Did you consider this, and decide it shouldn't be included there?  If so, fine, if not, this would be useful.  That is an incredibly nice page by the way, as are the others you have added.

We can either accept the pull request and change that later, or you can change that, and then I'll accept the pull request after, or tell me if shouldn't be there (but I think it would be good to be there, unless you have a good reason!).  Your choice.

**Comment by mikestillman** [comment]
@DanGrayson , can you comment on this aspect of (the first comment on) this pull request:

Adding a function and documentation for polarizing a monomial ideal. This code is slightly modified from the Computations... book. It would be better for the function to be called "polarization" instead of "polarize," but this creates a conflict with the book. Is there a better way to resolve this than the name change?

**Comment by DanGrayson** [comment]
I think we want the book to continue to work, and a name change is a good way to achieve that.

**Comment by DanGrayson** [comment]
No, currently there is no function named "polarize" or "polarization".  One of the chapters of the book has code that defines a function called "polarization".  That code will break if M2 ever defines such
a function, because the assignment to the variable "polarization" will fail.

**Comment by lilysilverstein** [comment]
@mikestillman Your suggestion is great, I simply overlooked it. I say accept the pull request as is (pending consensus on polarize), since I might not have time to work on documentation this week. Actually, the "lists and sequences" overview was part of my last pull request and is already in the current release. The reason it shows up here is that I reorganized some files by moving content to individual files in Macaulay2Doc/functions/. So the for...list description will have to be added after the fact anyway. I will put it on my to do list.

Regarding polarization, Mike has pointed out that a noun is usually preferred over a verb for a function like this, since a verb might misleadingly suggest that the function modifies its input. We could also consider other names for this function, like squarefreePolarization or idealPolarization. I have no strong feelings about the name, but went with polarize for brevity and auto-complete reasons. I'd love to find a better way to resolve the book/core name clash, but I haven't been able to think of one.

**Comment by mikestillman** [comment]
I think polarize is fine.  Perhaps the documentation should also include the string "polarization" as a key pointing to this node.  But I think I'm going to just accept the request as is.

**Pull request merged**
