### PR TITLE
Quickfix for capture

### PR DESCRIPTION
**Pull request by mahrud**
Fixes the issue that was preventing github actions from using capture for tests (see https://github.com/Macaulay2/M2/issues/1708#issuecomment-748277761). The problem was that a commented line at the top contained `/home/runner/...`, which matched `run`. We should see some speedup in the 4-hr long autotools build now. Also see: #1689

### CODE REVIEW

**Comment by mahrud** [comment]
There is definitely a significant time saving, such as here:
```m2
[mahrud@noether build]$ ./M2 -q --no-preload -e 'elapsedTime check "ConformalBlocks"; exit 0'
Macaulay2, version 1.17.0.1
 -- capturing check(0, "ConformalBlocks") from source:
   ../../Macaulay2/packages/ConformalBlocks.m2:938:1:                        -- 0.0943625 seconds elapsed
...
 -- 0.883614 seconds elapsed
[mahrud@noether build]$ M2 -q --no-preload -e 'elapsedTime check "ConformalBlocks"; exit 0'
Macaulay2, version 1.16.99
-* running test 0 of package ConformalBlocks in file:
   /usr/local/share/Macaulay2/ConformalBlocks.m2:939:1:
   rerun with: check_0 "ConformalBlocks" *-
...
 -- 11.5468 seconds elapsed
```
But they're being counteracted by other effects.

**Comment by mahrud** [comment]
I think the issue was that the random seed is set to zero by default when a subprocess starts, so now I'm setting it in `capture` as well.

**Comment by mahrud** [comment]
@DanGrayson I think this is done. There's is finally some reasonable time savings (about 7min).

The following packages are the only ones where the runtime is slower by that number of seconds:
```m2
(4.98, Saturation),
(7.35, SpecialFanoFourfolds),
(7.98, ToricVectorBundles),
(8.51, OldToricVectorBundles),
(14.87, QthPower),
(111.99, Polyhedra)
```

**Comment by DanGrayson** [comment]
> @DanGrayson I think this PR is done. There's is finally some reasonable time savings (about 7min).
> 

What about the net-printing bug?

**Comment by mahrud** [comment]
> What about the net-printing bug?

I have pushed a fix for it, but there's a small bug that I can't figure out:
```m2
i10 : last capture("K = ZZ/101\nA = matrix\"1,2,3,4;1,3,6,10;19,7,11,13\" ** oo", UserMode => false)

o10 = 
      i1 : K = ZZ/101

      o1 = K

      o1 : QuotientRing

      i2 : A = matrix"1,2,3,4;1,3,6,10;19,7,11,13" ** oo

      o2 = | 1  2 3  4  |
        | 1  3 6  10 |
        | 19 7 11 13 |

                   3       4
      o2 : Matrix K  <--- K

      i3 : 
```
It must have to do with the line that I added in `stdio.d`, but I'm not sure what's the correct fix.

**Comment by d-torrance** [comment]
Just pushed the commit from #1723 (and closed that PR).  (Apologies for the force push -- I'd forgotten that I'd left a very uninformative commit message in this branch!)

**Comment by DanGrayson** [comment]
> ```m2
> last capture("K = ZZ/101\nA = matrix\"1,2,3,4;1,3,6,10;19,7,11,13\" ** oo", UserMode => false)
> ```

Okay, I tried it out.  Removing that line seems to fix it.

**Comment by mahrud** [comment]
> Okay, I tried it out. Removing that line seems to fix it.

Removing which line?

**Comment by DanGrayson** [comment]
> > Okay, I tried it out. Removing that line seems to fix it.
> 
> Removing which line?

The line referred to here: "It must have to do with the line that I added in stdio.d, but I'm not sure what's the correct fix."

**Comment by mahrud** [comment]
> > Removing which line?
> 
> The line referred to here: "It must have to do with the line that I added in stdio.d, but I'm not sure what's the correct fix."

Removing that line causes nets to be printed completely randomly, how does that fix anything??

**Comment by mahrud** [comment]
Regardless, I think I fixed it in my last commit. You had added a line with a 100 character buffer for some reason. I don't know why.

**Comment by DanGrayson** [comment]
> > > Removing which line?
> > 
> > 
> > The line referred to here: "It must have to do with the line that I added in stdio.d, but I'm not sure what's the correct fix."
> 
> Removing that line causes nets to be printed completely randomly, how does that fix anything??

Maybe give me an example.  The one you gave me before does work with that line removed:
```m2
Macaulay2, version 1.16.99
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra, Saturation, TangentCone

i1 : last capture("K = ZZ/101\nA = matrix\"1,2,3,4;1,3,6,10;19,7,11,13\" ** oo", UserMode => false)

o1 = 
     i1 : K = ZZ/101

     o1 = K

     o1 : QuotientRing

     i2 : A = matrix"1,2,3,4;1,3,6,10;19,7,11,13" ** oo

     o2 = | 1  2 3  4  |
          | 1  3 6  10 |
          | 19 7 11 13 |

                  3       4
     o2 : Matrix K  <--- K

     i3 : 

```

**Comment by mahrud** [comment]
You don't appear to be on this branch at all. Look at these two tests:
https://github.com/mahrud/M2/blob/be6e8b23ebef9569e8187f30900f7ad0ee1965d0/M2/Macaulay2/tests/normal/capture.m2#L3-L20
Both of them simultaneously do not pass unless the line I added in stdio.d is there and the line you added in interp.dd is removed.

**Comment by mahrud** [comment]
Regardless, again, I think all issues are resolved. This PR is good to go.
Any other improvements to capture listed in #1689 (e.g. making it thread-safe or capturing cout and cerr coming directly from the engine) can wait for future releases.

**Comment by DanGrayson** [comment]
It doesn't seem to work on my mac:
```m2

+ /Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-release-1.17/M2 --no-readline -q --print-width 104
Macaulay2, version 1.16.99
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes,
               PrimaryDecomposition, ReesAlgebra, Saturation, TangentCone

i1 : input "~/src/M2/M2.git/M2/Macaulay2/tests/normal/capture.m2"

ii2 : -- See https://github.com/Macaulay2/M2/issues/1689
      
      -- printing nets
      (err, out) = capture " << id_(ZZ^0) << id_(ZZ^3) << id_(ZZ^2) << id_(ZZ^1);"

oo2 = (false,                                                           | 1 0 0 || 1 0 || 1 |)
              i1 :  << id_(ZZ^0) << id_(ZZ^3) << id_(ZZ^2) << id_(ZZ^1);| 0 1 0 || 0 1 |
              0                                                         | 0 0 1 |
              i2 : 


oo2 : Sequence

ii3 : assert(not err and out == "
      i1 :  << id_(ZZ^0) << id_(ZZ^3) << id_(ZZ^2) << id_(ZZ^1);
      0| 1 0 0 || 1 0 || 1 |
       | 0 1 0 || 0 1 |
       | 0 0 1 |
      i2 : \n")
../../../../../../Macaulay2/tests/normal/capture.m2:5:1:(3):[4]: error: assertion failed
../../../../../../Macaulay2/tests/normal/capture.m2:5:1:(3):[4]: --entering debugger (type help to see debugger commands)
../../../../../../Macaulay2/tests/normal/capture.m2:5:1-5:24: --source code:
assert(not err and out == "
```

I'm on your branch and I've recompiled and relinked:
```sh
gallium$ git log -1
commit be6e8b23ebef9569e8187f30900f7ad0ee1965d0 (HEAD)
Author: Mahrud Sayrafi <mahrud@berkeley.edu>
Date:   Tue Dec 22 09:44:25 2020 -0600

    fix a bug by removing a redundant line
```

**Comment by mahrud** [comment]
Why does it say 1.16.99 in your Macaulay2 prompt? This branch has version 1.17.0.1.

**Comment by mahrud** [comment]
This test passed on our github builds, so I think it's an issue with autotools not recompiling the proper files on your system.

**Comment by DanGrayson** [comment]
> This test passed on our github builds, so I think it's an issue with autotools not recompiling the proper files on your system.

I recompiled every single file in the d directory.  What else could there be?

**Comment by DanGrayson** [comment]
Maybe we should enable 'make check' in the autotools macos build.

**Comment by mahrud** [comment]
> I recompiled every single file in the d directory.  What else could there be?

I don't know. I don't use the autotools build. Does it know when it needs to relink? Try a fresh compilation, or try the CMake build maybe, it's smarter about dependencies.


I highly doubt that the code in this PR is incorrect, since the tests pass on both systems and the documentation is generated correctly.

**Comment by DanGrayson** [comment]
> > I recompiled every single file in the d directory.  What else could there be?
> 
> I don't know. I don't use the autotools build. Does it know when it needs to relink? Try a fresh compilation, or try the CMake build maybe, it's smarter about dependencies.
>


The cmake build doesn't work for me:
[log.txt](https://github.com/Macaulay2/M2/files/5737635/log.txt)

**Comment by DanGrayson** [comment]
Ah, here's why the cmake build doesn't work for me.  In an attempt not to link with dynamic libraries provided by homebrew, I have moved them out of the way.  And ninja has been told that only dynamic libraries are acceptable for some reason, even though the libraries come in pairs, one static and one dynamic.

**Comment by mahrud** [comment]
Added a few documentation changes and fixed the merge conflict. @DanGrayson is it building fine for you or still not working? I built with the autotools build and it works fine:
```m2
[mahrud@noether build]$ ./M2
Macaulay2, version 1.16.99
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes, PrimaryDecomposition,
               ReesAlgebra, Saturation, TangentCone

i1 : input "../../../Macaulay2/tests/normal/capture.m2";

ii2 : -- See https://github.com/Macaulay2/M2/issues/1689
      
      -- printing nets
      (err, out) = capture " << id_(ZZ^0) << id_(ZZ^3) << id_(ZZ^2) << id_(ZZ^1);"

oo2 = (false,                                                           )
              i1 :  << id_(ZZ^0) << id_(ZZ^3) << id_(ZZ^2) << id_(ZZ^1);
              0| 1 0 0 || 1 0 || 1 |
               | 0 1 0 || 0 1 |
               | 0 0 1 |
              i2 : 


oo2 : Sequence

ii3 : assert(not err and out == "
      i1 :  << id_(ZZ^0) << id_(ZZ^3) << id_(ZZ^2) << id_(ZZ^1);
      0| 1 0 0 || 1 0 || 1 |
       | 0 1 0 || 0 1 |
       | 0 0 1 |
      i2 : \n")

ii4 : 
      (err, out) = capture("K = ZZ/101\nA = matrix\"1,2,3,4;1,3,6,10;19,7,11,13\" ** oo", UserMode => false);

ii5 : assert(not err and match(regexQuote "
      i1 : K = ZZ/101\n\no1 = K\n\no1 : QuotientRing\n
      i2 : A = matrix\"1,2,3,4;1,3,6,10;19,7,11,13\" ** oo\n
      o2 = | 1  2 3  4  |
           | 1  3 6  10 |
           | 19 7 11 13 |\n
                   3       4
      o2 : Matrix K  <--- K\n" | ".*", out))

ii6 : 
      -- printing errors
      (err, out) = capture "1/0"

oo6 = (true,                                                   )
             i1 : 1/0
             currentString:1:2:(3):[7]: error: division by zero


oo6 : Sequence

ii7 : assert(err and match("\\A\ni1 : 1/0\ncurrentString:1:2:\\(3\\):\\[.\\]: error: division by zero\n\\Z", out))

ii8 : 
      -- make sure runaway existing private symbols are not changed
      -- TODO: how can we prevent new methods or hooks from escaping capture?
      assert(instance(K, Symbol))

ii9 : capture("K = ZZ/3", UserMode => false);

ii10 : assert(instance(K, Symbol))

ii11 : 

i12 : 
```

**Comment by DanGrayson** [comment]
Okay, after putting the dynamic libraries back (sigh), cmake managed to build it (under Mac OS 11.1), but the capture test still doesn't work.

[log2.txt](https://github.com/Macaulay2/M2/files/5740231/log2.txt)

**Comment by DanGrayson** [comment]
Aargh -- now it works.  It was my fault -- I still had that one line delete from stdio.d, so now the capture test works.

**Comment by mahrud** [comment]
> Maybe we should enable 'make check' in the autotools macos build.

Now that #1724 is merged, perhaps you can enable running the Core tests only. This is irrelevant for the purposes here, because the CMake is was already running the Core tests (including the capture test) on macOS and they were passing.

**Pull request merged**
